import { assessmentLearningCompletion } from '../../../lib/p2-original-learning-bridge';
import {AsyncLocalStorage} from 'node:async_hooks';
import {createHash,randomUUID} from 'node:crypto';
import {neon, type NeonQueryFunction} from '@neondatabase/serverless';
export type RouterContext={event:{headers:Record<string,string>};params:Record<string,string>;body:any;user?:{userId:string;name:string;scope:string}};
export type RouterMiddleware=(ctx:RouterContext)=>Promise<any>;
type Actor={role:'student'|'educator';id:string;studentId:string;academyId:string;label:string;studentSessionId?:string};
type State={sql:NeonQueryFunction<false,false>;actor:Actor;writes:any[];path:string;hash:string;request:Request;revisions:Map<string,number>;attemptCounts:Map<string,number>;previousStatuses:Map<string,string>};
export const context=new AsyncLocalStorage<State>();
const state=()=>{const s=context.getStore();if(!s)throw Error('request_context_missing');return s;};
export function json(data:any,statusCode=200){return{statusCode,headers:{'content-type':'application/json','cache-control':'no-store'},body:JSON.stringify(data)};}
export const error=(message:string,statusCode=400)=>json({error:message,message},statusCode);
export const canonicalEducatorAuth:RouterMiddleware=async ctx=>{const s=state();if(s.actor.role!=='educator')return error('Bağlı eğitmen girişi gerekli',401);ctx.user={userId:s.actor.id,name:s.actor.label,scope:'profile'};};
async function rows(ids?:string[]){const{sql,actor,revisions,attemptCounts,previousStatuses}=state();const r=await sql`SELECT id,metadata-'originalMedia' metadata FROM assessment_sessions WHERE student_id=${actor.studentId}::uuid AND metadata ? 'originalAssessment' AND (${ids===undefined} OR id=ANY(${ids||[]}::uuid[])) ORDER BY started_at DESC LIMIT 100`;return r.map(x=>{const value={...x.metadata.originalAssessment,id:x.id};revisions.set(x.id,Number(value.__revision||0));attemptCounts.set(x.id,value.attempts?.length||0);previousStatuses.set(x.id,value.status);return value;});}
function typedId(id:string){if(!/^[0-9a-f-]{36}$/i.test(id))throw Object.assign(Error('invalid_id'),{status:400});return id;}
export const db={
 async get<T>(table:string,ids:string[]):Promise<(T|undefined)[]>{if(table!=='assessment_sessions')throw Error('unsupported_table');ids.forEach(typedId);const found=await rows(ids);return ids.map(id=>found.find(r=>r.id===id)) as any;},
 async list<T>(table:string,_options?:any):Promise<{items:(T & {id:string})[]}>{const s=state();if(table==='assessment_sessions')return{items:await rows() as any};if(table==='cza_students')return{items:[{id:s.actor.studentId,name:s.actor.label,normalizedName:s.actor.label.trim().toLocaleLowerCase('tr-TR'),ownerUserId:s.actor.id,createdAt:null}] as any};if(table==='cza_report_versions'){const all=await s.sql`SELECT metadata->'originalReportVersions' versions FROM assessment_sessions WHERE student_id=${s.actor.studentId}::uuid AND metadata ? 'originalAssessment'`;return{items:all.flatMap(r=>r.versions||[]) as any};}throw Error('unsupported_table');},
 async add(table:string,records:any[]):Promise<string[]>{const s=state(),ids:string[]=[];for(const input of records){if(table==='cza_students'){ids.push(s.actor.studentId);continue;}const id=randomUUID();if(table==='cza_report_versions'){if(s.actor.role!=='educator')throw Object.assign(Error('educator_required'),{status:403});const record={...input,id,studentId:s.actor.studentId,ownerUserId:s.actor.id};s.writes.push(s.sql`UPDATE assessment_sessions SET metadata=jsonb_set(metadata,'{originalReportVersions}',COALESCE(metadata->'originalReportVersions','[]'::jsonb)||${JSON.stringify([record])}::jsonb) WHERE id=${typedId(input.sessionId)}::uuid AND student_id=${s.actor.studentId}::uuid`);ids.push(id);continue;}if(table!=='assessment_sessions')throw Error('unsupported_table');if(input.studentId&&input.studentId!==s.actor.studentId)throw Object.assign(Error('student_not_authorized'),{status:403});const record={...input,studentId:s.actor.studentId,studentLabel:s.actor.label,ownerUserId:s.actor.role==='educator'?s.actor.id:undefined,__revision:0};s.writes.push(s.sql`INSERT INTO assessment_sessions(id,student_id,template_code,student_label,status,current_task_code,metadata) VALUES(${id}::uuid,${s.actor.studentId}::uuid,'CZA_ORIGINAL_APPDEPLOY_V1',${s.actor.label},${record.status},${record.currentTaskId},${JSON.stringify({originalAssessment:record,moduleCode:'development_assessment',sourceVersion:'1790749888495'})}::jsonb)`);s.writes.push(s.sql`INSERT INTO training_sessions(id,academy_id,student_id,module_code,source,status,client_session_id,completion_client_record_id,settings_snapshot,engine_id,engine_version) VALUES(${id}::uuid,${s.actor.academyId}::uuid,${s.actor.studentId}::uuid,'development_assessment','free_practice','in_progress',${id}::uuid,${id}::uuid,${JSON.stringify({assessmentSessionId:id,originalAppVersion:'1790749888495'})}::jsonb,'CZA_ORIGINAL_ASSESSMENT','1790749888495')`);ids.push(id);}return ids;},
 async update(table:string,records:{id:string;record:any}[]):Promise<boolean[]>{if(table!=='assessment_sessions')throw Error('unsupported_table');const s=state();for(const {id,record:input}of records){typedId(id);const revision=s.revisions.get(id);if(revision===undefined)throw Error('session_not_read');const completing=input.status==='completed'&&s.previousStatuses.get(id)!=='completed';if(completing&&!s.actor.studentSessionId)throw Object.assign(Error('student_completion_required'),{status:403});const record={...input,studentId:s.actor.studentId,studentLabel:s.actor.label,__revision:revision+1};delete record.id;
 s.writes.push(s.sql`SELECT id FROM assessment_sessions WHERE id=${id}::uuid AND student_id=${s.actor.studentId}::uuid FOR UPDATE`);
 s.writes.push(s.sql`SELECT 1 / CASE WHEN EXISTS(SELECT 1 FROM assessment_sessions WHERE id=${id}::uuid AND student_id=${s.actor.studentId}::uuid AND (metadata->'originalAssessment'->>'__revision')::int=${revision}) THEN 1 ELSE 0 END AS revision_guard`);
 s.writes.push(s.sql`UPDATE assessment_sessions SET metadata=jsonb_set(jsonb_set(metadata,'{originalAssessment}',${JSON.stringify(record)}::jsonb),'{originalReplay}',COALESCE(metadata->'originalReplay','{}'::jsonb)||jsonb_build_object(${s.hash}::text,true)),status=${record.status},current_task_code=${record.currentTaskId||null},completed_at=CASE WHEN ${record.status==='completed'} THEN COALESCE(completed_at,now()) ELSE completed_at END WHERE id=${id}::uuid AND student_id=${s.actor.studentId}::uuid`);
 for(const [index,a]of (record.attempts||[]).entries()){if(index<(s.attemptCounts.get(id)||0))continue;const raw=createHash('sha256').update(id+':'+index+':'+a.taskId).digest('hex');const attemptId=raw.slice(0,8)+'-'+raw.slice(8,12)+'-4'+raw.slice(13,16)+'-a'+raw.slice(17,20)+'-'+raw.slice(20,32);s.writes.push(s.sql`INSERT INTO assessment_attempts(id,session_id,task_code,answer_text,answer_payload,support_level,response_latency_ms,total_response_time_ms,client_attempt_id,request_hash,server_evaluation) VALUES(${attemptId}::uuid,${id}::uuid,${a.taskId},${a.answer||null},${JSON.stringify(a)}::jsonb,${a.supportLevel||0},${a.responseLatencyMs??null},${a.totalResponseMs??null},${attemptId}::uuid,${createHash('sha256').update(JSON.stringify(a)).digest('hex')},${JSON.stringify({evaluatorId:'CZA_ORIGINAL_APPDEPLOY',evaluatorVersion:'1790749888495',responseOrigin:'client_reported',verdict:'unassessable'})}::jsonb) ON CONFLICT(id) DO NOTHING`);}
 s.writes.push(s.sql`UPDATE training_sessions SET answered_count=${record.attempts?.length||0},question_count=${record.attempts?.length||0},last_activity_at=now(),status=CASE WHEN ${record.status==='completed'} THEN 'completed'::session_status ELSE status END,completed_at=CASE WHEN ${record.status==='completed'} THEN COALESCE(completed_at,now()) ELSE completed_at END WHERE id=${id}::uuid AND student_id=${s.actor.studentId}::uuid AND academy_id=${s.actor.academyId}::uuid`);
 if(completing)s.writes.push(...assessmentLearningCompletion(s.sql as any,id,s.actor.studentSessionId!,'CZA_ORIGINAL_APPDEPLOY_V1','CZA_ORIGINAL_RECORD_IDENTITY'));
 }return records.map(()=>true);}
};
export const storage={async write(files:any[]){const s=state();for(const f of files){const id=f.path?.split('/')[1];typedId(id);if(!/^(early|voice)\//.test(f.path)||typeof f.content!=='string'||f.content.length>6000000||!f.contentType?.startsWith('audio/'))throw Object.assign(Error('invalid_audio'),{status:400});s.writes.push(s.sql`UPDATE assessment_sessions SET metadata=jsonb_set(metadata,'{originalMedia}',COALESCE(metadata->'originalMedia','{}'::jsonb)||jsonb_build_object(${f.path}::text,${JSON.stringify({content:f.content,contentType:f.contentType})}::jsonb)) WHERE id=${id}::uuid AND student_id=${s.actor.studentId}::uuid AND metadata ? 'originalAssessment'`);}return files.map(()=>true);}};
export function router(routes:Record<string,RouterMiddleware[]>){return async(request:Request,env:any,actor:Actor)=>{const url=new URL(request.url),sql=neon(env.DATABASE_URL);const body=['GET','HEAD'].includes(request.method)?undefined:await request.json();const hash=createHash('sha256').update(request.method+' '+url.pathname+' '+JSON.stringify(body)).digest('hex');const current:State={sql,actor,writes:[],path:url.pathname,hash,request,revisions:new Map(),attemptCounts:new Map(),previousStatuses:new Map()};return context.run(current,async()=>{try{const[project]=await sql`SELECT current_setting('neon.project_id',true) project`;if(project.project!=='patient-firefly-51111834')return error('wrong_synthetic_target',503);if(url.pathname==='/api/educator/me')return actor.role==='educator'?json({ok:true,userId:actor.id}):error('Eğitmen girişi gerekli',401);if(url.pathname==='/api/educator/setup-status')return json({configured:true});if(url.pathname.startsWith('/api/educator/')||url.pathname.startsWith('/api/admin/'))return error('Bu testte mevcut CZA kimlik girişi kullanılır',403);
 for(const[key,steps]of Object.entries(routes)){const[method,pattern]=key.split(' ');if(method!==request.method)continue;const names:string[]=[];const regex=new RegExp('^'+pattern.replace(/:([a-zA-Z]+)/g,(_,n)=>{names.push(n);return'([^/]+)';})+'$');const match=url.pathname.match(regex);if(!match)continue;const params=Object.fromEntries(names.map((n,i)=>[n,decodeURIComponent(match[i+1])]));if(params.id&&url.pathname.startsWith('/api/session/')){if(actor.role==='educator'&&!['GET','HEAD'].includes(request.method)&&!/(?:\/observe|\/area-observation|\/claim-student|\/approve-report|\/reopen-report)$/.test(url.pathname))return error('Öğrenci yanıtını yalnız öğrenci oturumu kaydeder',403);typedId(params.id);const [access]=await sql`SELECT status,metadata-'originalMedia' metadata FROM assessment_sessions WHERE id=${params.id}::uuid AND student_id=${actor.studentId}::uuid AND metadata ? 'originalAssessment'`;if(!access)return error('Bu kayda erişim yetkin yok',403);if(access.metadata.originalReplay?.[hash]&&request.method!=='GET'){const saved=access.metadata.originalReplay[hash];if(saved.body)return {statusCode:saved.statusCode,headers:{'content-type':'application/json','cache-control':'no-store'},body:saved.body};return json({...access.metadata.originalAssessment,id:params.id,replayed:true});}if(access.status==='completed'&&/\/(answer|restart-|early-development-response)/.test(url.pathname))return error('Tamamlanan kaydı yeniden değiştiremezsin',409);}
 if(params.id&&url.pathname.startsWith('/api/student/')&&params.id!==actor.studentId)return error('Öğrenci yetkisi yok',403);
 const ctx:RouterContext={event:{headers:Object.fromEntries(request.headers)},params,body};let result:any;for(const step of steps){result=await step(ctx);if(result!==undefined)break;}if(current.writes.length&&result?.statusCode<400){if(params.id&&url.pathname.startsWith('/api/session/'))current.writes.push(sql`UPDATE assessment_sessions SET metadata=jsonb_set(metadata,'{originalReplay}',COALESCE(metadata->'originalReplay','{}'::jsonb)||jsonb_build_object(${hash}::text,${JSON.stringify({statusCode:result.statusCode,body:result.body})}::jsonb)) WHERE id=${params.id}::uuid AND student_id=${actor.studentId}::uuid`);await sql.transaction(current.writes);}return result||error('Yanıt üretilemedi',500);}
 return error('İşlem bulunamadı',404);
 }catch(e:any){console.error('original_adapter_error',e?.code||'unknown');return error(e?.status===501?'Ses saklama bağlantısı henüz tamamlanmadı':e?.code==='22012'?'Kayıt başka bir istekte değişti, yenileyerek devam et':'İşlem tamamlanamadı',e?.status|| (e?.code==='22012'?409:503));}});};}
