import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import ts from 'typescript';
function load(file,modules,env,fetcher=fetch){const m={exports:{}};const js=ts.transpileModule(fs.readFileSync(new URL('../'+file,import.meta.url),'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText;new Function('require','module','exports','process','fetch',js)(id=>{if(!(id in modules))throw Error('Unknown import '+id);return modules[id]},m,m.exports,{env},fetcher);return m.exports;}
function harness(project='patient-firefly-51111834',branch='br-withered-queen-b15ltb40',fetcher=fetch){const env={DATABASE_URL:'test-only',CZA_EDUCATOR_AUTH_MODE:'neon-qa',CZA_NEON_AUTH_BASE_URL:'https://ep-polished-pine-b1r2qmye.neonauth.c-5.eu-central-1.aws.neon.tech/cza_t5_synthetic/auth'};let writes=0;const modules={'@neondatabase/serverless':{neon:()=>async()=>[{project,branch}]},'@/lib/educator-request-security':{readBoundedBytes:async r=>new Uint8Array(await r.arrayBuffer())},'@/lib/request-guard':{allowAccountRequest:async()=>({allowed:true}),allowRequest:async()=>{writes++;return {allowed:true}}}};const qa=load('lib/isolated-qa-auth.ts',modules,env);modules['@/lib/isolated-qa-auth']=qa;const ingress=load('lib/educator-neon-ingress.ts',modules,env,fetcher);return {env,qa,ingress,writes:()=>writes};}
const origin='https://cza-v01-isolated-synthetic-20261010.cza-staging-habip.workers.dev';const req=(base=origin,extra={})=>new Request(base+'/api/educator-auth',{method:'POST',headers:{origin:base,...extra},body:'{}'});
test('QA auth accepts only explicit QA origin and fixed synthetic provider',()=>{const h=harness();assert.equal(h.ingress.neonIngressAllowed(req()),true);for(const o of ['https://cza-akademi-staging.cza-staging-habip.workers.dev','https://evil.invalid','https://cza-p2-integrated-isolated.cza-staging-habip.workers.dev'])assert.equal(h.ingress.neonIngressAllowed(req(o)),false);h.env.CZA_NEON_AUTH_BASE_URL='https://evil.invalid';assert.equal(h.ingress.neonIngressAllowed(req()),false)});
test('forged trusted headers and cross-site ingress fail closed',()=>{const h=harness();for(const headers of [{'oai-authenticated-user-email':'owner@test.invalid'},{'x-cza-role':'educator'},{'sec-fetch-site':'cross-site'},{origin:'https://evil.invalid'}])assert.equal(h.ingress.neonIngressAllowed(req(origin,headers)),false)});
test('wrong DB target rejected before rate-limit writes or provider authentication',async()=>{const h=harness('production-project');let calls=0;const r=await h.ingress.handleNeonEducatorAuth(req(),{action:'me'},async()=>{calls++;return null},async()=>false);assert.equal(r.status,503);assert.equal((await r.json()).error,'qa_database_target_rejected');assert.equal(h.writes(),0);assert.equal(calls,0)});
test('QA password reset disabled without changing existing credentials',async()=>{const h=harness();const r=await h.ingress.handleNeonEducatorAuth(req(),{action:'request-reset',email:'fixture@cza.invalid'},async()=>null,async()=>true);assert.equal(r.status,403);assert.equal(h.writes(),0)});
test('ordinary Neon staging ingress remains restricted to existing provider',()=>{const h=harness();h.env.CZA_EDUCATOR_AUTH_MODE='neon';h.env.CZA_NEON_AUTH_BASE_URL='https://ep-falling-resonance-b2qnvtwf.neonauth.c-6.eu-central-1.aws.neon.tech/cza_learning/auth';assert.equal(h.ingress.neonIngressAllowed(req('https://cza-akademi-staging.cza-staging-habip.workers.dev')),true);assert.equal(h.ingress.neonIngressAllowed(req()),false)});

test('same project with a different branch is rejected before writes',async()=>{const h=harness('patient-firefly-51111834','br-curly-glitter-b1s8z9lw');const r=await h.ingress.handleNeonEducatorAuth(req(),{action:'me'},async()=>null,async()=>false);assert.equal(r.status,503);assert.equal(h.writes(),0)});

test('failed canonical mapping never hides failed provider revocation',async()=>{const h=harness(undefined,undefined,async url=>url.endsWith('/sign-in/email')?Response.json({}, {headers:{'set-cookie':'__Secure-neon-auth.session_token=test-token.signature; Path=/; Secure; HttpOnly'}}):new Response(null,{status:503}));const r=await h.ingress.handleNeonEducatorAuth(req(),{action:'login',email:'fixture@cza.invalid',password:'test-password'},async()=>null,async()=>false);assert.equal(r.status,503);assert.equal((await r.json()).error,'logout_revocation_failed')});
