import assert from 'node:assert/strict';
import { spawn } from 'node:child_process';
import { mkdtemp,rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { dirname,join,resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { inflate } from '@sparticuz/chromium';
import puppeteer from 'puppeteer-core';

const origin='http://127.0.0.1:4187';let browser,server,browserTemp;
const student={id:'c2000000-0000-4000-8000-000000000003',name:'Trust Boundary Demo',code:'U7-DEMO',username:'u2-high-fix-demo'};
const profile={ok:true,profile:{student:{id:student.id,name:student.name,recordedFrom:'2026-09-17T10:00:00Z'},calculatedAt:'2026-09-17T21:05:00Z',dataThrough:'2026-09-17T21:00:52Z',coverage:{assignments:5,sessions:4,attempts:8,records:3,evidence:1},studyPattern:{assignments:{active:2,completed:2,cancelled:2},sessions:{total:4,completed:3,activeDaysLast30:1,lastStudyAt:'2026-09-17T21:00:52Z'},provenance:'SERVER_AUTHORITATIVE'},modules:[{moduleCode:'flash_anzan',moduleName:'Flash Anzan',assignments:1,sessions:1,records:1,attempts:2,clientReportedAccuracy:50,provenance:'MIXED',sourceReferences:['training_recipes','training_sessions','question_attempts','learning_records']}],skills:[{skillCode:'U7_DEMO_CLIENT_SKILL',moduleCode:'flash_anzan',recordCount:1,provenance:'CLIENT_REPORTED',sourceReferences:['evidence:demo']}],errors:[{errorType:'U7_DEMO_CLIENT_REPORTED',count:1,provenance:'CLIENT_REPORTED',sourceReference:'question_attempts'}],process:{supportLevels:[{supportLevel:'unknown',count:1,provenance:'CLIENT_REPORTED'}],strategy:null,selfCorrection:null,repetition:null,transfer:null,insufficiencyReason:null},periods:[{label:'LAST_30_DAYS',from:'2026-08-18T00:00:00Z',to:'2026-09-17T00:00:00Z',sessions:4,records:3,attempts:8,clientReportedAccuracy:50,provenance:'MIXED'},{label:'PREVIOUS_30_DAYS',from:'2026-07-19T00:00:00Z',to:'2026-08-18T00:00:00Z',sessions:0,records:0,attempts:0,clientReportedAccuracy:null,provenance:'SERVER_AUTHORITATIVE'}]}};
const dashboard={ok:true,dashboard:{profile:{id:student.id,name:student.name,username:student.username},summary:{activeAssignments:2,completedSessions:3,totalAttempts:8,correctAttempts:4,accuracy:50,availableAssignments:1,inProgressAssignments:0,completedAssignments:2},assignments:[],recentActivity:[],skillProfile:[]}};
const detail={ok:true,student:{...student,campusCode:student.code},work:{active:[],completed:[]},attempts:[],errors:[],evidence:[],history:[],learningProfile:{clientReportedSkills:[],serverVerifiedSkills:[],clientReportedRecordCount:3,serverVerifiedEvidenceCount:0}};
const emptyTimeline={ok:true,timeline:{events:[],hasMore:false,nextCursor:null}};
async function binary(){browserTemp=await mkdtemp(join(tmpdir(),'cza-u7-browser-'));const entry=fileURLToPath(import.meta.resolve('@sparticuz/chromium'));return inflate(resolve(dirname(entry),'../bin/chromium.br'));}
async function startServer(){const child=spawn(process.execPath,['tests/u7-learning-profile-e2e-server.mjs'],{cwd:process.cwd(),env:{...process.env,NODE_ENV:'development'},stdio:['ignore','pipe','pipe']});await new Promise((ready,reject)=>{const timeout=setTimeout(()=>reject(new Error('U7_BROWSER_SERVER_TIMEOUT')),20000);const inspect=chunk=>{if(chunk.toString().includes('CZA_U7_E2E_READY')){clearTimeout(timeout);ready();}};child.stdout.on('data',inspect);child.stderr.on('data',inspect);child.once('exit',code=>reject(new Error(`U7_BROWSER_SERVER_EXIT_${code}`)));});return child;}
async function assertViewport(page,path,width,height){await page.setViewport({width,height,deviceScaleFactor:1});await page.goto(`${origin}${path}`,{waitUntil:'networkidle0'});await page.waitForFunction(()=>document.body.innerText.includes('Öğrenme Profili')&&document.body.innerText.includes('İstemci bildirimi'));const state=await page.evaluate(()=>({profile:document.body.innerText.includes('Öğrenme Profili'),trace:document.body.innerText.includes('Kaynak: training_recipes'),reported:document.body.innerText.includes('İstemci bildirimi'),fakeVerified:document.body.innerText.includes('Doğrulanmış başarı'),falseZero:document.body.innerText.includes('İstemci doğruluğu: %0'),overflow:document.documentElement.scrollWidth>window.innerWidth,wide:[...document.querySelectorAll('*')].filter(element=>element.getBoundingClientRect().right>window.innerWidth+1).slice(0,5).map(element=>({tag:element.tagName,className:element.className,text:element.textContent?.slice(0,60)}))}));assert.deepEqual({...state,wide:[]},{profile:true,trace:true,reported:true,fakeVerified:false,falseZero:false,overflow:false,wide:[]},`${path} ${width}x${height} ${JSON.stringify(state.wide)}`);}
try{server=await startServer();browser=await puppeteer.launch({executablePath:await binary(),headless:true,args:['--no-sandbox','--disable-setuid-sandbox']});const page=await browser.newPage();const errors=[];page.on('console',message=>{if(message.type()==='error')errors.push(message.text());});page.on('pageerror',error=>errors.push(error.message));await page.setRequestInterception(true);page.on('request',request=>{const url=new URL(request.url());const respond=body=>request.respond({status:200,contentType:'application/json',body:JSON.stringify(body)});if(url.pathname==='/api/core/dashboard')return void respond(dashboard);if(url.pathname==='/api/core/learning-profile'||url.pathname==='/api/educator-learning-profile')return void respond(profile);if(url.pathname==='/api/core/history'||url.pathname==='/api/educator-student-history')return void respond(emptyTimeline);if(url.pathname==='/api/educator-auth')return void respond({ok:true,user:{name:'U7 Demo Eğitmen'}});if(url.pathname==='/api/educator-students')return void respond({ok:true,students:[student],hasMore:false});if(url.pathname==='/api/educator-student-detail')return void respond(detail);if(url.pathname==='/api/educator-assignments')return void respond({ok:true,assignments:[]});if(url.pathname==='/api/educator-analytics')return void respond({ok:true,student,filters:{},report:{summary:{assignments:null,sessions:null,clientPerformance:null},modules:[],errors:[],evidence:[],trend:[],sessions:[],nextCursor:null}});void request.continue();});for(const [path,width,height] of [['/',1440,900],['/',768,1024],['/',390,844],['/educator',1440,900],['/educator',768,1024],['/educator',390,844]])await assertViewport(page,path,width,height);assert.deepEqual(errors,[]);process.stdout.write('U7_BROWSER_ACCEPTANCE=PASS UI_DESKTOP=PASS UI_TABLET=PASS UI_MOBILE=PASS HORIZONTAL_OVERFLOW=false CONSOLE_ERRORS=0 MODE=LOCAL_UI_WITH_STAGING_DERIVED_DEMO_FIXTURE\n');}finally{if(browser)await browser.close();if(server&&!server.killed)server.kill('SIGTERM');if(browserTemp)await rm(browserTemp,{recursive:true,force:true});}
