import assert from 'node:assert/strict';
import { spawn } from 'node:child_process';
import { mkdtemp, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { inflate } from '@sparticuz/chromium';
import puppeteer from 'puppeteer-core';

const origin = 'http://127.0.0.1:4187';
let browser; let server; let browserTemp;
const student = { id: 'c2000000-0000-4000-8000-000000000003', name: 'U8 Demo Öğrenci', code: 'U8-DEMO', username: 'u8-demo' };
const coaching = { programs: [{ id: '88000000-0000-4000-8000-000000000101', program_type: 'LGS', status: 'active' }], goals: [{ id: '88000000-0000-4000-8000-000000000102' }], topics: [], plans: [{ id: '88000000-0000-4000-8000-000000000103', status: 'published', version: 1, items: [{ itemId: '88000000-0000-4000-8000-000000000104', recipeId: '88000000-0000-4000-8000-000000000105', name: 'U8 Matematik Planı', taskKind: 'academic', subject: 'MAT', topic: 'Çarpanlar', active: true }] }], studyLogs: [], exams: [{ id: '88000000-0000-4000-8000-000000000106', stage: 'LGS', total_net: 33 }], mistakes: [], meetings: [{ id: '88000000-0000-4000-8000-000000000107', shared_summary: 'Çarpanlar tekrar edilecek.' }], templates: [], provenance: 'CLIENT_REPORTED' };
const profile = { ok: true, profile: { student: { id: student.id, name: student.name, recordedFrom: null }, calculatedAt: new Date().toISOString(), dataThrough: null, coverage: { assignments: 0, sessions: 0, attempts: 0, records: 0, evidence: 0 }, studyPattern: { assignments: { active: 0, completed: 0, cancelled: 0 }, sessions: { total: 0, completed: 0, activeDaysLast30: 0, lastStudyAt: null }, provenance: 'SERVER_AUTHORITATIVE' }, modules: [], skills: [], errors: [], process: { supportLevels: [], strategy: null, selfCorrection: null, repetition: null, transfer: null, insufficiencyReason: 'Yeterli kayıt yok' }, periods: [], coaching: { activePrograms: 1, publishedPlans: 1, studyLogs: 0, examResults: 1, performanceProvenance: 'CLIENT_REPORTED' } } };
const dashboard = { ok: true, dashboard: { profile: { id: student.id, name: student.name, username: student.username }, summary: { activeAssignments: 0, completedSessions: 0, totalAttempts: 0, correctAttempts: 0, accuracy: null, availableAssignments: 0, inProgressAssignments: 0, completedAssignments: 0 }, assignments: [], recentActivity: [], skillProfile: [] } };
const detail = { ok: true, student: { ...student, campusCode: student.code }, work: { active: [], completed: [] }, attempts: [], errors: [], evidence: [], history: [], learningProfile: { clientReportedSkills: [], serverVerifiedSkills: [], clientReportedRecordCount: 0, serverVerifiedEvidenceCount: 0 } };
const emptyTimeline = { ok: true, timeline: { events: [], hasMore: false, nextCursor: null } };

async function binary() { browserTemp = await mkdtemp(join(tmpdir(), 'cza-u8-browser-')); const entry = fileURLToPath(import.meta.resolve('@sparticuz/chromium')); return inflate(resolve(dirname(entry), '../bin/chromium.br')); }
async function startServer() { const child = spawn(process.execPath, ['tests/u7-learning-profile-e2e-server.mjs'], { cwd: process.cwd(), env: { ...process.env, NODE_ENV: 'development' }, stdio: ['ignore', 'pipe', 'pipe'] }); await new Promise((ready, reject) => { const timeout = setTimeout(() => reject(new Error('U8_BROWSER_SERVER_TIMEOUT')), 20000); const inspect = chunk => { if (chunk.toString().includes('CZA_U7_E2E_READY')) { clearTimeout(timeout); ready(); } }; child.stdout.on('data', inspect); child.stderr.on('data', inspect); child.once('exit', code => reject(new Error(`U8_BROWSER_SERVER_EXIT_${code}`))); }); return child; }
async function viewport(page, path, width, height) { await page.setViewport({ width, height, deviceScaleFactor: 1 }); await page.goto(`${origin}${path}`, { waitUntil: 'networkidle0' }); await page.waitForFunction(() => document.body.innerText.includes('Koçluk Merkezi') && document.body.innerText.includes('İstemci bildirimi')); const state = await page.evaluate(() => ({ text: document.body.innerText, overflow: document.documentElement.scrollWidth > window.innerWidth, overlay: Boolean(document.querySelector('[data-nextjs-dialog], .vite-error-overlay, #webpack-dev-server-client-overlay')) })); for (const label of ['Koçluk Merkezi', 'U8 Matematik Planı', 'İstemci bildirimi']) assert.ok(state.text.includes(label), `${path}: ${label}`); assert.equal(state.overflow, false, `${path} ${width}x${height} overflow`); assert.equal(state.overlay, false, `${path} error overlay`); }

try {
  server = await startServer(); browser = await puppeteer.launch({ executablePath: await binary(), headless: true, args: ['--no-sandbox', '--disable-setuid-sandbox'] });
  const page = await browser.newPage(); const errors = [];
  page.on('console', message => { if (message.type() === 'error') errors.push(message.text()); }); page.on('pageerror', error => errors.push(error.message));
  await page.setRequestInterception(true);
  page.on('request', request => { const url = new URL(request.url()); const respond = body => request.respond({ status: 200, contentType: 'application/json', body: JSON.stringify(body) }); if (url.pathname === '/api/core/dashboard') return void respond(dashboard); if (url.pathname === '/api/core/coaching' || url.pathname === '/api/educator-coaching') return void respond({ ok: true, coaching }); if (url.pathname === '/api/core/learning-profile' || url.pathname === '/api/educator-learning-profile') return void respond(profile); if (url.pathname === '/api/core/history' || url.pathname === '/api/educator-student-history') return void respond(emptyTimeline); if (url.pathname === '/api/educator-auth') return void respond({ ok: true, user: { name: 'U8 Demo Eğitmen' } }); if (url.pathname === '/api/educator-students') return void respond({ ok: true, students: [student], hasMore: false }); if (url.pathname === '/api/educator-student-detail') return void respond(detail); if (url.pathname === '/api/educator-assignments') return void respond({ ok: true, assignments: [] }); if (url.pathname === '/api/educator-analytics') return void respond({ ok: true, student, filters: {}, report: { summary: { assignments: null, sessions: null, clientPerformance: null }, modules: [], errors: [], evidence: [], trend: [], sessions: [], nextCursor: null } }); void request.continue(); });
  for (const [path, width, height] of [['/', 1440, 900], ['/', 768, 1024], ['/', 390, 844], ['/educator', 1440, 900], ['/educator', 768, 1024], ['/educator', 390, 844]]) await viewport(page, path, width, height);
  assert.deepEqual(errors, []);
  process.stdout.write('U8_BROWSER_ACCEPTANCE=PASS UI_DESKTOP=PASS UI_TABLET=PASS UI_MOBILE=PASS HORIZONTAL_OVERFLOW=false ERROR_OVERLAY=false CONSOLE_ERRORS=0 MODE=LOCAL_UI_WITH_EXPLICIT_FIXTURE\n');
} finally { if (browser) await browser.close(); if (server && !server.killed) server.kill('SIGTERM'); if (browserTemp) await rm(browserTemp, { recursive: true, force: true }); }
