import { neon } from '@neondatabase/serverless';
import { authenticatedStudent } from '@/lib/student-session';
import { allowRequest,rateLimited } from '@/lib/request-guard';
import { CoachingError,readCoachingCenter,recordExam,recordStudy,submitMeetingFeedback,type CoachingActor } from '@/lib/persistence/coaching-center';

const json=(body:unknown,status=200)=>Response.json(body,{status,headers:{'cache-control':'no-store'}});
async function context(request:Request){const student=await authenticatedStudent(request);if(!student)throw new CoachingError('session_required',401);const gate=await allowRequest(request,'student-coaching',40,60_000,student.student_id);if(!gate.allowed)return{limited:rateLimited(gate)};if(!process.env.DATABASE_URL)throw new CoachingError('database_unavailable',503);return{sql:neon(process.env.DATABASE_URL),actor:{userId:student.student_user_id,academyId:student.academy_id,studentId:student.student_id,canCoach:false} as CoachingActor};}
export async function GET(request:Request){try{const ctx=await context(request);if('limited'in ctx)return ctx.limited;const url=new URL(request.url);const limit=Number(url.searchParams.get('limit')||20);return json({ok:true,coaching:await readCoachingCenter(ctx.sql,ctx.actor,{studentView:true,limit,cursor:url.searchParams.get('cursor')})});}catch(error){const e=error instanceof CoachingError?error:new CoachingError('coaching_unavailable',503);return json({ok:false,error:e.code},e.status);}}
export async function POST(request:Request){const origin=request.headers.get('origin');if(origin&&origin!==new URL(request.url).origin)return json({ok:false,error:'request_origin_rejected'},403);try{const ctx=await context(request);if('limited'in ctx)return ctx.limited;const input=await request.json() as Record<string,unknown>;const action=typeof input.action==='string'?input.action:'';const result=action==='study_log'?await recordStudy(ctx.sql,ctx.actor,input):action==='exam'?await recordExam(ctx.sql,ctx.actor,input):action==='meeting_feedback'?await submitMeetingFeedback(ctx.sql,ctx.actor,input):(()=>{throw new CoachingError('student_action_not_allowed',403);})();return json({ok:true,result},201);}catch(error){const e=error instanceof CoachingError?error:new CoachingError('coaching_write_failed',503);return json({ok:false,error:e.code},e.status);}}
