import { useEffect, useMemo, useRef, useState } from 'react';
import { BrainCircuit, Eye, RefreshCw, ShieldCheck, Sparkles, Waypoints } from 'lucide-react';

type Domain='math'|'lang'|'memory'|'spatial'|'plan'|'flex';
type Choice={id:string;label?:string};
type Item={id:string;domain:Domain;title:string;prompt:string;correct:string;choices:Choice[];memory?:boolean};
type Row={id:string;domain:Domain;answer:string;score:number;max:number;ms:number;changes:number};
type PriorAttempt={taskId:string;answer:string};
type Signal={sum:number;n:number};

const domains:Domain[]=['math','lang','memory','spatial','plan','flex'];
const labels:Record<Domain,string>={math:'Matematiksel Muhakeme',lang:'Anlama ve Çıkarım',memory:'Çalışma Belleği',spatial:'Görsel-Uzamsal',plan:'Problem ve Planlama',flex:'Esneklik ve Transfer'};
const bank:Record<Domain,Item[]>={
math:[{id:'MA1',domain:'math',title:'İki koşulu birlikte tut',prompt:'İki sayının toplamı 36, aralarındaki fark 8. Hangi çift iki koşulu da sağlıyor?',correct:'14+22',choices:[{id:'12+24',label:'12 + 24'},{id:'14+22',label:'14 + 22'},{id:'16+20',label:'16 + 20'},{id:'10+26',label:'10 + 26'}]},{id:'MA2',domain:'math',title:'Eksik parçayı tamamla',prompt:'Bir kutuda 24 boncuk var. İki kutuda toplam 40 boncuk olması için diğer kutuda kaç boncuk olmalı?',correct:'16',choices:[{id:'14',label:'14'},{id:'16',label:'16'},{id:'18',label:'18'},{id:'20',label:'20'}]}],
lang:[{id:'LA1',domain:'lang',title:'Nedeni çıkar',prompt:'Bahçe toprağı sabah sulandı. Öğleden sonra çocuk toprağa dokundu; hâlâ nemliydi. Sulama kabını yerine bıraktı. Neden yeniden sulamadı?',correct:'moist',choices:[{id:'moist',label:'Toprak hâlâ nemli olduğu için'},{id:'empty',label:'Sulama kabı boş olduğu için'},{id:'late',label:'Akşam olduğu için'},{id:'forgot',label:'Sulamayı unuttuğu için'}]},{id:'LA2',domain:'lang',title:'İpucunu birleştir',prompt:'Sınıftaki pencere açıktı. Masadaki hafif kâğıtlar birden havalandı, dışarıdaki ağaç dalları hızla sallandı. En güçlü çıkarım hangisi?',correct:'wind',choices:[{id:'wind',label:'Rüzgâr güçlendi.'},{id:'rain',label:'Yağmur kesin başladı.'},{id:'class',label:'Ders bitti.'},{id:'door',label:'Kapı kilitlendi.'}]}],
memory:[{id:'ME1',domain:'memory',title:'Dört izi aklında tut',prompt:'Diziyi kısa süre incele. Görüntü kapanınca aynı sırayı seç.',correct:'tc-gs-vt-bs',memory:true,choices:[{id:'tc-gs-vt-bs'},{id:'tc-vt-gs-bs'},{id:'gs-tc-vt-bs'},{id:'tc-gs-bs-vt'}]},{id:'ME2',domain:'memory',title:'Konumları koru',prompt:'Üç işaretin yerini aklında tut. Pano kapanınca aynı düzeni bul.',correct:'g2',memory:true,choices:[{id:'g1'},{id:'g2'},{id:'g3'},{id:'g4'}]}],
spatial:[{id:'SP1',domain:'spatial',title:'Çeyrek tur döndür',prompt:'Soldaki şekli 90° saat yönünde döndür. Oluşan şekli seç.',correct:'r90',choices:[{id:'r0'},{id:'r90'},{id:'r180'},{id:'r270'}]},{id:'SP2',domain:'spatial',title:'Aynanın öbür tarafı',prompt:'Dikey aynada sol ve sağ yer değiştirir. Aynı düzenin gerçek ayna görüntüsünü seç.',correct:'m2',choices:[{id:'m1'},{id:'m2'},{id:'m3'},{id:'m4'}]}],
plan:[{id:'PL1',domain:'plan',title:'Bağımlılıkları sırala',prompt:'Kural: Önce yönergeyi oku; sonra malzemeyi seç; seçtikten sonra kutuya koy; etiketi en son yapıştır. Hangi sıra kurala tam uyuyor?',correct:'order',choices:[{id:'order',label:'Yönerge → Malzeme → Kutu → Etiket'},{id:'o2',label:'Malzeme → Yönerge → Kutu → Etiket'},{id:'o3',label:'Yönerge → Kutu → Malzeme → Etiket'},{id:'o4',label:'Yönerge → Malzeme → Etiket → Kutu'}]},{id:'PL2',domain:'plan',title:'Sınırı aşmadan seç',prompt:'Çanta en fazla 5 kg taşıyor. Pil 2 kg ve sensör 1 kg zorunlu. Yanına yalnız bir araç alabilirsin. Çantayı aşmadan alabileceğin en ağır araç hangisi?',correct:'wrench',choices:[{id:'pliers',label:'Pense · 3 kg'},{id:'wrench',label:'Anahtar · 2 kg'},{id:'lamp',label:'Fener · 1 kg'},{id:'none',label:'Hiçbiri'}]}],
flex:[{id:'FL1',domain:'flex',title:'Dönüşümü yeni şekle taşı',prompt:'Örneklerde küçük ve boş şekil, büyük ve dolu hâle dönüşüyor. Aynı dönüşümü üçgene uygula.',correct:'large-filled',choices:[{id:'small-filled',label:'Küçük dolu üçgen'},{id:'large-outline',label:'Büyük boş üçgen'},{id:'large-filled',label:'Büyük dolu üçgen'},{id:'large-circle',label:'Büyük dolu daire'}]},{id:'FL2',domain:'flex',title:'Eski kuralı bırak',prompt:'Eski kural: altın kart sağ kapıya, mavi kart sol kapıya gider. Yeni tabela “Kuralları tersine çevir” diyor. Mavi kare hangi kapıya gitmeli?',correct:'right',choices:[{id:'left',label:'Sol kapı'},{id:'right',label:'Sağ kapı'},{id:'stop',label:'Bekle'},{id:'both',label:'İki kapı da'}]}]
};

function add(s:Record<Domain,Signal>,d:Domain,v:number){if(Number.isFinite(v)&&v>=0&&v<=1){s[d].sum+=v;s[d].n++}}
function signals(attempts:PriorAttempt[]){const s=Object.fromEntries(domains.map(d=>[d,{sum:0,n:0}])) as Record<Domain,Signal>;for(const a of attempts){let m;if(a.taskId==='M1A'&&(m=a.answer.match(/^MS\|n=(\d+)\|c=(\d+)/)))add(s,'math',Number(m[2])/Math.max(1,Number(m[1])));if(a.taskId==='L1A'&&(m=a.answer.match(/\|comp=(\d+)\/(\d+)/)))add(s,'lang',Number(m[1])/Math.max(1,Number(m[2])));if(a.taskId==='DX1'){m=a.answer.match(/\|reason=(\d+)\/(\d+)\|organ=\d+\/\d+\|meaning=(\d+)\/(\d+)/);if(m)add(s,'lang',(Number(m[1])/Math.max(1,Number(m[2]))+Number(m[3])/Math.max(1,Number(m[4])))/2)}if(a.taskId==='RF1'&&(m=a.answer.match(/\|comp=(\d+)\/(\d+)/)))add(s,'lang',Number(m[1])/Math.max(1,Number(m[2])));if(a.taskId==='WM1'){m=a.answer.match(/\|aud=(\d+)\/(\d+)\|work=(\d+)\/(\d+)\|inst=(\d+)\/(\d+)/);if(m)add(s,'memory',(Number(m[1])+Number(m[3])+Number(m[5]))/Math.max(1,Number(m[2])+Number(m[4])+Number(m[6])))}if(a.taskId==='GV1'){m=a.answer.match(/\|spatial=(\d+)\/(\d+)\|rule=\d+\/\d+\|attention=\d+\/\d+\|memory=(\d+)\/(\d+)\|problem=(\d+)\/(\d+)/);if(m){add(s,'spatial',Number(m[1])/Math.max(1,Number(m[2])));add(s,'memory',Number(m[3])/Math.max(1,Number(m[4])));add(s,'plan',Number(m[5])/Math.max(1,Number(m[6])))}}if(a.taskId==='ZX1'){m=a.answer.match(/\|rule=\d+\/\d+\|flex=(\d+)\/(\d+)\|spatial=(\d+)\/(\d+)\|plan=(\d+)\/(\d+)/);if(m){add(s,'flex',Number(m[1])/Math.max(1,Number(m[2])));add(s,'spatial',Number(m[3])/Math.max(1,Number(m[4])));add(s,'plan',Number(m[5])/Math.max(1,Number(m[6])))}}if(a.taskId==='EX1'){m=a.answer.match(/\|plan=(\d+)\/(\d+)\|adapt=(\d+)\/(\d+)/);if(m){add(s,'plan',Number(m[1])/Math.max(1,Number(m[2])));add(s,'flex',Number(m[3])/Math.max(1,Number(m[4])))}}if(a.taskId==='HB1'&&(m=a.answer.match(/\|switch=(\d+)\/(\d+)/)))add(s,'flex',Number(m[1])/Math.max(1,Number(m[2])))}return s}
function buildPlan(attempts:PriorAttempt[]){const s=signals(attempts);const observed=domains.filter(d=>s[d].n>0);if(observed.length<3)return{focus:domains,items:domains.map(d=>bank[d][0])};const focus=[...domains].sort((a,b)=>(s[a].sum/s[a].n)-(s[b].sum/s[b].n)).slice(0,3);return{focus,items:[...focus.map(d=>bank[d][0]),...focus.map(d=>bank[d][1])]}}
function shuffle(a:Choice[]){const x=[...a];for(let i=x.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[x[i],x[j]]=[x[j],x[i]]}return x}
function Token({kind}:{kind:string}){const[tone,shape]=kind.split('-');const pts=shape==='triangle'?'50,10 90,84 10,84':shape==='star'?'50,7 61,36 92,36 67,55 77,86 50,68 23,86 33,55 8,36 39,36':'';return <svg className={'av-token '+tone} viewBox='0 0 100 100' aria-hidden='true'>{shape==='circle'?<circle cx='50' cy='50' r='35'/>:shape==='square'?<rect x='16' y='16' width='68' height='68' rx='10'/>:<polygon points={pts}/>}</svg>}
const seqs:Record<string,string[]>={'tc-gs-vt-bs':['teal-circle','gold-star','violet-triangle','blue-square'],'tc-vt-gs-bs':['teal-circle','violet-triangle','gold-star','blue-square'],'gs-tc-vt-bs':['gold-star','teal-circle','violet-triangle','blue-square'],'tc-gs-bs-vt':['teal-circle','gold-star','blue-square','violet-triangle']};
const boards:Record<string,Record<number,string>>={target:{0:'gold-star',4:'blue-circle',8:'coral-square'},g1:{0:'gold-star',4:'blue-circle',7:'coral-square'},g2:{0:'gold-star',4:'blue-circle',8:'coral-square'},g3:{2:'gold-star',4:'blue-circle',8:'coral-square'},g4:{0:'blue-circle',4:'gold-star',8:'coral-square'},mirrorTarget:{0:'gold-star',3:'teal-circle',7:'violet-triangle'},m1:{0:'gold-star',5:'teal-circle',7:'violet-triangle'},m2:{2:'gold-star',5:'teal-circle',7:'violet-triangle'},m3:{2:'gold-star',3:'teal-circle',7:'violet-triangle'},m4:{6:'gold-star',5:'teal-circle',1:'violet-triangle'}};
function Board({variant}:{variant:string}){const map=boards[variant];return <span className='av-board'>{Array.from({length:9},(_,i)=><i key={i}>{map[i]?<Token kind={map[i]}/>:null}</i>)}</span>}
const rot:Record<string,number[]>={r0:[0,2,3],r90:[0,1,2],r180:[0,1,3],r270:[1,2,3]};
function Block({cells}:{cells:number[]}){return <span className='av-block'>{Array.from({length:4},(_,i)=><i key={i} className={cells.includes(i)?'on':''}/>)}</span>}
function domainIcon(d:Domain){return d==='memory'?<Eye/>:d==='spatial'?<RefreshCw/>:d==='plan'?<Waypoints/>:<BrainCircuit/>}

export default function AdaptiveTransferLab({studentLabel,attempts,busy,onFinish,err,onActivity}:{studentLabel?:string;attempts:PriorAttempt[];busy:boolean;onFinish:(value:string)=>void;err:string;onActivity:()=>void}){
const plan=useMemo(()=>buildPlan(attempts),[attempts]);const items=plan.items;const[idx,setIdx]=useState(0);const[selected,setSelected]=useState('');const[changes,setChanges]=useState(0);const[rows,setRows]=useState<Row[]>([]);const[breakMode,setBreakMode]=useState(false);const[phase,setPhase]=useState<'study'|'retain'|'answer'>('answer');const responseStarted=useRef(Date.now());const item=items[idx];const choices=useMemo(()=>shuffle(item.choices),[item.id]);
useEffect(()=>{setSelected('');setChanges(0);if(!item.memory){setPhase('answer');responseStarted.current=Date.now();return}setPhase('study');let b=0;const a=window.setTimeout(()=>{setPhase('retain');b=window.setTimeout(()=>{setPhase('answer');responseStarted.current=Date.now()},900)},4000);return()=>{window.clearTimeout(a);if(b)window.clearTimeout(b)}},[item.id]);
const choose=(id:string)=>{if(busy||phase!=='answer')return;onActivity();if(selected&&selected!==id)setChanges(v=>v+1);setSelected(id)};
const encode=(rs:Row[])=>{const stat=(d:Domain)=>{const x=rs.filter(r=>r.domain===d);return x.reduce((n,r)=>n+r.score,0)+'/'+x.reduce((n,r)=>n+r.max,0)};return 'AV|n='+rs.length+'|math='+stat('math')+'|lang='+stat('lang')+'|memory='+stat('memory')+'|spatial='+stat('spatial')+'|plan='+stat('plan')+'|flex='+stat('flex')+'|focus='+plan.focus.join('+')+'|r='+rs.map(r=>r.id+'~'+r.answer+'~'+r.score+'~'+r.ms+'~'+r.changes).join(',')};
const next=(skip=false)=>{if(((!selected||phase!=='answer')&&!skip)||busy)return;const row:Row={id:item.id,domain:item.domain,answer:skip?'SKIP':selected,score:skip?0:selected===item.correct?1:0,max:skip?0:1,ms:Math.max(0,Date.now()-responseStarted.current),changes};const rs=[...rows,row];if(idx===items.length-1){onFinish(encode(rs));return}setRows(rs);if(idx===2){setBreakMode(true);return}setIdx(v=>v+1)};
const resume=()=>{setBreakMode(false);setIdx(3)};
const visual=()=>{if(item.id==='ME1'&&phase==='study')return <div className='av-seq'>{seqs[item.correct].map((x,i)=><span key={i}><Token kind={x}/></span>)}</div>;if(item.id==='ME2'&&phase==='study')return <Board variant='target'/>;if(item.id==='SP1')return <div className='av-rotate'><Block cells={rot.r0}/><RefreshCw/><b>90°</b></div>;if(item.id==='SP2')return <div className='av-mirror'><Board variant='mirrorTarget'/><i/><strong>AYNA</strong></div>;if(item.id==='PL2')return <div className='av-weight'><span>Pil <b>2 kg</b></span><span>Sensör <b>1 kg</b></span><em>Çanta sınırı <b>5 kg</b></em></div>;if(item.id==='FL1')return <div className='av-transform'><span><small>KÜÇÜK • BOŞ</small>○</span><b>→</b><span><small>BÜYÜK • DOLU</small>●</span><em>aynı dönüşümü üçgene taşı</em></div>;return null};
const choiceView=(c:Choice)=>{if(item.id==='ME1')return <span className='av-seq mini'>{seqs[c.id].map((x,i)=><Token key={i} kind={x}/>)}</span>;if(item.id==='ME2')return <Board variant={c.id}/>;if(item.id==='SP1')return <Block cells={rot[c.id]}/>;if(item.id==='SP2')return <Board variant={c.id}/>;return <strong>{c.label}</strong>};
if(breakMode)return <div className='av-shell'><header className='av-top'><div><b>CZA</b><span>Çelik Zihin Akademisi</span></div><em>Son Doğrulama & Transfer Turu</em></header><main className='av-main'><section className='av-break'><div><Sparkles/></div><h1>İlk doğrulama turu tamam.</h1><p>Şimdi aynı düşünme gücünü farklı bir yüzeyde yeniden kullanacaksın. Eski cevabı değil, yeni durumu çöz.</p><span>3 görev tamamlandı · 3 görev kaldı</span><button type='button' onClick={resume}>Son tura geç <b>→</b></button></section></main></div>;
return <div className='av-shell'><header className='av-top'><div><b>CZA</b><span>Çelik Zihin Akademisi</span></div><em>Son Doğrulama & Transfer Turu</em></header><main className='av-main'>{err&&<div className='av-error'>{err}</div>}<section className='av-card'><div className='av-progress'><strong>{idx+1}<small>/6</small></strong><div><i style={{width:((idx+1)/6*100)+'%'}}/></div><span>{labels[item.domain]}</span></div><div className='av-head'><div><span>CZA HEDEFLİ TRANSFER</span><h1>{item.title}</h1><p>{item.prompt}</p></div><div>{domainIcon(item.domain)}</div></div><div className='av-stage'>{item.memory&&phase!=='answer'?<div className={'av-memory '+phase}>{phase==='study'?<>{visual()}<strong>4 saniye incele.</strong><small>Cevap seçenekleri görüntü kapanmadan açılmaz.</small></>:<><Eye/><strong>Görüntü kapandı.</strong><small>Bir an zihninde tut…</small></>}</div>:<>{visual()}<div className={'av-options '+(item.id==='ME1'||item.id==='ME2'||item.id==='SP1'||item.id==='SP2'?'visual':'')}>{choices.map(c=><button type='button' key={c.id} className={selected===c.id?'selected':''} aria-pressed={selected===c.id} onClick={()=>choose(c.id)}>{choiceView(c)}{selected===c.id&&<b className='av-check'>✓</b>}</button>)}</div></>}</div><div className='av-bottom'><div><ShieldCheck/><span><strong>Bu tur tekrar soru çözmek için değil, transferi doğrulamak için.</strong><small>Sistem önceki kanıt yeterliyse gereksiz tekrar açmaz; doğrudan başlatılan testte altı alandan dengeli birer örnek kullanır. Doğru/yanlış öğrenciye gösterilmez.</small></span></div><div style={{display:'flex',gap:9,flexWrap:'wrap',justifyContent:'flex-end'}}><button type='button' className='cza-btn cza-soft' disabled={busy} onClick={()=>next(true)}>Bu soruyu geç</button><button className='av-next' disabled={!selected||busy||phase!=='answer'} onClick={()=>next(false)}>{busy?'Kaydediliyor…':idx===5?'Doğrulama Turunu Tamamla':'Sonraki Görev'} <span>→</span></button></div></div><footer className='av-footer'><span>{studentLabel||'Öğrenci'} · 6 hedefli görev</span><span>kanıt doğrulama • yeni duruma transfer • fikir değişimi</span></footer></section></main></div>;
}
