import { useEffect, useMemo, useState } from 'react';
import { api } from '@appdeploy/client';
import { ArrowLeft, Brain, CheckCircle2, Download, FileText, Home, Printer, ShieldCheck, Sparkles, Target, TrendingUp } from 'lucide-react';
import { downloadParentReportPdf } from './parentReportPdf';
import './parent-report-extra.css';

type Status='strong'|'developing'|'support'|'profile'|'pending';
type Area={id:number;icon:string;title:string;mode:'performance'|'profile';status:Status;statusLabel:string;score:number|null;evidenceCount:number;summary:string;evidence:string[];nextStep:string;educatorObservation?:string;educatorObservationStructured?:Record<string,string>;educatorObservationUpdatedAt?:string;holisticAssessment?:string};
type Report={studentLabel:string;status:string;attemptCount:number;coverage:{completed:number;total:number};learningResponse:{label:string};areas:Area[];strengths:string[];developing:string[];needsSupport:string[];strategy:string[];summary:string[];recommendations:string[];disclaimer:string};
type Guide={focus:string;methods:string[];target:string;home:string};

const guides:Record<number,Guide>={
1:{focus:'Bu alan, çocuğun bilgiyi doğru tutarken ne kadar akıcı ve dengeli işlediğini gösterir.',methods:['Paritmetik parmak çalışmaları','Soroban doğruluk-ritim çalışmaları','Flash Anzan ve süre kontrollü zihinsel işlem'],target:'Aynı doğruluğu korurken görev süresinin kısalması ve acele hatalarının artmaması.',home:'Kısa süreli zihinden işlem oyunları yapın; hız için doğruluktan vazgeçmesini istemeyin.'},
2:{focus:'Bu alan yalnız işlemin sonucunu değil, sayı ilişkisini anlayıp uygun çözüm yolu kurmayı gösterir.',methods:['Sayı temsilleri ve soroban','CZA çok yollu işlem soruları','Kural keşfi ve yeni probleme transfer'],target:'Yeni tip soruda stratejiyi bağımsız kurması ve gerektiğinde farklı çözüm yoluna geçebilmesi.',home:'“Cevap kaç?”tan önce “Nasıl düşündün, başka yol var mı?” diye sorun.'},
3:{focus:'Bu alan şekil, konum, yön ve görsel bilgiyi zihinde tutup dönüştürme becerisini izler.',methods:['Görsel hafıza kodlama','Uzamsal döndürme ve yol bulma','Soroban zihinsel imgeleme'],target:'Yeni görsel-uzamsal görevde daha az deneme ile doğru strateji kurması ve transfer göstermesi.',home:'Kısa yapboz, yön bulma ve “gözünü kapat, nerede olduğunu hatırla” oyunları kullanın.'},
4:{focus:'Bu alan dinlediğini seçme, akılda tutma ve sözlü yönergeyi sırayla uygulama becerisini gösterir.',methods:['Kulak Radarı işitsel diziler','Sesli Anzan','Çok adımlı sözlü yönerge çalışmaları'],target:'Tekrar ihtiyacının azalması ve 2–3 adımlı yönergeyi doğru sırayla uygulaması.',home:'Tek seferde kısa iki adımlı yönergeler verin; hemen tekrar etmek yerine önce hatırlamasına fırsat tanıyın.'},
5:{focus:'Bu alan matematiğe yaklaşım, zor görev karşısındaki güven, yardım kullanımı ve sebat örüntüsünü gösterir.',methods:['Kademeli başarı deneyimi','Seçim hakkı ve destek azaltma','Matematik özgüveni ve kalibrasyon görevleri'],target:'Zor göreve yaklaşma isteğinin, uygun yardım istemenin ve gerçek performansla güven düzeyinin daha uyumlu hale gelmesi.',home:'“Sen matematikte iyisin/kötüsün” yerine “Bu soruda hangi yol işine yaradı?” dilini kullanın.'},
6:{focus:'Bu alan okuma doğruluğu, akıcılık, anlama ve çıkarımı birlikte ele alır.',methods:['Okuma doğruluğu ve akıcılık temeli','Kelime gruplama ve göz ritmi','Anlamayı koruyarak uygun düzeyde hızlı okuma'],target:'Doğruluk ve anlama korunurken daha akıcı ve bağımsız okuma.',home:'Kısa metinleri tekrar tekrar hız yarışı yaptırmak yerine okuduktan sonra bir cümleyle ne anladığını sorun.'},
7:{focus:'Bu alan bilgiyi kısa süreli tutma, anlamlı biçimde kodlama ve daha sonra geri çağırma becerisini izler.',methods:['Görsel kodlama ve çağrışım','Hikâyeleştirme ve aktif hatırlama','Zihin haritası + 37 komutluk Tam Öğrenme sistemi'],target:'Daha az tekrar ile hatırlama ve gecikmeli hatırlamada kalıcılığın artması.',home:'Ezberletmek yerine bilgiyi resim, hikâye veya komik bir çağrışımla bağlamasını isteyin.'},
8:{focus:'Bu alan bilgiyi gruplama, sıralama, planlama ve düzenli bir yapıya dönüştürme becerisini gösterir.',methods:['Zihin haritası','Bilgiyi gruplama ve sıralama','Etkili not alma + planlama rutinleri'],target:'Bilgiyi kendi başına gruplaması, sıralaması ve çalışma planına dönüştürmesi.',home:'Bir işi sözel olarak uzun anlatmak yerine “önce–sonra–bitti” şeklinde üç küçük kutuya ayırın.'},
9:{focus:'Bu alan hedefe odaklanma, dikkat dağıtıcıyı eleme, kural değişince yeniden toparlanma ve dürtüyü kontrol etmeyi izler.',methods:['Derin Odak çalışmaları','Dikkat Avı / Stroop tipi görevler','Kural değiştirme ve engelleyici kontrol'],target:'Hedefi daha uzun sürdürmesi, kural değişiminde daha hızlı toparlanması ve acele hatalarının azalması.',home:'Kısa odak blokları kullanın; “dikkatini ver” demek yerine tek hedef söyleyin ve süreyi görünür tutun.'},
10:{focus:'Bu alan problemi anlamak, plan kurmak, gerekçe üretmek ve işe yaramayan yolu değiştirmekle ilgilidir.',methods:['CZA bilişsel yoğunluklu sorular','Birden fazla çözüm yolu','Eksik bilgi, kural keşfi ve transfer'],target:'Yeni soruda plan kurması, gerekçe sunması ve işe yaramayan stratejiyi değiştirebilmesi.',home:'Hemen cevabı vermeyin; “Şu an ne biliyoruz, ne eksik, ilk neyi denersin?” diye sorun.'},
11:{focus:'Bu alan duygusal ipuçlarını fark etme, bağlamı kullanma ve farklı bakış açılarını değerlendirmeyi izler.',methods:['Duygu ipucu okuma','Bakış açısı değiştirme','Duygu düzenleme ve neden-gerekçe konuşmaları'],target:'Duyguyu yalnız yüzden değil bağlamdan çıkarabilmesi ve birden fazla olasılığı gerekçelendirebilmesi.',home:'Günlük bir olayda “Sence o neden böyle hissetmiş olabilir, başka ne hissedebilirdi?” diye sorun.'},
12:{focus:'Bu alan hedef koyma, ilk adımı seçme, ilerlemeyi izleme ve gerektiğinde planı değiştirme becerisini gösterir.',methods:['Kısa hedef koyma','Öz izleme ve üstbiliş','Planla–Uygula–Kontrol Et–Güncelle koçluk döngüsü'],target:'Hedefi netleştirmesi, ilk adımı seçmesi, ilerlemeyi kontrol edip gerektiğinde planı değiştirmesi.',home:'“Ödevini yap” yerine “İlk küçük adımın ne?” diye sorup sonunda kendi kontrolünü yapmasını isteyin.'},
13:{focus:'Bu alan günlük yaşamda adalet, sorumluluk, empati, izin, onarma ve niyet-sonuç ilişkisini nasıl düşündüğünü anlamaya yöneliktir.',methods:['Günlük yaşam değer senaryoları','Neden? gerekçelendirme','Sorumluluk, onarma ve empati çalışmaları'],target:'Farklı günlük durumlarda seçim-gerekçe tutarlılığının ve onarma davranışının daha görünür hale gelmesi.',home:'Doğru cevabı söylemeden “Sen olsan ne yapardın ve neden?” diye konuşun.'},
14:{focus:'Bu alan şükür, sabır, saygı, dua, niyet ve emanet gibi değerleri gündelik yaşamla ilişkilendirme biçimini gözlemler.',methods:['Şükür-sabır-saygı farkındalığı','Günlük değer hikâyeleri','Niyet ve davranış üzerine kısa düşünme görevleri'],target:'Değer kavramlarını gündelik duruma bağlaması ve kendi gerekçesini ifade edebilmesi.',home:'Gün sonunda kısa bir “Bugün neye şükrettik, nerede sabrettik?” sohbeti yapın; puanlama veya kıyaslama yapmayın.'}
};

const whyByArea:Record<number,string>={
1:'Çünkü hedef yalnız daha hızlı cevap vermek değil; doğruluğu koruyarak zihinsel işlem yükünü azaltmak ve otomatikliği güvenli biçimde artırmaktır.',
2:'Çünkü sayı ilişkisini anlayan çocuk yalnız ezberlediği işlemi değil, yeni bir problemi de farklı yollarla çözebilir.',
3:'Çünkü görsel-uzamsal temsil güçlendikçe çocuk hem zihinsel imgelemede hem soroban ve problem çözme görevlerinde daha az deneme-yanılmaya ihtiyaç duyar.',
4:'Çünkü sözlü bilgiyi seçme ve sırayla taşıma güçlendikçe uzun yönergeler çocuğun zihinsel kapasitesini gereksiz yere tüketmez.',
5:'Çünkü güveni yalnız övgüyle değil; başarılabilir görev, doğru yardım kullanımı ve gerçek performansla uyumlu öz değerlendirme ile geliştirmek isteriz.',
6:'Çünkü hız, doğruluk ve anlama birlikte ilerlemediğinde hızlı okuma tek başına gerçek bir kazanım değildir.',
7:'Çünkü kalıcı öğrenmede tekrar sayısından çok bilginin nasıl kodlandığı, geri çağrıldığı ve yeni bilgiyle bağlandığı önemlidir.',
8:'Çünkü bilgiyi düzenleyebilen çocuk çalışma yükünü parçalara ayırır, neyi ne zaman yapacağını daha bağımsız yönetir.',
9:'Çünkü dikkat “dikkatini ver” komutuyla değil; hedef seçme, dürtüyü tutma, kural değiştirme ve odağı geri getirme becerileriyle gelişir.',
10:'Çünkü CZA’nın amacı yalnız doğru cevabı buldurmak değil; plan kuran, gerekçe üreten ve işe yaramayan yolu değiştirebilen bir düşünme sistemi geliştirmektir.',
11:'Çünkü duygusal farkındalık yalnız yüz ifadesi tanımak değil; bağlamı, beden ipuçlarını ve farklı bakış açılarını birlikte değerlendirebilmektir.',
12:'Çünkü çocuk kendi hedefini, ilk adımını ve kontrol yöntemini öğrendiğinde dış yönlendirmeye olan bağımlılığı azalır.',
13:'Çünkü değer gelişiminde amaç hazır cevabı ezberletmek değil; günlük durumda nedenini düşünebilen ve onarma-sorumluluk bağlantısını kurabilen muhakemedir.',
14:'Çünkü manevi ve değer farkındalığı puanlanacak bir üstünlük değil; gündelik yaşama bağlanan anlam, niyet ve fark etme sürecidir.'
};

const statusOrder:Record<Status,number>={support:0,developing:1,strong:2,profile:3,pending:4};
function plainStatus(a:Area,name:string){if(a.status==='strong')return `${name}, şu ana kadarki görevlerde bu alanda daha bağımsız ve tutarlı ilerledi. Bu güçlü görünen beceriyi daha zor ve yeni durumlara taşımayı hedefleyeceğiz.`;if(a.status==='developing')return `${name} bu beceriyi kullanabiliyor; ancak görev zorlaştığında veya koşul değiştiğinde daha fazla düşünme ya da yapılandırma ihtiyacı görülebiliyor. Hedefimiz beceriyi daha tutarlı ve bağımsız hale getirmek.`;if(a.status==='support')return `${name} bu alandaki bazı görevlerde zorlanma sinyali verdi. Bu “yapamıyor” demek değildir; hangi destek biçimiyle daha iyi performans gösterdiğini bulup desteği adım adım azaltacağız.`;if(a.status==='profile')return `Bu alanda ${name} için yüksek-düşük puanı vermiyoruz. Seçimlerini, gerekçelerini ve günlük durumlara verdiği tepkileri anlamaya çalışıyoruz.`;return `Bu alanda henüz güvenilir yorum yapmaya yetecek görev kanıtı oluşmadı. Şimdilik güçlü-zayıf etiketi koymuyoruz.`}
function meaning(a:Area){if(a.status==='strong')return 'Bu alan şu an bir geliştirme açığından çok, ileri düzey görevlerle zenginleştirilecek bir güç alanı gibi görünüyor.';if(a.status==='developing')return 'Beceri mevcut; daha kararlı, hızlı veya bağımsız kullanılabilmesi için düzenli ve kademeli çalışma yararlı olacaktır.';if(a.status==='support')return 'Bu sonuç kapasite sınırı değildir. CZA için asıl soru, hangi yöntem ve destek sonrasında performansın toparlandığıdır.';if(a.status==='profile')return 'Burada amaç çocuğu etiketlemek değil, düşünme ve değer gerekçelerini daha iyi tanımaktır.';return 'Kanıt oluşmadan eğitim planında bu alanı zayıflık olarak değerlendirmeyeceğiz.'}
function methodLead(a:Area){if(a.status==='strong')return 'Tekrar yaptırmak yerine beceriyi zorlaştırılmış görev, hız-esneklik ve transfer ile ileri taşıyacağız.';if(a.status==='developing')return 'Kademeli destek → bağımsız uygulama → yeni duruma transfer sırasını kullanacağız.';if(a.status==='support')return 'Önce bilişsel yükü azaltıp doğru stratejiyi kuracağız; sonra yardımı kademeli azaltıp yeniden ölçeceğiz.';if(a.status==='profile')return 'Puan vermeden, günlük senaryo, gerekçe ve öz değerlendirme üzerinden farkındalığı zenginleştireceğiz.';return 'Önce kısa hedef görevlerle yeterli kanıt toplayacağız; kanıt oluşmadan çalışma etiketi koymayacağız.'}
function phaseOne(a:Area){if(a.status==='support')return 'Temeli kur: Görevi sadeleştir, doğru stratejiyi somut/görsel destekle kur ve ilk başarıyı güvenli biçimde oluştur.';if(a.status==='developing')return 'Temeli netleştir: Mevcut stratejiyi görünür hale getir, gereksiz yükü azalt ve doğru yolu tutarlılaştır.';return 'Seviyeyi yükselt: Güçlü beceriyi daha zor, daha değişken ve daha az tahmin edilebilir görevle çalıştır.'}
function phaseTwo(g:Guide){return `Akıcılığı artır: ${g.methods.slice(0,2).join(' + ')} ile kısa ve düzenli uygulama yap; ipucu ve dış desteği kademeli azalt.`}
function phaseThree(){return 'Transfer et ve yeniden ölç: Benzer olmayan yeni görevde becerinin kendiliğinden kullanılıp kullanılmadığını kontrol et; sonuca göre rotayı güncelle.'}
function evidenceStage(done:number,total:number){const p=total?done/total:0;if(p>=.8)return 'Geniş kanıt kapsamı';if(p>=.45)return 'Gelişen kanıt kapsamı';return 'İlk kanıt kapsamı'}const observationLabels:Record<string,string>={'strategy:modeled':'Strateji: modelleme ile','strategy:prompted':'Strateji: ipucuyla','strategy:independent':'Strateji: bağımsız','strategy:flexible':'Strateji: esnek / değiştirebildi','independence:full_support':'Bağımsızlık: yoğun destekle','independence:partial_support':'Bağımsızlık: kısmi destekle','independence:mostly_independent':'Bağımsızlık: çoğunlukla bağımsız','independence:independent':'Bağımsızlık: bağımsız','supportUse:not_needed':'Yardım: desteğe gerek duymadı','supportUse:accepted':'Yardım: desteği kabul etti','supportUse:used_effectively':'Yardım: desteği etkili kullandı','supportUse:limited_response':'Yardım: desteğe sınırlı yanıt','selfCorrection:not_seen':'Öz düzeltme: gözlenmedi','selfCorrection:prompted':'Öz düzeltme: hatırlatmayla','selfCorrection:spontaneous':'Öz düzeltme: kendiliğinden','perseverance:stopped_quickly':'Sebat: çabuk bıraktı','perseverance:with_prompt':'Sebat: teşvikle sürdürdü','perseverance:sustained':'Sebat: sürdürdü','attention:frequent_redirect':'Dikkat: sık yönlendirme gerekti','attention:occasional_redirect':'Dikkat: ara sıra yönlendirme','attention:sustained':'Dikkat: odağı sürdürebildi','transfer:not_tested':'Transfer: henüz denenmedi','transfer:with_support':'Transfer: destekle','transfer:partial':'Transfer: kısmi','transfer:independent':'Transfer: bağımsız'};function observationLines(a:Area){return Object.entries(a.educatorObservationStructured||{}).map(([k,v])=>v&&v!=='not_observed'?observationLabels[k+':'+v]||null:null).filter((x):x is string=>Boolean(x))}

export async function downloadCurrentParentReportPdf(report:Report){const priorities=[...report.areas].filter(a=>a.mode==='performance'&&a.evidenceCount>0&&a.status!=='pending').sort((a,b)=>statusOrder[a.status]-statusOrder[b.status]||(a.score??999)-(b.score??999)).slice(0,3);const teacherNotes=report.areas.filter(a=>Boolean(a.educatorObservation?.trim()||observationLines(a).length));await downloadParentReportPdf({student:report.studentLabel,isFinal:report.status==='completed',coverage:report.coverage.completed+'/'+report.coverage.total,coverageLabel:evidenceStage(report.coverage.completed,report.coverage.total),attemptCount:report.attemptCount,learningResponse:report.learningResponse.label,summary:report.summary,strengths:report.strengths,developing:report.developing,priorities:priorities.map(a=>a.title),strategy:report.strategy,teacherNotes:teacherNotes.map(a=>({title:a.title,note:[...observationLines(a),a.educatorObservation||''].filter(Boolean).join(' · ')})),areas:report.areas.map(a=>{const g=guides[a.id];return{id:a.id,title:a.title,status:a.statusLabel,academic:a.evidenceCount>0?(a.summary||'Bu alanda değerlendirme kanıtı oluştu; yorum yeni görevlerle güçlenecektir.'):'Bu alanda güvenilir akademik yorum için henüz yeterli değerlendirme kanıtı oluşmadı.',family:g.focus+' '+plainStatus(a,report.studentLabel),daily:meaning(a),teacher:a.educatorObservation,teacherStructured:observationLines(a),holistic:a.holisticAssessment||'Kanıt kaynakları biriktikçe bütüncül değerlendirme güncellenecektir.',nextStep:a.evidenceCount>0?a.nextStep:'Önce bu alanı kısa ve yaşa uygun görevlerle örnekleyip yeterli kanıt oluşturacağız.',evidence:a.evidence.length?a.evidence.join(' · '):'Kanıt bekleniyor'}}),routes:priorities.map((a,i)=>{const g=guides[a.id];return{order:i+1,title:a.title,status:a.statusLabel,why:a.summary,methods:g.methods,rationale:whyByArea[a.id],target:g.target,home:g.home}}),disclaimer:report.disclaimer})}

export default function ParentReportView({sessionId}:{sessionId:string}){
const[report,setReport]=useState<Report|null>(null);const[err,setErr]=useState('');const[pdfBusy,setPdfBusy]=useState(false);const[pdfStatus,setPdfStatus]=useState('');const[autoStatus,setAutoStatus]=useState('');
useEffect(()=>{if(!sessionId){setErr('Veli raporu için oturum numarası gerekli.');return}let active=true;let initial=true;const load=async(showStatus=false)=>{try{const r=await api.get('/api/session/'+sessionId+'/report');if(!active)return;setReport(r.data as Report);setErr('');if(showStatus)setAutoStatus('Öğretmen gözlemi geldi · Veli raporu güncellendi.')}catch{if(active&&initial)setErr('Veli raporu hazırlanamadı.')}finally{initial=false}};void load();const eventKey='cza-report-updated:'+sessionId;const onStorage=(e:StorageEvent)=>{if(e.key===eventKey)void load(true)};const onFocus=()=>void load();const onVisibility=()=>{if(document.visibilityState==='visible')void load()};window.addEventListener('storage',onStorage);window.addEventListener('focus',onFocus);document.addEventListener('visibilitychange',onVisibility);const timer=window.setInterval(()=>void load(),15000);return()=>{active=false;window.removeEventListener('storage',onStorage);window.removeEventListener('focus',onFocus);document.removeEventListener('visibilitychange',onVisibility);window.clearInterval(timer)}},[sessionId]);useEffect(()=>{if(!autoStatus)return;const t=window.setTimeout(()=>setAutoStatus(''),4000);return()=>window.clearTimeout(t)},[autoStatus]);
const priorities=useMemo(()=>report?[...report.areas].filter(a=>a.mode==='performance'&&a.evidenceCount>0&&a.status!=='pending').sort((a,b)=>statusOrder[a.status]-statusOrder[b.status]||(a.score??999)-(b.score??999)).slice(0,3):[],[report]);
const profileHighlights=useMemo(()=>report?report.areas.filter(a=>a.mode==='profile'&&a.evidenceCount>0).slice(0,3):[],[report]);
const teacherNotes=useMemo(()=>report?report.areas.filter(a=>Boolean(a.educatorObservation?.trim()||observationLines(a).length)):[],[report]);
async function downloadPdf(){if(!report||pdfBusy)return;setPdfBusy(true);setPdfStatus('');try{await downloadCurrentParentReportPdf(report);setPdfStatus('PDF kaydetme ekranı açıldı. Hedef olarak “PDF olarak kaydet” seçin.')}catch{setPdfStatus('PDF oluşturulamadı. Lütfen tekrar deneyin.')}finally{setPdfBusy(false)}}
if(err)return <div className='pr-shell'><div className='pr-error'>{err}</div></div>;if(!report)return <div className='pr-shell'><div className='pr-loading'>CZA veli raporu hazırlanıyor…</div></div>;
const isFinal=report.status==='completed';const coveragePct=Math.round((report.coverage.completed/Math.max(1,report.coverage.total))*100);const stage=evidenceStage(report.coverage.completed,report.coverage.total);
return <div className='pr-shell'><header className='pr-top no-print'><a href={'#/report?session='+sessionId}><ArrowLeft/> Eğitmen raporu</a><div className='pr-brand'><b>CZA</b><span>Veli Bilgilendirme Raporu</span></div><div className='pr-tools'><button className='pr-pdf-btn' onClick={()=>void downloadPdf()} disabled={pdfBusy}><Download/> {pdfBusy?'Açılıyor…':'PDF Olarak Kaydet'}</button><button onClick={()=>window.print()}><Printer/> Yazdır</button></div></header>{autoStatus&&<div className='pr-auto-status no-print'><CheckCircle2/>{autoStatus}</div>}{pdfStatus&&<div className={'pr-pdf-status no-print '+(pdfStatus.startsWith('PDF oluşturulamadı')?'error':'ok')}>{pdfStatus}</div>}<main className='pr-main'>
<section className='pr-cover'><div><div className={'pr-state '+(isFinal?'final':'draft')}>{isFinal?'FINAL DEĞERLENDİRME RAPORU':'ARA RAPOR · DEĞERLENDİRME DEVAM EDİYOR'}</div><span>CZA · BÜTÜNCÜL ÖĞRENME VE GELİŞİM PROFİLİ</span><h1>{report.studentLabel}</h1><p>Bu rapor yalnız “kaç doğru yaptı?” sorusuna değil; <strong>nasıl düşündü, hangi desteğe cevap verdi ve hangi CZA yöntemiyle daha ileri taşınabilir?</strong> sorularına cevap vermek için hazırlanmıştır.</p><div className='pr-metrics'><b><CheckCircle2/> {report.coverage.completed}/{report.coverage.total} alan kanıtı</b><b><FileText/> {report.attemptCount} görev kaydı</b><b><Brain/> {report.learningResponse.label}</b></div><div className='pr-evidence-scope'><div><b>Kanıt kapsamı</b><span>{stage}</span></div><i><em style={{width:coveragePct+'%'}}/></i><small>%{coveragePct} başarı puanı değildir; 14 ana alanın kaçında yorumlanabilir kanıt oluştuğunu gösterir.</small></div></div><div className='pr-cover-mark'><Brain/><b>CZA</b><span>ÖLÇ → ANLA → YÖNTEMİ SEÇ → ÇALIŞTIR → TEKRAR ÖLÇ</span></div></section>
{!isFinal&&<section className='pr-draft-note'><ShieldCheck/><div><b>Önemli: Bu bir ara rapordur.</b><p>Değerlendirme akışı henüz tamamlanmadığı için aşağıdaki yorumlar yalnız şu ana kadar oluşan kanıta dayanır. Kanıt bekleyen alanlar zayıflık sayılmaz; final rota yeni görevler geldikçe değişebilir.</p></div></section>}
<section className='pr-principle'><ShieldCheck/><div><b>Bu raporu nasıl okuyalım?</b><p>“Gelişiyor” veya “destekle izleyelim” ifadeleri çocuğun kapasitesini etiketlemez. CZA, zorlanmanın nedenini ayırmaya ve doğru yöntem uygulandığında performansın nasıl değiştiğini izlemeye çalışır.</p></div></section>
<section className='pr-summary'><div className='pr-summary-copy'><span>AİLE İÇİN HIZLI ÖZET</span><h2>Şu ana kadarki kanıt bize ne söylüyor?</h2>{report.summary.map((x,i)=><p key={i}>{x}</p>)}</div><div className='pr-summary-grid'><article><span>🌟</span><b>Öne çıkan güçlü yönler</b><p>{report.strengths.length?report.strengths.join(' · '):'Güçlü alan yorumu için kanıt birikiyor.'}</p></article><article><span>🌱</span><b>Gelişmekte olan alanlar</b><p>{report.developing.length?report.developing.join(' · '):'Şu an belirgin gelişen alan etiketi yok.'}</p></article><article><span>🎯</span><b>İlk çalışma öncelikleri</b><p>{priorities.length?priorities.map(a=>a.title).join(' · '):'Yeterli performans kanıtı oluşunca rota netleşecek.'}</p></article></div></section>
{priorities.length>0&&<section className='pr-decision'><div className='pr-decision-head'><Target/><div><span>BUGÜN İÇİN CZA EĞİTİM KARARI</span><h2>Önce neye dokunacağız?</h2><p>Bu sıralama “en zayıf alan” listesi değildir. Mevcut kanıta göre çocuğun gelişimini en çok ileri taşıyabilecek ilk çalışma kapılarını gösterir.</p></div></div><div className='pr-decision-grid'>{priorities.map((a,i)=>{const g=guides[a.id];return <article key={a.id}><b>{i+1}</b><span>{a.icon}</span><div><small>{a.statusLabel}</small><h3>{a.title}</h3><p>{g.methods[0]}</p></div></article>})}</div></section>}
<section className='pr-learning'><div><span>ÇOCUĞUM NASIL ÖĞRENİYOR?</span><h2>Cevaptan çok öğrenme davranışına bakıyoruz.</h2><p>{report.strategy.length?`Gözlenen strateji ve davranışlar: ${report.strategy.join(' · ')}.`:'Eğitmen gözlemleri ve yeni görevler eklendikçe çocuğun öğrenme davranışı burada daha ayrıntılı görünecek.'}</p></div><div className='pr-learning-rule'><Sparkles/><p>Bir çocuk bazen konuyu bildiği halde yavaşlık, dikkat yükü, çalışma belleği, sembol erişimi veya yanlış strateji nedeniyle zorlanabilir. CZA yöntem seçimini bu ayrımlara göre yapar.</p></div></section>
{teacherNotes.length>0&&<section className='pr-teacher-synthesis'><div><Sparkles/><div><span>ÖĞRETMEN GÖZLEMİYLE BÜTÜNCÜL OKUMA</span><h2>Dijital görev kanıtı + canlı gözlem birlikte</h2><p>Öğretmen gözlemleri dijital görev sonucunu değiştiren bir “ek puan” değildir. Çocuğun strateji, bağımsızlık, destekten yararlanma, öz-düzeltme ve süreç davranışını açıklayan ikinci kanıt kaynağıdır.</p></div></div><div className='pr-teacher-note-grid'>{teacherNotes.slice(0,4).map(a=><article key={a.id}><b>{a.title}</b><p>{[...observationLines(a),a.educatorObservation||''].filter(Boolean).join(' · ')}</p></article>)}</div>{teacherNotes.length>4&&<small>Diğer öğretmen gözlemleri ilgili gelişim alanlarının altında ayrıca yer almaktadır.</small>}</section>}
<section className='pr-head'><span>14 ANA GELİŞİM ALANI</span><h2>Kanıt, akademik yorum ve günlük yaşamdaki karşılığı aynı kartta</h2><p>Her kartta sistemden gelen kanıt, akademik değerlendirme, günlük yaşamdaki karşılığı, eğitmen gözlemi ve bu iki kaynağın birlikte okunduğu bütüncül değerlendirme birbirinden görünür biçimde ayrılır.</p></section>
<section className='pr-area-grid'>{report.areas.map(a=>{const g=guides[a.id];return <article className={'pr-area '+a.status} key={a.id}><div className='pr-area-title'><span>{a.icon}</span><div><small>{String(a.id).padStart(2,'0')} · ANA ALAN</small><h3>{a.title}</h3></div><b>{a.statusLabel}</b></div><div className='pr-system-evidence'><span>SİSTEMDEN GELEN KANIT</span><p>{a.evidence.length?a.evidence.join(' · '):'Kanıt bekleniyor.'}</p><small>{a.evidenceCount} mikro-görev / davranış kanıtı</small></div><div className='pr-academic'><span>AKADEMİK DEĞERLENDİRME</span><p>{a.evidenceCount>0?(a.summary||'Bu alanda gözlem kanıtı oluştu; ayrıntılı yorum yeni görevlerle güçlenecektir.'):'Bu alanda güvenilir akademik yorum için henüz yeterli değerlendirme kanıtı oluşmadı.'}</p></div><div className='pr-plain'><span>GÜNLÜK YAŞAMDAKİ KARŞILIĞI</span><p>{g.focus} {plainStatus(a,report.studentLabel)}</p></div><div className='pr-meaning'><b>Bu bulguyu nasıl yorumlayabiliriz?</b><p>{meaning(a)}</p></div><div className='pr-teacher-observation'><div><Sparkles/><b>Eğitmen gözlemi</b></div>{observationLines(a).length>0&&<div className='pr-observation-chips'>{observationLines(a).map(x=><span key={x}>{x}</span>)}</div>}<p>{a.educatorObservation||'Henüz eğitmen gözlemi eklenmedi.'}</p><small>Bu gözlem sistemden gelen kanıttan ayrı tutulur ve otomatik puanı değiştirmez.</small></div><div className='pr-holistic'><div><Brain/><b>Bütüncül değerlendirme</b></div><p>{a.holisticAssessment||'Kanıt kaynakları biriktikçe bütüncül değerlendirme güncellenecektir.'}</p></div><div className='pr-area-next'><Target/><div><b>CZA sonraki adım</b><p>{a.evidenceCount>0?a.nextStep:'Önce bu alanı kısa ve yaşa uygun görevlerle örnekleyip yeterli kanıt oluşturacağız.'}</p></div></div><div className='pr-area-source'><b>Kanıt kaynağı</b><span>{a.evidenceCount} mikro-görev / davranış kanıtı</span><small>{a.evidence.length?a.evidence.join(' · '):'Kanıt bekleniyor'}</small></div></article>})}</section>
<section className='pr-route'><div className='pr-route-head'><Target/><div><span>CZA BU ÇOCUK İÇİN NE YAPACAK?</span><h2>Kişiselleştirilmiş ilk gelişim rotası</h2><p>Her öğrenciye aynı egzersiz verilmez. Aşağıdaki rota mevcut kanıta göre seçilir; destek azaltma, transfer ve tekrar ölçüm sonucuna göre güncellenir.</p></div></div>{priorities.length?<div className='pr-route-grid'>{priorities.map((a,i)=>{const g=guides[a.id];return <article key={a.id}><div className='pr-route-no'>{i+1}</div><div className='pr-route-title'><span>{a.icon}</span><div><small>{a.statusLabel}</small><h3>{a.title}</h3></div></div><p className='pr-method-lead'>{methodLead(a)}</p><div className='pr-route-why'><b>Neden bu alanı seçtik?</b><p>{a.summary}</p>{a.nextStep&&<small>Mevcut raporun önerdiği sonraki adım: {a.nextStep}</small>}</div><div className='pr-methods'><b>CZA’da kullanacağımız yöntemler</b>{g.methods.map(m=><span key={m}>{m}</span>)}</div><div className='pr-route-rationale'><Sparkles/><div><b>Neden bu teknikler?</b><p>{whyByArea[a.id]}</p></div></div><div className='pr-phases'><b>3 aşamalı çalışma sırası</b><span><i>1</i>{phaseOne(a)}</span><span><i>2</i>{phaseTwo(g)}</span><span><i>3</i>{phaseThree()}</span></div><div className='pr-measure'><TrendingUp/><div><b>Geliştiğini nasıl anlayacağız?</b><p>{g.target}</p></div></div><div className='pr-home'><Home/><div><b>Evde küçük destek</b><p>{g.home}</p></div></div></article>})}</div>:<div className='pr-route-empty'>Kişiselleştirilmiş rota için yeterli performans kanıtı henüz oluşmadı. Önce değerlendirme görevlerini tamamlayıp kanıt toplayacağız.</div>}</section>
{profileHighlights.length>0&&<section className='pr-profile-focus'><div className='pr-profile-head'><Sparkles/><div><span>NİTEL GELİŞİM EŞLİKÇİLERİ</span><h2>Puanlamadığımız ama yakından izlediğimiz alanlar</h2><p>Tutum, karakter ve manevi değerler “yüksek-düşük” puanına çevrilmez. Bu alanlarda seçim, gerekçe, yardım kullanımı ve günlük yaşama taşıma biçimini izleriz.</p></div></div><div className='pr-profile-grid'>{profileHighlights.map(a=>{const g=guides[a.id];return <article key={a.id}><div><span>{a.icon}</span><h3>{a.title}</h3></div><p>{plainStatus(a,report.studentLabel)}</p><b>CZA yaklaşımı</b><small>{g.methods.join(' · ')}</small></article>})}</div></section>}
<section className='pr-cycle'><div><Brain/><div><span>CZA GELİŞİM DÖNGÜSÜ</span><h2>Rapor son nokta değil, başlangıçtır.</h2><p>Ölç → İhtiyacı ayır → Doğru tekniği seç → Kademeli çalıştır → Aynı beceriyi yeni görevde tekrar ölç → Rotayı güncelle.</p></div></div><strong>Hedef; daha az ipucu, daha bağımsız strateji, daha güçlü transfer ve çocuğun kendi öğrenmesini yönetebilmesidir.</strong></section>
<section className='pr-guard'><ShieldCheck/><div><b>CZA yöntem seçme kuralı</b><p>Anzan, Soroban, hızlı okuma, hafıza teknikleri, Derin Odak veya bilişsel yoğunluklu soru çalışmaları çocuğa topluca ve rastgele verilmez. Hangi teknik kullanılacağı, bu rapordaki kanıta ve çocuğun destek sonrası verdiği öğrenme tepkisine göre seçilir.</p></div></section>
<footer className='pr-footer'><b>Çelik Zihin Akademisi · Veli Bilgilendirme Raporu</b><p>{report.disclaimer}</p><p>Bu rapordaki CZA yöntem önerileri eğitimsel gelişim planıdır; klinik tanı veya tedavi önerisi değildir. {isFinal?'Değerlendirme akışı tamamlanmıştır.':'Değerlendirme devam ettiği için sonuçlar yeni kanıtlarla güncellenebilir.'}</p></footer>
</main></div>}
