import { useEffect, useMemo, useRef, useState } from 'react';
import { BrainCircuit, Eye, Grid3X3, Route, RotateCw, ShieldCheck, Sparkles } from 'lucide-react';

type Domain='Görsel-Uzamsal'|'Kural'|'Dikkat'|'Bellek'|'Problem';
type Choice={id:string;label:string};
type Item={id:string;domain:Domain;title:string;prompt:string;correct:string;choices?:Choice[]};
type Row={id:string;domain:Domain;answer:string;score:number;max:number;ms:number;changes:number};

const items:Item[]=[
{id:'V1',domain:'Kural',title:'Gizli düzen',prompt:'Her satır ve sütunda aynı üç kart birer kez bulunuyor. Eksik kart hangisi?',correct:'blue-triangle',choices:[{id:'gold-circle',label:'Altın daire'},{id:'blue-triangle',label:'Mavi üçgen'},{id:'violet-square',label:'Mor kare'},{id:'coral-circle',label:'Mercan daire'}]},
{id:'V2',domain:'Görsel-Uzamsal',title:'Aynadaki iz',prompt:'Kesikli çizgi bir aynadır. Soldaki şeklin gerçek ayna görüntüsünü seç.',correct:'mirror',choices:[{id:'same',label:'A'},{id:'mirror',label:'B'},{id:'turn',label:'C'},{id:'flip',label:'D'}]},
{id:'V3',domain:'Görsel-Uzamsal',title:'Zihninde döndür',prompt:'Kartı 90° saat yönünde döndür. Aynı kart hangi seçenekte oluşur?',correct:'90',choices:[{id:'270',label:'A'},{id:'180',label:'B'},{id:'90',label:'C'},{id:'0',label:'D'}]},
{id:'V4',domain:'Görsel-Uzamsal',title:'Yukarıdan bak',prompt:'Kulelere tam yukarıdan bakarsan hangi taban izi görünür?',correct:'footprint',choices:[{id:'near',label:'A'},{id:'wide',label:'B'},{id:'footprint',label:'C'},{id:'full',label:'D'}]},
{id:'V5',domain:'Problem',title:'Anahtar • kapı • hedef',prompt:'S’den H’ye 6 hamlede git. Önce anahtarı al, sonra mavi kapıdan geç. Siyah bloklara basma.',correct:'route-d',choices:[{id:'route-a',label:'→ → ↓ ↓ → ↓'},{id:'route-b',label:'↓ → ↓ ↓ → →'},{id:'route-c',label:'→ ↓ → ↓ → ↓'},{id:'route-d',label:'↓ → → ↓ ↓ →'}]},
{id:'V6',domain:'Bellek',title:'Konumu aklında tut',prompt:'Kartların yerini 5 saniye incele. Görüntü kapanınca aynı düzeni bul.',correct:'memory-b',choices:[{id:'memory-a',label:'A'},{id:'memory-b',label:'B'},{id:'memory-c',label:'C'},{id:'memory-d',label:'D'}]},
{id:'V7',domain:'Dikkat',title:'Kuralı bozan kart',prompt:'Her satırda ok 90° saat yönünde dönüyor. Kuralı ilk bozan tek karta dokun.',correct:'r3c4'},
{id:'V8',domain:'Kural',title:'İpuçlarıyla ele',prompt:'Üç rozet birbirinden farklı. Bora üçgen taşıyor. Aylin daire taşımıyor. Aylin’in rozeti hangisi?',correct:'square',choices:[{id:'circle',label:'Daire'},{id:'triangle',label:'Üçgen'},{id:'square',label:'Kare'}]},
{id:'V9',domain:'Problem',title:'Parçaları birleştir',prompt:'Hedef deseni boşluk ve fazlalık olmadan hangi iki parça birlikte oluşturur?',correct:'ab',choices:[{id:'ac',label:'A + C'},{id:'bd',label:'B + D'},{id:'ab',label:'A + B'},{id:'ad',label:'A + D'}]},
{id:'V10',domain:'Kural',title:'Şifreli rota transferi',prompt:'Örneklerden ⭐ ve ● kodlarının ne yaptığını keşfet. Son görevde robot hangi köşeye ulaşır?',correct:'top-right',choices:[{id:'top-left',label:'Sol üst'},{id:'top-right',label:'Sağ üst'},{id:'bottom-left',label:'Sol alt'},{id:'bottom-right',label:'Sağ alt'}]}
];

function shuffled(a:Choice[]){const x=[...a];for(let i=x.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[x[i],x[j]]=[x[j],x[i]]}return x}
function Token({kind}:{kind:string}){const [tone,shape]=kind.split('-');return <span className={'gv-token '+tone+' '+shape} aria-hidden='true'/>}
function MiniGrid({cells,tokens}:{cells:number[];tokens?:Record<number,string>}){return <span className='gv-minigrid'>{Array.from({length:9},(_,i)=><i key={i} className={cells.includes(i)?'on':''}>{tokens?.[i]?<Token kind={tokens[i]}/>:null}</i>)}</span>}
function MirrorGlyph({variant}:{variant:'same'|'mirror'|'turn'|'flip'}){const transform=variant==='mirror'?'translate(80 0) scale(-1 1)':variant==='turn'?'rotate(180 40 35)':variant==='flip'?'translate(0 70) scale(1 -1)':undefined;return <svg viewBox='0 0 80 70' aria-hidden='true'><g transform={transform}><path d='M10 10H58V29H31V60H10Z'/><circle cx='21' cy='20' r='5'/></g></svg>}
function RotateGlyph({deg}:{deg:number}){return <svg viewBox='0 0 80 80' aria-hidden='true'><g transform={'rotate('+deg+' 40 40)'}><path d='M14 14H58V31H33V66H14Z'/><circle cx='24' cy='24' r='5'/></g></svg>}
function icon(domain:Domain){return domain==='Görsel-Uzamsal'?<RotateCw/>:domain==='Kural'?<BrainCircuit/>:domain==='Dikkat'?<Eye/>:domain==='Bellek'?<Grid3X3/>:<Route/>}

function MatrixVisual(){const seq=['gold-circle','blue-triangle','violet-square','blue-triangle','violet-square','gold-circle','violet-square','gold-circle',''];return <div className='gv-matrix'>{seq.map((x,i)=><span key={i} className={!x?'missing':''}>{x?<Token kind={x}/>:<b>?</b>}</span>)}</div>}
function MirrorVisual(){return <div className='gv-mirror-stage'><div><small>ASIL</small><MirrorGlyph variant='same'/></div><b className='gv-mirror-line'/><div className='gv-mirror-hint'><span>AYNA</span><small>sol ↔ sağ</small></div></div>}
function RotateVisual(){return <div className='gv-rotate-stage'><div><RotateGlyph deg={0}/></div><span><RotateCw/>90°</span></div>}
function TowerVisual(){const towers:[number,number][]=[[0,2],[2,1],[4,3],[7,1]];return <div className='gv-tower-board'>{Array.from({length:9},(_,i)=>{const h=towers.find(x=>x[0]===i)?.[1]||0;return <span key={i}>{Array.from({length:h},(_,j)=><i key={j}/>)}</span>})}</div>}
function RouteVisual(){return <div className='gv-route-grid'>{Array.from({length:16},(_,i)=>{const label=i===0?'S':i===5?'🔑':i===10?'KAPI':i===15?'H':'';const block=[2,8,11].includes(i);return <span key={i} className={(block?'block ':'')+(i===10?'gate ':'')}>{label}</span>})}</div>}
function MemoryBoard({variant}:{variant:'target'|'memory-a'|'memory-b'|'memory-c'|'memory-d'}){const map:Record<string,Record<number,string>>={target:{0:'gold-star',4:'blue-circle',7:'violet-triangle'},'memory-a':{0:'gold-star',4:'blue-circle',8:'violet-triangle'},'memory-b':{0:'gold-star',4:'blue-circle',7:'violet-triangle'},'memory-c':{0:'blue-circle',4:'gold-star',7:'violet-triangle'},'memory-d':{0:'gold-star',3:'blue-circle',7:'violet-triangle'}};return <MiniGrid cells={Object.keys(map[variant]).map(Number)} tokens={map[variant]}/>} 
function AnomalyGrid({selected,onPick}:{selected:string;onPick:(id:string)=>void}){const rows=[['↑','→','↓','←'],['→','↓','←','↑'],['↓','←','↑','↑']];return <div className='gv-anomaly'>{rows.flatMap((r,ri)=>r.map((a,ci)=>{const id='r'+(ri+1)+'c'+(ci+1);return <button key={id} type='button' className={selected===id?'selected':''} onClick={()=>onPick(id)}>{a}</button>}))}</div>}
function LogicVisual(){return <div className='gv-clues'><div><strong>AYLİN</strong><span>○ değil</span></div><div><strong>BORA</strong><span>△</span></div><div><strong>CEM</strong><span>?</span></div><p>○ △ □ rozetleri birer kez kullanılıyor.</p></div>}
const targetCells=[0,1,4,5,8],pieces:Record<string,number[]>={A:[0,4,8],B:[1,5],C:[0,1,4],D:[5,7]};
function PiecePair({pair}:{pair:string}){const ids=pair.toUpperCase().split('');return <span className='gv-piece-pair'>{ids.map(id=><span key={id}><b>{id}</b><MiniGrid cells={pieces[id]}/></span>)}</span>}
function CodeDemo(){return <div className='gv-code'><div><b>Örnek 1</b><span>↑ + ⭐ ●</span><em>→ sağdaki hücre</em></div><div><b>Örnek 2</b><span>→ + ⭐ ●</span><em>→ alttaki hücre</em></div><div><b>Örnek 3</b><span>↓ + ⭐ ●</span><em>→ soldaki hücre</em></div><section><strong>YENİ</strong><span>Başlangıç: orta hücre, yön ↑</span><b>● ⭐ ●</b></section></div>}

export default function VisualStrategyLab({studentLabel,busy,onFinish,err,onActivity}:{studentLabel?:string;busy:boolean;onFinish:(value:string)=>void;err:string;onActivity:()=>void}){
const[idx,setIdx]=useState(0);const[selected,setSelected]=useState('');const[changes,setChanges]=useState(0);const[records,setRecords]=useState<Row[]>([]);const[breakMode,setBreakMode]=useState(false);const[memoryPhase,setMemoryPhase]=useState<'study'|'retain'|'answer'>('study');const started=useRef(Date.now());const item=items[idx];const choices=useMemo(()=>shuffled(item.choices||[]),[item.id]);
useEffect(()=>{if(item.id!=='V6')return;setSelected('');setMemoryPhase('study');let b=0;const a=window.setTimeout(()=>{setMemoryPhase('retain');b=window.setTimeout(()=>setMemoryPhase('answer'),1100)},5000);return()=>{window.clearTimeout(a);if(b)window.clearTimeout(b)}},[item.id]);
const choose=(id:string)=>{if(busy)return;onActivity();if(selected&&selected!==id)setChanges(v=>v+1);setSelected(id)};
const ready=Boolean(selected)&&(item.id!=='V6'||memoryPhase==='answer');
const encode=(rs:Row[])=>{const stat=(d:Domain)=>{const x=rs.filter(r=>r.domain===d);return x.reduce((s,r)=>s+r.score,0)+'/'+x.reduce((s,r)=>s+r.max,0)};return 'GV|n='+rs.length+'|spatial='+stat('Görsel-Uzamsal')+'|rule='+stat('Kural')+'|attention='+stat('Dikkat')+'|memory='+stat('Bellek')+'|problem='+stat('Problem')+'|r='+rs.map(r=>r.id+'~'+r.answer+'~'+r.score+'~'+r.ms+'~'+r.changes).join(',')};
const next=(skip=false)=>{if((!ready&&!skip)||busy)return;const row:Row={id:item.id,domain:item.domain,answer:skip?'SKIP':selected,score:skip?0:selected===item.correct?1:0,max:skip?0:1,ms:Math.max(0,Date.now()-started.current),changes};const rs=[...records,row];if(idx===items.length-1){onFinish(encode(rs));return}setRecords(rs);if(idx===4){setBreakMode(true);return}setIdx(v=>v+1);setSelected('');setChanges(0);started.current=Date.now()};
const resume=()=>{setBreakMode(false);setIdx(5);setSelected('');setChanges(0);started.current=Date.now()};
const renderVisual=()=>item.id==='V1'?<MatrixVisual/>:item.id==='V2'?<MirrorVisual/>:item.id==='V3'?<RotateVisual/>:item.id==='V4'?<TowerVisual/>:item.id==='V5'?<RouteVisual/>:item.id==='V6'?(memoryPhase==='study'?<div className='gv-memory-study'><MemoryBoard variant='target'/><strong>5 saniye bak • yerleri aklında tut</strong></div>:memoryPhase==='retain'?<div className='gv-memory-blank'><Eye/><strong>Görüntü kapandı.</strong><small>Bir an zihninde tut…</small></div>:null):item.id==='V8'?<LogicVisual/>:item.id==='V9'?<div className='gv-target'><span>HEDEF</span><MiniGrid cells={targetCells}/></div>:item.id==='V10'?<CodeDemo/>:null;
const renderChoice=(c:Choice)=>{if(item.id==='V1')return <><Token kind={c.id}/><small>{c.label}</small></>;if(item.id==='V2')return <><MirrorGlyph variant={c.id as 'same'|'mirror'|'turn'|'flip'}/><small>{c.label}</small></>;if(item.id==='V3')return <><RotateGlyph deg={Number(c.id)}/><small>{c.label}</small></>;if(item.id==='V4'){const maps:Record<string,number[]>={near:[0,2,4,8],wide:[0,1,2,4,7],footprint:[0,2,4,7],full:[0,2,3,4,7]};return <><MiniGrid cells={maps[c.id]}/><small>{c.label}</small></>}if(item.id==='V6')return <><MemoryBoard variant={c.id as 'memory-a'|'memory-b'|'memory-c'|'memory-d'}/><small>{c.label}</small></>;if(item.id==='V8')return <><span className={'gv-badge-shape '+c.id}/><small>{c.label}</small></>;if(item.id==='V9')return <PiecePair pair={c.id}/>;if(item.id==='V10'){const pos:Record<string,string>={'top-left':'↖','top-right':'↗','bottom-left':'↙','bottom-right':'↘'};return <><b className='gv-corner'>{pos[c.id]}</b><small>{c.label}</small></>}return <strong>{c.label}</strong>};
if(breakMode)return <div className='gv-shell'><header className='gv-top'><div><b>CZA</b><span>Çelik Zihin Akademisi</span></div><em>Görsel Strateji & Mantık Laboratuvarı</em></header><main className='gv-main'><section className='gv-break'><div><Sparkles/></div><h1>İlk görsel keşif tamam.</h1><p>Şimdi gözünü değil, görüntüyü zihninde tutma ve ipuçlarını birleştirme gücünü daha fazla kullanacaksın.</p><span>5 görev tamamlandı · 5 görev kaldı</span><button onClick={resume}>İkinci tura geç <b>→</b></button></section></main></div>;
return <div className='gv-shell'><header className='gv-top'><div><b>CZA</b><span>Çelik Zihin Akademisi</span></div><em>Görsel Strateji & Mantık Laboratuvarı</em></header><main className='gv-main'>{err&&<div className='gv-error'>{err}</div>}<section className='gv-card'><div className='gv-progress'><strong>{idx+1}<small>/10</small></strong><div><i style={{width:((idx+1)/10*100)+'%'}}/></div><span>{item.domain}</span></div><div className='gv-head'><div><span>CZA GÖRSEL AKIL YÜRÜTME</span><h1>{item.title}</h1><p>{item.prompt}</p></div><div>{icon(item.domain)}</div></div><div className='gv-stage'>{renderVisual()}{item.id==='V7'?<AnomalyGrid selected={selected} onPick={choose}/>:item.id==='V6'&&memoryPhase!=='answer'?null:<div className={'gv-options gv-'+item.id.toLowerCase()}>{choices.map(c=><button type='button' key={c.id} className={selected===c.id?'selected':''} aria-pressed={selected===c.id} onClick={()=>choose(c.id)}>{renderChoice(c)}{selected===c.id&&<b className='gv-check'>✓</b>}</button>)}</div>}</div><div className='gv-bottom'><div><ShieldCheck/><span><strong>Doğru/yanlış gösterilmiyor.</strong><small>Seçim süresi ve fikir değişiklikleri ham kanıt olarak saklanır. Görsel bellek ekranında cevaplar görüntü kapanmadan açılmaz.</small></span></div><div style={{display:'flex',gap:9,flexWrap:'wrap',justifyContent:'flex-end'}}><button type='button' className='cza-btn cza-soft' disabled={busy} onClick={()=>next(true)}>Bu soruyu geç</button><button className='gv-next' disabled={!ready||busy} onClick={()=>next(false)}>{busy?'Kaydediliyor…':idx===9?'Görsel Turu Tamamla':'Sonraki Görev'} <span>→</span></button></div></div><footer className='gv-footer'><span>{studentLabel||'Öğrenci'} · 10 yoğun görev</span><span>mekân • kural • dikkat • bellek • problem</span></footer></section></main></div>;
}
