'use client';
import { useCallback,useEffect,useMemo,useState } from 'react';
import { CalendarRange,ClipboardCheck,GraduationCap,MessageSquareText,RefreshCw,Target } from 'lucide-react';
import type { LucideIcon } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';

type Row=Record<string,unknown>;
type Data={programs:Row[];goals:Row[];topics:Row[];plans:Array<Row&{items:Row[]}>;studyLogs:Row[];exams:Row[];mistakes:Row[];meetings:Row[];templates:Row[];provenance:'CLIENT_REPORTED'};
const uid=()=>crypto.randomUUID();
const today=()=>new Date().toISOString().slice(0,10);
const field='min-h-11 w-full rounded-xl border border-[#d4dfda] bg-white px-3 text-sm';
const asText=(v:unknown)=>typeof v==='string'?v:'';
const displayNumber=(v:unknown)=>typeof v==='number'||typeof v==='string'?String(v):'Yeterli kayıt yok';

export function CoachingCenter({studentId,audience}:{studentId?:string;audience:'educator'|'student'}){
  const endpoint=audience==='educator'?`/api/educator-coaching?studentId=${encodeURIComponent(studentId||'')}`:'/api/core/coaching';
  const [data,setData]=useState<Data|null>(null),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[version,setVersion]=useState(0);
  const [programType,setProgramType]=useState<'LGS'|'YKS'>('LGS'),[examYear,setExamYear]=useState(new Date().getFullYear()+1),[target,setTarget]=useState('Hedefimi düzenle');
  const [subject,setSubject]=useState('Matematik'),[topic,setTopic]=useState(''),[taskTitle,setTaskTitle]=useState('Günlük akademik çalışma'),[taskKind,setTaskKind]=useState<'academic'|'cza_module'>('academic');
  const [questions,setQuestions]=useState('20'),[minutes,setMinutes]=useState('30'),[feedback,setFeedback]=useState('');
  const [meeting,setMeeting]=useState('Gelecek hafta odağı ve alınan karar');
  const load=useCallback(async()=>{try{const response=await fetch(endpoint,{cache:'no-store'});const body=await response.json();if(!response.ok||!body.ok)throw new Error(body.error||'Koçluk verisi alınamadı.');setData(body.coaching);}catch(error){setMessage(error instanceof Error?error.message:'Koçluk verisi alınamadı.');}},[endpoint]);
  useEffect(()=>{const timer=setTimeout(()=>void load(),0);return()=>clearTimeout(timer);},[load,version]);
  const activeProgram=useMemo(()=>data?.programs.find(row=>row.status==='active'),[data]);
  async function command(action:string,payload:Row){setBusy(true);setMessage('');try{const response=await fetch(audience==='educator'?'/api/educator-coaching':'/api/core/coaching',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action,...(studentId?{studentId}:{}),...payload})});const body=await response.json();if(!response.ok||!body.ok)throw new Error(body.error||'İşlem tamamlanamadı.');setMessage('İşlem kaydedildi.');setVersion(v=>v+1);}catch(error){setMessage(error instanceof Error?error.message:'İşlem tamamlanamadı.');}finally{setBusy(false);}}
  if(!data)return <section className="rounded-3xl border bg-white p-6"><output className="flex items-center gap-2"><RefreshCw className="animate-spin" size={18}/> Koçluk Merkezi hazırlanıyor…</output>{message&&<p role="alert" className="mt-3 text-sm text-amber-800">{message}</p>}</section>;
  const publishedItems:Row[]=data.plans.flatMap(plan=>Array.isArray(plan.items)?plan.items.map(item=>({...item,planId:plan.id,planVersion:plan.version,planStatus:plan.status} as Row)):[]);
  const cards:Array<[LucideIcon,string,number]>=[[Target,'Hedef',data.goals.length],[CalendarRange,'Plan',data.plans.length],[ClipboardCheck,'Çalışma',data.studyLogs.length],[GraduationCap,'Deneme',data.exams.length]];
  return <section className="rounded-3xl border border-[#d6e2dc] bg-[#f7faf8] p-5 shadow-sm sm:p-7" aria-label="LGS YKS Koçluk Merkezi">
    <header className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-xs font-black uppercase tracking-[.14em] text-[#2d705d]">LGS · YKS ortak çekirdek</p><h3 className="mt-2 text-2xl font-black">Koçluk Merkezi</h3><p className="mt-2 text-sm text-[#5f7169]">Tek öğrenci kimliği · aynı görev, geçmiş ve öğrenme profili</p></div><span className="rounded-full bg-amber-100 px-3 py-1.5 text-xs font-bold text-amber-900">Manuel performans: İstemci bildirimi</span></header>
    {message&&<output className="mt-4 block rounded-xl bg-white p-3 text-sm font-semibold text-[#315f50]">{message}</output>}
    <div className="mt-5 grid gap-4 sm:grid-cols-2 xl:grid-cols-4">
      {cards.map(([Icon,label,count])=><article key={label} className="rounded-2xl bg-white p-4"><Icon className="text-[#276151]"/><b className="mt-3 block">{label}</b><strong className="text-2xl">{count}</strong></article>)}
    </div>
    {audience==='educator'?<div className="mt-6 grid gap-5 xl:grid-cols-2">
      <form className="rounded-2xl bg-white p-5" onSubmit={e=>{e.preventDefault();void command('goal',{programType,examYear,target:{statement:target,kind:'target_not_prediction'},clientRequestId:uid()});}}><h4 className="font-black">Program ve hedef</h4><div className="mt-3 grid gap-3 sm:grid-cols-2"><select className={field} value={programType} onChange={e=>setProgramType(e.target.value as 'LGS'|'YKS')}><option>LGS</option><option>YKS</option></select><Input type="number" value={examYear} onChange={e=>setExamYear(Number(e.target.value))}/></div><Input className="mt-3" value={target} onChange={e=>setTarget(e.target.value)} maxLength={300}/><Button className="mt-3" disabled={busy}>Hedefi sürümleyerek kaydet</Button></form>
      <form className="rounded-2xl bg-white p-5" onSubmit={e=>{e.preventDefault();if(!activeProgram)return setMessage('Önce aktif program ve hedef oluştur.');void command('publish_plan',{programId:activeProgram.id,title:taskTitle,taskKind,subject,topic,moduleCode:'finger_read',instructions:'Yayınlanmış koçluk planı görevi',periodStart:today(),periodEnd:today(),scheduledFor:today(),targetQuestions:Number(questions)||null,targetMinutes:Number(minutes)||null,clientRequestId:uid()});}}><h4 className="font-black">Planı yayınla ve canonical görev oluştur</h4><div className="mt-3 grid gap-3 sm:grid-cols-2"><select className={field} value={taskKind} onChange={e=>setTaskKind(e.target.value as 'academic'|'cza_module')}><option value="academic">Akademik görev</option><option value="cza_module">CZA modül görevi</option></select><Input value={taskTitle} onChange={e=>setTaskTitle(e.target.value)}/>{taskKind==='academic'?<><Input value={subject} onChange={e=>setSubject(e.target.value)} placeholder="Ders"/><Input value={topic} onChange={e=>setTopic(e.target.value)} placeholder="Konu"/></>:<p className="text-sm text-[#5f7169]">Mevcut izinli Parmak Okuma motoru kullanılır.</p>}</div><Button className="mt-3" disabled={busy||!activeProgram}>Yayınla</Button></form>
      <form className="rounded-2xl bg-white p-5" onSubmit={e=>{e.preventDefault();if(!activeProgram)return;const template=data.templates.find(t=>t.program_type===activeProgram.program_type);if(!template)return setMessage('Uyumlu demo şablon yok.');const rules=template.rules as {sections?:Array<{code:string;questions:number}>};void command('exam',{programId:activeProgram.id,templateId:template.id,examDate:today(),sections:(rules.sections||[]).map(s=>({code:s.code,correct:0,wrong:0,blank:s.questions})),clientRequestId:uid()});}}><h4 className="font-black">Deneme kaydı</h4><p className="mt-2 text-sm text-[#66766f]">Sürüm bağlı DEMO şablonla, net sunucuda hesaplanır. Bu ekran örnek olarak tüm cevapları boş kaydeder.</p><Button className="mt-3" disabled={busy||!activeProgram}>Demo deneme kaydet</Button></form>
      <form className="rounded-2xl bg-white p-5" onSubmit={e=>{e.preventDefault();if(!activeProgram)return;void command('meeting',{programId:activeProgram.id,meetingAt:new Date().toISOString(),privateNote:'Koça özel eğitimsel gözlem',sharedSummary:meeting,nextWeekFocus:meeting,clientRequestId:uid()});}}><h4 className="flex items-center gap-2 font-black"><MessageSquareText size={18}/> Koç görüşmesi</h4><Input className="mt-3" value={meeting} onChange={e=>setMeeting(e.target.value)}/><Button className="mt-3" disabled={busy||!activeProgram}>Görüşme kararını kaydet</Button></form>
      <form className="rounded-2xl bg-white p-5" onSubmit={e=>{e.preventDefault();if(!activeProgram||!topic.trim())return setMessage('Ders ve konu gir.');const existing=data.topics.find(row=>row.program_id===activeProgram.id&&row.subject_code===subject&&row.topic_code===topic);void command('topic_status',{programId:activeProgram.id,subject,topic,status:'in_progress',expectedVersion:Number(existing?.version)||0});}}><h4 className="font-black">Ders ve konu haritası</h4><div className="mt-3 grid gap-3 sm:grid-cols-2"><Input value={subject} onChange={e=>setSubject(e.target.value)} placeholder="Ders"/><Input value={topic} onChange={e=>setTopic(e.target.value)} placeholder="Konu"/></div><Button className="mt-3" disabled={busy||!activeProgram}>Çalışılıyor olarak işaretle</Button></form>
      <form className="rounded-2xl bg-white p-5" onSubmit={e=>{e.preventDefault();if(!activeProgram||!data.exams[0])return setMessage('Önce kaynak deneme kaydı gerekir.');void command('mistake_revision',{programId:activeProgram.id,examResultId:data.exams[0].id,subject,topic,reason:'coach_review',explanation:'Koç incelemesine bağlı tekrar görevi',clientRequestId:uid()});}}><h4 className="font-black">Hata kaydından tekrar görevi</h4><p className="mt-2 text-sm text-[#66766f]">Son deneme kaynağına bağlı canonical akademik tekrar görevi oluşturur.</p><Button className="mt-3" disabled={busy||!activeProgram||!data.exams.length}>Tekrar görevi oluştur</Button></form>
    </div>:<div className="mt-6 rounded-2xl bg-white p-5"><h4 className="font-black">Hedefim ve bugünkü planım</h4><p className="mt-2 text-sm text-[#66766f]">Yalnız yayınlanmış görevler ve öğrenciyle paylaşılan görüşme özeti görünür.</p></div>}
    <div className="mt-6 grid gap-4 lg:grid-cols-2">{publishedItems.map(item=><article key={String(item.itemId)} className="rounded-2xl border bg-white p-5"><div className="flex flex-wrap justify-between gap-2"><b>{asText(item.name)}</b><span className="rounded-full bg-[#edf5f1] px-2 py-1 text-xs font-bold">{item.taskKind==='academic'?'Akademik çalışma':'CZA modülü'}</span></div><p className="mt-2 text-sm text-[#66766f]">{asText(item.subject)||asText(item.moduleCode)} {item.topic?`· ${asText(item.topic)}`:''}</p>{audience==='educator'&&item.planStatus==='published'?<Button className="mt-3" variant="outline" disabled={busy} onClick={()=>void command('cancel_plan',{planId:item.planId,expectedVersion:item.planVersion})}>Planı iptal et</Button>:null}{audience==='student'&&item.taskKind==='academic'&&item.active===true?<form className="mt-4 grid gap-2 sm:grid-cols-3" onSubmit={e=>{e.preventDefault();void command('study_log',{recipeId:item.recipeId,questionCount:Number(questions)||null,durationMinutes:Number(minutes)||null,feedback,clientRequestId:uid()});}}><Input type="number" value={questions} onChange={e=>setQuestions(e.target.value)} placeholder="Soru"/><Input type="number" value={minutes} onChange={e=>setMinutes(e.target.value)} placeholder="Dakika"/><Input value={feedback} onChange={e=>setFeedback(e.target.value)} placeholder="Geri bildirim"/><Button disabled={busy} className="sm:col-span-3">Çalışmamı bildir</Button></form>:null}</article>)}{!publishedItems.length?<p className="rounded-2xl border border-dashed bg-white p-6 text-sm text-[#66766f]">Yayınlanmış koçluk görevi yok.</p>:null}</div>
    <div className="mt-6 grid gap-4 lg:grid-cols-3"><section className="rounded-2xl bg-white p-5"><h4 className="font-black">Sonuçlarım</h4>{data.exams.map(row=><p key={String(row.id)} className="mt-2 text-sm">{asText(row.stage)} · Net {displayNumber(row.total_net)} · İstemci bildirimi</p>)}</section><section className="rounded-2xl bg-white p-5"><h4 className="font-black">Yanlış / tekrar</h4><p className="mt-2 text-sm">{data.mistakes.length} kaynak bağlı kayıt · otomatik kazanım hükmü yok</p></section><section className="rounded-2xl bg-white p-5"><h4 className="font-black">Görüşmeler</h4>{data.meetings.map(row=><p key={String(row.id)} className="mt-2 text-sm">{asText(row.shared_summary)||'Paylaşılan özet yok'}</p>)}</section></div>
  </section>;
}
