'use client';

import { Button } from '@/components/ui/button';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Slider } from '@/components/ui/slider';
import { Switch } from '@/components/ui/switch';
import { defaultConfig, modeLabels, type ExerciseConfig, type ExerciseMode, type Operation } from '@/lib/exercise-engine';

export function ExerciseSettings({ config, onChange, disabled = false }: { config: ExerciseConfig; onChange: (config: ExerciseConfig) => void; disabled?: boolean }) {
  const update = (values: Partial<ExerciseConfig>) => onChange({ ...config, ...values });
  const mental = config.mode === 'flash' || config.mode === 'audio';
  const flash = config.mode === 'flash';
  const additionPool = config.additionPool ?? config.pool;
  const subtractionPool = config.subtractionPool ?? config.pool;
  const togglePool = (key: 'additionPool' | 'subtractionPool', value: number) => {
    const source = key === 'additionPool' ? additionPool : subtractionPool;
    const next = source.includes(value) ? source.filter(item => item !== value) : [...source, value].sort((a, b) => a - b);
    update({ [key]: next, pool: next.length ? next : config.pool } as Partial<ExerciseConfig>);
  };
  return <fieldset disabled={disabled} className="space-y-5 disabled:opacity-50">
    <div><label htmlFor="exercise-mode" className="mb-2 block text-xs font-semibold">Çalışma türü</label>
      <Select value={config.mode} onValueChange={v => v && update({ mode: v as ExerciseMode })} disabled={disabled}>
        <SelectTrigger id="exercise-mode" className="h-10 w-full"><SelectValue>{modeLabels[config.mode]}</SelectValue></SelectTrigger>
        <SelectContent>{Object.entries(modeLabels).map(([key, label]) => <SelectItem key={key} value={key}>{label}</SelectItem>)}</SelectContent>
      </Select>
    </div>
      <div className="grid grid-cols-2 gap-4">
      <div><label htmlFor="digits" className="mb-2 block text-xs font-semibold">Basamak</label><Select value={String(config.digits)} onValueChange={v => v && update({ digits: Number(v), minDigits: Number(v), maxDigits: Number(v) })} disabled={disabled}><SelectTrigger id="digits" className="h-10 w-full"><SelectValue>{config.digits} basamak</SelectValue></SelectTrigger><SelectContent>{[1,2,3,4,5].map(v => <SelectItem key={v} value={String(v)}>{v} basamak</SelectItem>)}</SelectContent></Select></div>
      <div><label htmlFor="rounds" className="mb-2 block text-xs font-semibold">Soru sayısı</label><Select value={String(config.rounds)} onValueChange={v => v && update({ rounds: Number(v) })} disabled={disabled}><SelectTrigger id="rounds" className="h-10 w-full"><SelectValue>{config.rounds} soru</SelectValue></SelectTrigger><SelectContent>{[3,5,10,15,20,30].map(v => <SelectItem key={v} value={String(v)}>{v} soru</SelectItem>)}</SelectContent></Select></div>
    </div>
    {mental && <>
      <div><label htmlFor="operation" className="mb-2 block text-xs font-semibold">İşlem türü</label><Select value={config.operation} onValueChange={v => v && update({ operation: v as Operation })} disabled={disabled}><SelectTrigger id="operation" className="h-10 w-full"><SelectValue>{config.operation === 'add' ? 'Toplama' : config.operation === 'subtract' ? 'Çıkarma' : 'Toplama ve çıkarma'}</SelectValue></SelectTrigger><SelectContent><SelectItem value="add">Toplama</SelectItem><SelectItem value="subtract">Çıkarma</SelectItem><SelectItem value="mixed">Toplama ve çıkarma</SelectItem></SelectContent></Select></div>
      <div><div className="mb-4 flex justify-between text-xs"><span id="terms-label" className="font-semibold">İşlem sayısı</span><span>{config.terms} sayı</span></div><Slider aria-labelledby="terms-label" value={[config.terms]} min={2} max={30} step={1} disabled={disabled} onValueChange={v => update({ terms: Number(Array.isArray(v) ? v[0] : v) })} /></div>
      <div className="border-t border-border pt-4"><div className="flex items-center justify-between"><label htmlFor="manual-mode" className="text-xs font-semibold">Adım adım ilerle</label><Switch id="manual-mode" checked={config.interval === 0} disabled={disabled} onCheckedChange={v => update({ interval: v ? 0 : 1.5 })} /></div><p className="mt-1 text-[11px] leading-5 text-muted-foreground">Süre baskısı olmadan, her sayıyı sen ilerlet.</p></div>
      {config.interval > 0 && <div><div className="mb-4 flex justify-between text-xs"><label id="interval-label" className="font-semibold">{config.mode === 'audio' ? 'Sesler arası bekleme' : 'Sayı gösterim süresi'}</label><span>{config.interval.toFixed(1)} sn</span></div><Slider aria-labelledby="interval-label" value={[config.interval]} min={.1} max={8} step={.1} disabled={disabled} onValueChange={v => update({ interval: Number(Array.isArray(v) ? v[0] : v) })} /></div>}
    </>}
    {flash && <div className="space-y-4 border-t border-border pt-4">
      <div className="grid grid-cols-2 gap-4"><div><label htmlFor="min-digits" className="mb-2 block text-xs font-semibold">Minimum hane</label><Select value={String(config.minDigits ?? config.digits)} onValueChange={v => { if (!v) return; const value = Number(v); update({ minDigits: value, digits: value, maxDigits: Math.max(value, config.maxDigits ?? value) }); }}><SelectTrigger id="min-digits" className="h-10 w-full"><SelectValue /></SelectTrigger><SelectContent>{[1,2,3,4,5].map(v => <SelectItem key={v} value={String(v)}>{v}</SelectItem>)}</SelectContent></Select></div><div><label htmlFor="max-digits" className="mb-2 block text-xs font-semibold">Maksimum hane</label><Select value={String(config.maxDigits ?? config.digits)} onValueChange={v => v && update({ maxDigits: Math.max(Number(v), config.minDigits ?? 1) })}><SelectTrigger id="max-digits" className="h-10 w-full"><SelectValue /></SelectTrigger><SelectContent>{[1,2,3,4,5].map(v => <SelectItem key={v} value={String(v)}>{v}</SelectItem>)}</SelectContent></Select></div></div>
      <div><label htmlFor="max-value" className="mb-2 block text-xs font-semibold">Maksimum değer</label><input id="max-value" type="number" min={1} max={99999} value={config.maxValue ?? 900} onChange={event => update({ maxValue: Math.max(1, Number(event.target.value) || 1) })} className="h-10 w-full rounded-lg border border-input bg-background px-3 text-sm" /></div>
      <div className="flex items-center justify-between"><label htmlFor="first-within-max" className="text-xs font-semibold">İlk sayı maksimum değere göre verilsin</label><Switch id="first-within-max" checked={config.firstWithinMax !== false} onCheckedChange={value => update({ firstWithinMax: value })} /></div>
      <div className="grid grid-cols-2 gap-3"><div><span className="mb-2 block text-xs font-semibold">Toplama havuzu</span><div className="grid grid-cols-5 gap-1">{[1,2,3,4,5,6,7,8,9].map(value => <Button type="button" key={value} size="sm" variant={additionPool.includes(value) ? 'default' : 'outline'} aria-pressed={additionPool.includes(value)} onClick={() => togglePool('additionPool', value)}>{value}</Button>)}</div></div><div><span className="mb-2 block text-xs font-semibold">Çıkarma havuzu</span><div className="grid grid-cols-5 gap-1">{[1,2,3,4,5,6,7,8,9].map(value => <Button type="button" key={value} size="sm" variant={subtractionPool.includes(value) ? 'default' : 'outline'} aria-pressed={subtractionPool.includes(value)} onClick={() => togglePool('subtractionPool', value)}>{value}</Button>)}</div></div></div>
      <div className="flex items-center justify-between"><label htmlFor="free-practice" className="text-xs font-semibold">Serbest çalışma</label><Switch id="free-practice" checked={config.freePractice === true} onCheckedChange={value => update({ freePractice: value })} /></div>
      <div className="grid grid-cols-2 gap-3"><div><label htmlFor="font-size" className="mb-2 block text-xs font-semibold">Rakam boyutu</label><input id="font-size" type="number" min={48} max={180} value={config.fontSize ?? 95} onChange={event => update({ fontSize: Math.min(180, Math.max(48, Number(event.target.value) || 95)) })} className="h-10 w-full rounded-lg border border-input bg-background px-3 text-sm" /></div><div className="flex items-end gap-2 pb-2"><input id="show-numbers" type="checkbox" checked={config.showNumbers !== false} onChange={event => update({ showNumbers: event.target.checked })} className="h-4 w-4" /><label htmlFor="show-numbers" className="text-xs font-semibold">Sayılar gösterilsin</label></div></div>
      <div className="grid grid-cols-2 gap-3"><div><label htmlFor="background-color" className="mb-2 block text-xs font-semibold">Zemin rengi</label><input id="background-color" type="color" value={config.backgroundColor ?? '#ffffff'} onChange={event => update({ backgroundColor: event.target.value })} className="h-10 w-full cursor-pointer rounded-lg border border-input bg-background p-1" /></div><div><label htmlFor="text-color" className="mb-2 block text-xs font-semibold">Yazı rengi</label><input id="text-color" type="color" value={config.textColor ?? '#111827'} onChange={event => update({ textColor: event.target.value })} className="h-10 w-full cursor-pointer rounded-lg border border-input bg-background p-1" /></div></div>
      <p className="text-[11px] leading-5 text-muted-foreground">0 saniye süresiz/manuel akıştır. Süre seçildiğinde sayı yalnız gösterim süresi kadar görünür; cevap için ek süre sınırı uygulanmaz.</p>
    </div>}
    <details className="border-t border-border pt-4"><summary className="cursor-pointer text-xs font-semibold">Gelişmiş · rakam havuzu</summary><p className="mb-3 mt-3 text-[11px] leading-5 text-muted-foreground">Tek basamaklı çalışmalarda kullanılacak rakamlar. Çok basamaklı çalışmalarda tüm sayılar kullanılır.</p><div className="grid grid-cols-5 gap-2">{[1,2,3,4,5,6,7,8,9].map(n => <Button type="button" key={n} variant={config.pool.includes(n) ? 'default' : 'outline'} disabled={disabled || config.digits > 1} aria-pressed={config.pool.includes(n)} onClick={() => update({ pool: config.pool.includes(n) ? config.pool.filter(v=>v!==n) : [...config.pool,n] })}>{n}</Button>)}</div></details>
    <Button type="button" variant="ghost" className="w-full text-xs text-muted-foreground" disabled={disabled} onClick={() => onChange({...defaultConfig, mode: config.mode})}>Ayarları sıfırla</Button>
  </fieldset>;
}
