'use client';

import { Calculator, Check, Gauge, Grid3X3, Hand } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Slider } from '@/components/ui/slider';
import { Switch } from '@/components/ui/switch';
import { defaultConfig, type ExerciseConfig, type ExerciseMode, type Operation } from '@/lib/exercise-engine';
import { exerciseCategories, exerciseRegistry, type ExerciseCategory, type ExerciseDefinition } from '@/lib/exercise-registry';
import { feedbackModeFor, practiceModeDescriptions, practiceModeLabels, shouldShowCountdown, type PracticeMode } from '@/lib/practice-mode';
import { answerPresets, durationLabel, presentationPresets, speedLabel } from '@/lib/timed-stimulus';

const categoryOrder: ExerciseCategory[] = ['paritmetik','soroban','arithmetic','anzan'];
const icons = { hand: Hand, abacus: Grid3X3, operation: Calculator, speed: Gauge };
const categoryTheme: Record<ExerciseCategory, { heading: string; selected: string; icon: string; idleIcon: string }> = {
  paritmetik: { heading: 'text-[#9a522c]', selected: 'border-[#d88a5e] bg-[#fff2e8]', icon: 'bg-[#c86e3c] text-white', idleIcon: 'bg-[#f8e5d6] text-[#9a522c]' },
  soroban: { heading: 'text-[#166f68]', selected: 'border-[#4aa79d] bg-[#e9f7f4]', icon: 'bg-[#168579] text-white', idleIcon: 'bg-[#dff1ed] text-[#166f68]' },
  arithmetic: { heading: 'text-[#315e92]', selected: 'border-[#719dcc] bg-[#edf5ff]', icon: 'bg-[#3f76ad] text-white', idleIcon: 'bg-[#e2edf9] text-[#315e92]' },
  anzan: { heading: 'text-[#705391]', selected: 'border-[#a987ca] bg-[#f5effb]', icon: 'bg-[#7d5aa2] text-white', idleIcon: 'bg-[#ece2f5] text-[#705391]' },
};

function ModuleCard({ exercise, selected, disabled, choose }: { exercise: ExerciseDefinition; selected: boolean; disabled: boolean; choose: (mode: ExerciseMode) => void }) {
  const Icon = icons[exercise.icon];
  const theme = categoryTheme[exercise.category];
  const classes = `group relative flex min-h-20 w-full items-center gap-3 rounded-xl border p-3 text-left transition ${selected ? `${theme.selected} shadow-sm` : 'border-border bg-white hover:border-[#9ebcaf] hover:bg-[#f8fbf9]'}`;
  const body = <><span className={`grid h-10 w-10 shrink-0 place-items-center rounded-lg ${selected ? theme.icon : theme.idleIcon}`}><Icon size={20}/></span><span className="min-w-0"><strong className="block text-sm">{exercise.title}</strong><small className="mt-1 block text-[11px] leading-4 text-muted-foreground">{exercise.description}</small></span>{selected && <Check className={`ml-auto shrink-0 ${theme.heading}`} size={18}/>}</>;
  if (exercise.href) return <a href={exercise.href} aria-label={`${exercise.title} çalışmasını aç`} className={classes}>{body}</a>;
  return <button type="button" disabled={disabled} aria-pressed={selected} className={classes} onClick={() => exercise.mode && choose(exercise.mode)}>{body}</button>;
}

export function ExerciseSettings({ config, onChange, disabled = false }: { config: ExerciseConfig; onChange: (config: ExerciseConfig) => void; disabled?: boolean }) {
  const update = (values: Partial<ExerciseConfig>) => onChange({ ...config, ...values });
  const choose = (mode: ExerciseMode) => { const digits = mode === 'finger-read' ? Math.min(2, config.digits) : config.digits; update({ mode, digits, minDigits: digits, maxDigits: digits }); };
  const timedReading = config.mode === 'finger-read' || config.mode === 'soroban-read';
  const soroban = config.mode.startsWith('soroban');
  const mental = config.mode === 'flash' || config.mode === 'audio';
  const flash = config.mode === 'flash';
  const maxDigits = config.mode === 'finger-read' ? 2 : soroban ? config.rods ?? 5 : 5;
  const additionPool = config.additionPool ?? config.pool;
  const subtractionPool = config.subtractionPool ?? config.pool;
  const togglePool = (key: 'additionPool' | 'subtractionPool', value: number) => { const source = key === 'additionPool' ? additionPool : subtractionPool; const next = source.includes(value) ? source.filter(item => item !== value) : [...source, value].sort((a,b)=>a-b); update({[key]:next,pool:next.length?next:config.pool} as Partial<ExerciseConfig>); };
  const applyReadingPreset = (preset: 'start' | 'middle' | 'fast' | 'expert') => {
    const values = preset === 'start' ? {digits:1,rounds:10,presentationDurationMs:1500} : preset === 'middle' ? {digits:Math.min(2,maxDigits),rounds:15,presentationDurationMs:1000} : preset === 'fast' ? {digits:Math.min(2,maxDigits),rounds:20,presentationDurationMs:500} : {digits:Math.min(2,maxDigits),rounds:20,presentationDurationMs:250};
    update({...values,minDigits:values.digits,maxDigits:values.digits});
  };
  const practiceMode = config.practiceMode ?? 'free_practice';
  const choosePracticeMode = (next: PracticeMode) => update({ practiceMode: next, feedbackMode: feedbackModeFor(next), countdownEnabled: next === 'performance' || next === 'assessment', answerDurationMs: next === 'performance' || next === 'assessment' ? (config.answerDurationMs || 10000) : 0 });
  const countdownVisible = shouldShowCountdown({ practiceMode, exerciseType: config.mode, timed: timedReading || config.interval > 0, assessmentMode: practiceMode === 'assessment', countdownEnabled: config.countdownEnabled });

  return <fieldset disabled={disabled} className="space-y-5 disabled:opacity-50">
    <div className="space-y-4">{categoryOrder.map(category => <section key={category} aria-labelledby={`category-${category}`}><h3 id={`category-${category}`} className={`mb-2 text-xs font-extrabold uppercase tracking-[.08em] ${categoryTheme[category].heading}`}>{exerciseCategories[category].title}</h3><div className="grid gap-2 sm:grid-cols-2 lg:grid-cols-1">{exerciseRegistry.filter(item=>item.category===category).map(item=><ModuleCard key={item.id} exercise={item} selected={item.mode===config.mode} disabled={disabled} choose={choose}/>)}</div></section>)}</div>

    <section className="rounded-xl border-2 border-[#b9daca] bg-[#f3fbf7] p-4"><p className="text-[11px] font-black uppercase tracking-[.08em] text-[#176e5e]">Ana çalışma modu</p><div className="mt-3 grid gap-2">{(Object.keys(practiceModeLabels) as PracticeMode[]).map(mode=><button type="button" key={mode} aria-pressed={practiceMode===mode} onClick={()=>choosePracticeMode(mode)} className={`rounded-xl border p-3 text-left transition ${practiceMode===mode?'border-[#14836f] bg-[#0f806c] text-white shadow-md':'border-[#cddbd5] bg-white hover:border-[#62a995]'}`}><strong className="block text-sm">{practiceMode===mode?'✓ ':''}{practiceModeLabels[mode]}</strong><span className={`mt-1 block text-[11px] leading-4 ${practiceMode===mode?'text-[#d9fff2]':'text-muted-foreground'}`}>{practiceModeDescriptions[mode]}</span></button>)}</div></section>

    <section className="rounded-xl border border-[#cbdad4] bg-[#f8fbf9] p-4"><p className="text-[11px] font-bold uppercase tracking-[.08em] text-[#277161]">Çalışma ayarları</p><h3 className="mt-1 font-bold">{exerciseRegistry.find(item=>item.mode===config.mode)?.title}</h3>
      <div className="mt-4 grid grid-cols-2 gap-3"><div><label htmlFor="digits" className="mb-2 block text-xs font-semibold">Basamak</label><Select value={String(config.digits)} onValueChange={value=>value&&update({digits:Number(value),minDigits:Number(value),maxDigits:Number(value)})} disabled={disabled}><SelectTrigger id="digits" className="h-11 w-full"><SelectValue/></SelectTrigger><SelectContent>{Array.from({length:maxDigits},(_,index)=>index+1).map(value=><SelectItem key={value} value={String(value)}>{value} basamak</SelectItem>)}</SelectContent></Select></div><div><label htmlFor="rounds" className="mb-2 block text-xs font-semibold">Soru sayısı</label><Select value={String(config.rounds)} onValueChange={value=>value&&update({rounds:Number(value)})} disabled={disabled}><SelectTrigger id="rounds" className="h-11 w-full"><SelectValue/></SelectTrigger><SelectContent>{[5,10,15,20,30,50].map(value=><SelectItem key={value} value={String(value)}>{value} soru</SelectItem>)}</SelectContent></Select></div></div>
      {soroban&&<div className="mt-4"><span className="mb-2 block text-xs font-semibold">Soroban çubuk sayısı</span><div className="grid grid-cols-4 gap-2">{([4,5,6,7] as const).map(rods=><Button key={rods} type="button" variant={(config.rods??5)===rods?'default':'outline'} aria-pressed={(config.rods??5)===rods} onClick={()=>update({rods,digits:Math.min(config.digits,rods),maxDigits:Math.min(config.maxDigits??config.digits,rods)})}>{rods}</Button>)}</div></div>}
      {timedReading&&<div className="mt-4 space-y-4 border-t border-[#dbe5e1] pt-4"><div><span className="mb-2 block text-xs font-semibold">Hızlı reçete</span><div className="grid grid-cols-2 gap-2">{([['start','Başlangıç'],['middle','Orta'],['fast','Hızlı'],['expert','Uzman']] as const).map(([value,label])=><Button type="button" key={value} variant="outline" className="bg-white" onClick={()=>applyReadingPreset(value)}>{label}</Button>)}</div></div><div><label htmlFor="presentation-duration" className="mb-2 block text-xs font-semibold">Gösterim süresi</label><Select value={String(config.presentationDurationMs??1000)} onValueChange={value=>value&&update({presentationDurationMs:Number(value)})}><SelectTrigger id="presentation-duration" className="h-11 w-full"><SelectValue/></SelectTrigger><SelectContent>{presentationPresets.map(value=><SelectItem key={value} value={String(value)}>{durationLabel(value)} · {speedLabel(value)}</SelectItem>)}</SelectContent></Select></div><div><label htmlFor="answer-duration" className="mb-2 block text-xs font-semibold">Cevap süresi</label><Select value={String(config.answerDurationMs??0)} onValueChange={value=>value&&update({answerDurationMs:Number(value)})} disabled={!['performance','assessment'].includes(practiceMode)}><SelectTrigger id="answer-duration" className="h-11 w-full"><SelectValue/></SelectTrigger><SelectContent>{answerPresets.map(value=><SelectItem key={value} value={String(value)}>{value===0?'Süre kısıtlaması yok':`${value/1000} saniye`}</SelectItem>)}</SelectContent></Select></div><div className="flex items-center justify-between"><div><label htmlFor="countdown" className="text-xs font-semibold">3–2–1 hazırlık</label><p className="mt-1 text-[11px] text-muted-foreground">Performans ve değerlendirmede otomatik; antrenmanda eğitimci seçebilir.</p></div><Switch id="countdown" checked={countdownVisible} disabled={practiceMode==='performance'||practiceMode==='assessment'} onCheckedChange={value=>update({countdownEnabled:value})}/></div></div>}
      {mental&&<div className="mt-4 space-y-4 border-t border-[#dbe5e1] pt-4"><div><label htmlFor="operation" className="mb-2 block text-xs font-semibold">İşlem türü</label><Select value={config.operation} onValueChange={value=>value&&update({operation:value as Operation})}><SelectTrigger id="operation" className="h-11 w-full"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="add">Toplama</SelectItem><SelectItem value="subtract">Çıkarma</SelectItem><SelectItem value="mixed">Toplama ve çıkarma</SelectItem></SelectContent></Select></div><div><div className="mb-4 flex justify-between text-xs"><span id="terms-label" className="font-semibold">İşlem sayısı</span><span>{config.terms} sayı</span></div><Slider aria-labelledby="terms-label" value={[config.terms]} min={2} max={30} step={1} onValueChange={value=>update({terms:Number(Array.isArray(value)?value[0]:value)})}/></div><div><div className="mb-4 flex justify-between text-xs"><span id="interval-label" className="font-semibold">{config.mode==='audio'?'Sesler arası bekleme':'Sayı gösterim süresi'}</span><span>{config.interval===0?'Adım adım':`${config.interval.toFixed(1)} sn`}</span></div><Slider aria-labelledby="interval-label" value={[config.interval]} min={0} max={8} step={.1} onValueChange={value=>update({interval:Number(Array.isArray(value)?value[0]:value)})}/></div></div>}
      {timedReading&&(config.presentationDurationMs??1000)<=200&&config.digits>=3&&<p className="mt-4 rounded-lg bg-amber-50 p-3 text-xs leading-5 text-amber-900">Bu kombinasyon oldukça yüksek görsel işlemleme hızı gerektiriyor. Seçim korunacak; öğrencinin doğruluk ve tutarlılığını yakından izle.</p>}
    </section>

    <details className="rounded-xl border border-border p-4"><summary className="cursor-pointer text-xs font-semibold">Gelişmiş ayarlar</summary><div className="mt-4 space-y-4"><div className="grid grid-cols-2 gap-3"><label className="text-xs font-semibold">Minimum değer<input type="number" min={0} value={config.minValue??1} onChange={event=>update({minValue:Number(event.target.value)})} className="mt-2 h-10 w-full rounded-lg border px-3"/></label><label className="text-xs font-semibold">Maksimum değer<input type="number" min={1} value={config.maxValue??900} onChange={event=>update({maxValue:Number(event.target.value)})} className="mt-2 h-10 w-full rounded-lg border px-3"/></label></div><div><p className="mb-3 text-[11px] leading-5 text-muted-foreground">Tek basamaklı çalışmalarda kullanılacak rakamlar.</p><div className="grid grid-cols-5 gap-2">{[1,2,3,4,5,6,7,8,9].map(number=><Button type="button" key={number} variant={config.pool.includes(number)?'default':'outline'} aria-pressed={config.pool.includes(number)} onClick={()=>update({pool:config.pool.includes(number)?config.pool.filter(value=>value!==number):[...config.pool,number].sort((a,b)=>a-b)})}>{number}</Button>)}</div></div>{flash&&<div className="grid grid-cols-2 gap-3"><div><span className="mb-2 block text-xs font-semibold">Toplama havuzu</span>{[1,2,3,4,5,6,7,8,9].map(value=><button type="button" className={`m-0.5 h-9 w-9 rounded-lg border ${additionPool.includes(value)?'bg-primary text-white':''}`} key={value} onClick={()=>togglePool('additionPool',value)}>{value}</button>)}</div><div><span className="mb-2 block text-xs font-semibold">Çıkarma havuzu</span>{[1,2,3,4,5,6,7,8,9].map(value=><button type="button" className={`m-0.5 h-9 w-9 rounded-lg border ${subtractionPool.includes(value)?'bg-primary text-white':''}`} key={value} onClick={()=>togglePool('subtractionPool',value)}>{value}</button>)}</div></div>}</div></details>
    <Button type="button" variant="ghost" className="w-full text-xs text-muted-foreground" disabled={disabled} onClick={()=>onChange({...defaultConfig,mode:config.mode})}>Bu modülün ayarlarını sıfırla</Button>
  </fieldset>;
}
