import type { AssessmentTask } from './assessment-engine';

const languageRubric = [
  { id: 'accuracy', label: 'Doğruluk / anlam', max: 2 },
  { id: 'fluency', label: 'Akıcılık ve süreklilik', max: 3 },
  { id: 'explanation', label: 'Düşünceyi açıklama', max: 3 },
  { id: 'independence', label: 'Bağımsızlık', max: 2 },
  { id: 'transfer', label: 'Transfer / yeni durumda kullanma', max: 2 },
];

export const languageTasks: AssessmentTask[] = [
  {
    id: 'TR-01A', groupId: 'TR-01', role: 'ACADEMIC_ANCHOR', title: 'Kısa Cümle Kaşifi',
    childInstruction: 'Şu cümleyi sesli oku: “Ece kırmızı topunu bahçeye götürdü.” Sonra söyle: Ece topunu nereye götürdü?',
    educatorInstruction: 'Okuma sırasında heceleme, tekrar, atlama, kendini düzeltme ve akıcılığı ayrı ayrı gözle. Cevabı yönlendirme.',
    responseModes: ['SPEAK', 'TEXT'], estimatedSeconds: 55,
    skillWeights: [{ skillId: 'reading_fluency', weight: .40 }, { skillId: 'comprehension', weight: .35 }, { skillId: 'attention', weight: .15 }, { skillId: 'verbal_expression', weight: .10 }],
    rubric: languageRubric, next: { success: 'TR-01B', support: 'TR-01S' },
  },
  {
    id: 'TR-01S', groupId: 'TR-01', role: 'SUPPORT_PROBE', title: 'Cümleyi Parçalara Ayıralım',
    childInstruction: '“Ece / kırmızı topunu / bahçeye / götürdü.” Cümlede “nereye?” sorusunun cevabı hangi bölüm?',
    educatorInstruction: 'Okuma güçlüğü ile anlama güçlüğünü ayır. Parçalanmış cümleyle anlam belirginleşiyorsa bunu not et.',
    responseModes: ['SPEAK', 'TEXT'], estimatedSeconds: 45,
    skillWeights: [{ skillId: 'comprehension', weight: .45 }, { skillId: 'reading_fluency', weight: .20 }, { skillId: 'attention', weight: .20 }, { skillId: 'verbal_expression', weight: .15 }],
    rubric: languageRubric, next: { success: 'TR-01B' },
  },
  {
    id: 'TR-01B', groupId: 'TR-01', role: 'CZA_PROBE', title: 'Cümlede Yazmayanı Yakala',
    childInstruction: 'Bu cümlede açıkça yazmayan ama tahmin edebileceğin bir şey söyle. Neden böyle düşündün?',
    educatorInstruction: 'Tahminin doğru olmasından çok, metindeki ipucuyla gerekçe kurup kurmadığına bak.',
    responseModes: ['SPEAK', 'TEXT'], estimatedSeconds: 80,
    skillWeights: [{ skillId: 'comprehension', weight: .30 }, { skillId: 'verbal_expression', weight: .25 }, { skillId: 'problem_solving', weight: .20 }, { skillId: 'cognitive_flexibility', weight: .15 }, { skillId: 'working_memory', weight: .10 }],
    rubric: languageRubric, next: { transfer: 'TR-01T' },
  },
  {
    id: 'TR-01T', groupId: 'TR-01', role: 'TRANSFER', title: 'Yeni Cümlede Aynı Dedektiflik',
    childInstruction: '“Mert montunu giyip şemsiyesini aldı.” Sence dışarıdaki hava nasıl olabilir? Bunu hangi ipucundan anladın?',
    educatorInstruction: 'Önceki çıkarım stratejisini yeni cümleye taşıyıp taşımadığını değerlendir.',
    responseModes: ['SPEAK', 'TEXT'], estimatedSeconds: 70,
    skillWeights: [{ skillId: 'comprehension', weight: .35 }, { skillId: 'problem_solving', weight: .20 }, { skillId: 'verbal_expression', weight: .20 }, { skillId: 'cognitive_flexibility', weight: .15 }, { skillId: 'working_memory', weight: .10 }],
    rubric: languageRubric,
  },
  {
    id: 'TR-02A', groupId: 'TR-02', role: 'ACADEMIC_ANCHOR', title: 'Mini Hikâyeyi Anla',
    childInstruction: '“Defne oyuncağını masanın üstünde bıraktı. Biraz sonra kardeşi oyuncağı sepete koydu.” Oyuncağın en son nerede olduğunu söyle.',
    educatorInstruction: 'İki cümlelik bilgiyi sırayla tutma ve son durumu belirleme becerisini gözle.',
    responseModes: ['SPEAK', 'TEXT'], estimatedSeconds: 55,
    skillWeights: [{ skillId: 'comprehension', weight: .40 }, { skillId: 'working_memory', weight: .30 }, { skillId: 'attention', weight: .20 }, { skillId: 'verbal_expression', weight: .10 }],
    rubric: languageRubric, next: { success: 'TR-02B', support: 'TR-02S' },
  },
  {
    id: 'TR-02S', groupId: 'TR-02', role: 'SUPPORT_PROBE', title: 'Önce ve Sonra',
    childInstruction: 'Önce oyuncak masadaydı. Sonra kardeşi sepete koydu. Şimdi oyuncak nerede?',
    educatorInstruction: 'Bilgiyi sadeleştirince başarı artıyorsa çalışma belleği yüküne duyarlılığı not et.',
    responseModes: ['SPEAK', 'TEXT'], estimatedSeconds: 35,
    skillWeights: [{ skillId: 'comprehension', weight: .45 }, { skillId: 'working_memory', weight: .35 }, { skillId: 'attention', weight: .20 }],
    rubric: languageRubric, next: { success: 'TR-02B' },
  },
  {
    id: 'TR-02B', groupId: 'TR-02', role: 'CZA_PROBE', title: 'Hikâyenin Görünmeyen Parçası',
    childInstruction: 'Defne oyuncağını aramaya gelse ilk önce nerede arayabilir? Sonra ne yapabilir? Neden?',
    educatorInstruction: 'Olay sırası, perspektif alma, neden-sonuç ve olası eylem planını birlikte değerlendir.',
    responseModes: ['SPEAK', 'TEXT'], estimatedSeconds: 85,
    skillWeights: [{ skillId: 'comprehension', weight: .25 }, { skillId: 'problem_solving', weight: .25 }, { skillId: 'verbal_expression', weight: .20 }, { skillId: 'working_memory', weight: .15 }, { skillId: 'cognitive_flexibility', weight: .15 }],
    rubric: languageRubric, next: { transfer: 'TR-02T' },
  },
  {
    id: 'TR-02T', groupId: 'TR-02', role: 'TRANSFER', title: 'Sonu Değiştir',
    childInstruction: 'Hikâyenin sonunu değiştir: Defne oyuncağını başka nasıl bulabilirdi?',
    educatorInstruction: 'Özgünlük kadar olayın mantıksal tutarlılığını da kaydet.',
    responseModes: ['SPEAK', 'TEXT'], estimatedSeconds: 75,
    skillWeights: [{ skillId: 'cognitive_flexibility', weight: .30 }, { skillId: 'verbal_expression', weight: .25 }, { skillId: 'problem_solving', weight: .20 }, { skillId: 'comprehension', weight: .15 }, { skillId: 'self_regulation', weight: .10 }],
    rubric: languageRubric,
  },
  {
    id: 'TR-03A', groupId: 'TR-03', role: 'ACADEMIC_ANCHOR', title: 'Kelime Ailesi',
    childInstruction: 'Kedi bir hayvandır. Elma nedir?',
    educatorInstruction: 'Üst kategori oluşturma ve kelimeyi uygun kavram altında sınıflama becerisini gözle.',
    responseModes: ['SPEAK', 'TEXT'], estimatedSeconds: 30,
    skillWeights: [{ skillId: 'verbal_expression', weight: .35 }, { skillId: 'comprehension', weight: .25 }, { skillId: 'pattern_reasoning', weight: .25 }, { skillId: 'processing_speed', weight: .15 }],
    rubric: languageRubric, next: { success: 'TR-03B', support: 'TR-03S' },
  },
  {
    id: 'TR-03S', groupId: 'TR-03', role: 'SUPPORT_PROBE', title: 'Hangileri Aynı Grupta?',
    childInstruction: 'Elma, armut ve muz aynı grupta. Bu grubun adı ne olabilir?',
    educatorInstruction: 'Örneklerden kategori adına geçiş yapabiliyor mu değerlendir.',
    responseModes: ['SPEAK', 'TEXT'], estimatedSeconds: 35,
    skillWeights: [{ skillId: 'verbal_expression', weight: .35 }, { skillId: 'pattern_reasoning', weight: .35 }, { skillId: 'comprehension', weight: .20 }, { skillId: 'attention', weight: .10 }],
    rubric: languageRubric, next: { success: 'TR-03B' },
  },
  {
    id: 'TR-03B', groupId: 'TR-03', role: 'CZA_PROBE', title: 'Birden Fazla Kural Bul',
    childInstruction: '“Elma, top, portakal, balon” kelimelerini iki farklı kurala göre gruplandırabilir misin?',
    educatorInstruction: 'Tek doğru arama yerine alternatif sınıflama kuralları üretip üretemediğini gözle.',
    responseModes: ['SPEAK', 'TEXT'], estimatedSeconds: 90,
    skillWeights: [{ skillId: 'cognitive_flexibility', weight: .30 }, { skillId: 'pattern_reasoning', weight: .25 }, { skillId: 'verbal_expression', weight: .20 }, { skillId: 'problem_solving', weight: .15 }, { skillId: 'attention', weight: .10 }],
    rubric: languageRubric, next: { transfer: 'TR-03T' },
  },
  {
    id: 'TR-03T', groupId: 'TR-03', role: 'TRANSFER', title: 'Kuralı Sen Kur',
    childInstruction: 'Bana üç kelime söyle ve onları aynı gruba koyan kuralı sen açıkla.',
    educatorInstruction: 'Kendi örneğini üretme, kural koyma ve gerekçelendirmeyi değerlendir.',
    responseModes: ['SPEAK', 'TEXT'], estimatedSeconds: 75,
    skillWeights: [{ skillId: 'cognitive_flexibility', weight: .30 }, { skillId: 'verbal_expression', weight: .25 }, { skillId: 'pattern_reasoning', weight: .20 }, { skillId: 'problem_solving', weight: .15 }, { skillId: 'self_regulation', weight: .10 }],
    rubric: languageRubric,
  },
  {
    id: 'TR-04A', groupId: 'TR-04', role: 'ACADEMIC_ANCHOR', title: 'Cümleyi Tamamla',
    childInstruction: '“Bugün okulda…” diye başlayan anlamlı bir cümle kur.',
    educatorInstruction: 'Cümle bütünlüğü, sözcük seçimi, dil bilgisel düzen ve bağımsız üretimi gözle.',
    responseModes: ['SPEAK', 'TEXT'], estimatedSeconds: 50,
    skillWeights: [{ skillId: 'written_expression', weight: .40 }, { skillId: 'verbal_expression', weight: .25 }, { skillId: 'self_regulation', weight: .20 }, { skillId: 'working_memory', weight: .15 }],
    rubric: languageRubric, next: { success: 'TR-04B' },
  },
  {
    id: 'TR-04B', groupId: 'TR-04', role: 'CZA_PROBE', title: 'Aynı Fikri Başka Türlü Söyle',
    childInstruction: 'Kurmuş olduğun cümleyi aynı anlamı koruyarak başka türlü söyleyebilir misin?',
    educatorInstruction: 'Sözel esneklik ve anlamı koruyarak yeniden ifade etme becerisini değerlendir.',
    responseModes: ['SPEAK', 'TEXT'], estimatedSeconds: 70,
    skillWeights: [{ skillId: 'cognitive_flexibility', weight: .30 }, { skillId: 'written_expression', weight: .25 }, { skillId: 'verbal_expression', weight: .25 }, { skillId: 'comprehension', weight: .10 }, { skillId: 'self_regulation', weight: .10 }],
    rubric: languageRubric, next: { transfer: 'TR-04T' },
  },
  {
    id: 'TR-04T', groupId: 'TR-04', role: 'TRANSFER', title: 'Üç Cümlelik Mini Hikâye',
    childInstruction: 'İçinde “kapı”, “yağmur” ve “kedi” kelimelerinin geçtiği üç cümlelik minicik bir hikâye kur.',
    educatorInstruction: 'Verilen üç öğeyi anlamlı yapı içinde birleştirme, planlama ve anlatım tutarlılığını değerlendir.',
    responseModes: ['SPEAK', 'TEXT'], estimatedSeconds: 110,
    skillWeights: [{ skillId: 'written_expression', weight: .30 }, { skillId: 'verbal_expression', weight: .20 }, { skillId: 'working_memory', weight: .20 }, { skillId: 'cognitive_flexibility', weight: .20 }, { skillId: 'self_regulation', weight: .10 }],
    rubric: languageRubric,
  },
  {
    id: 'TR-05A', groupId: 'TR-05', role: 'ACADEMIC_ANCHOR', title: 'Yönergeyi Yakala',
    childInstruction: 'Şunu yap: Önce 3 yaz, sonra yanına 5 yaz, en sona bir yıldız işareti koy. Sonucun nasıl göründüğünü yaz ya da söyle.',
    educatorInstruction: 'Yönergeyi tekrar etmeden uygulat. Sıra, atlama ve tekrar ihtiyacını gözle.',
    responseModes: ['TEXT', 'SPEAK'], estimatedSeconds: 45,
    skillWeights: [{ skillId: 'working_memory', weight: .35 }, { skillId: 'attention', weight: .30 }, { skillId: 'self_regulation', weight: .20 }, { skillId: 'processing_speed', weight: .15 }],
    rubric: languageRubric, next: { success: 'TR-05B', support: 'TR-05S' },
  },
  {
    id: 'TR-05S', groupId: 'TR-05', role: 'SUPPORT_PROBE', title: 'İki Adımlı Yönerge',
    childInstruction: 'Önce 3 yaz, sonra yanına 5 yaz.',
    educatorInstruction: 'Yönerge yükünü azaltınca performans değişimini kaydet.',
    responseModes: ['TEXT', 'SPEAK'], estimatedSeconds: 30,
    skillWeights: [{ skillId: 'working_memory', weight: .40 }, { skillId: 'attention', weight: .35 }, { skillId: 'self_regulation', weight: .25 }],
    rubric: languageRubric, next: { success: 'TR-05B' },
  },
  {
    id: 'TR-05B', groupId: 'TR-05', role: 'CZA_PROBE', title: 'Kural Değişti',
    childInstruction: 'Şimdi kuralı değiştiriyorum: Önce yıldız koy, sonra 5, en sona 3 yaz. Eski kurala takılmadan yenisini uygula.',
    educatorInstruction: 'Eski yönergeyi baskılama, yeni kurala geçme ve sıralı belleği birlikte değerlendir.',
    responseModes: ['TEXT', 'SPEAK'], estimatedSeconds: 50,
    skillWeights: [{ skillId: 'attention', weight: .30 }, { skillId: 'working_memory', weight: .30 }, { skillId: 'cognitive_flexibility', weight: .25 }, { skillId: 'self_regulation', weight: .15 }],
    rubric: languageRubric, next: { transfer: 'TR-05T' },
  },
  {
    id: 'TR-05T', groupId: 'TR-05', role: 'TRANSFER', title: 'Yönergeyi Sen Tasarla',
    childInstruction: 'Şimdi bana üç adımlı kısa bir yönerge sen ver. Ben uygulayacakmışım gibi açık ve sıralı anlat.',
    educatorInstruction: 'Kural üretme, sıralama, dil açıklığı ve planlama becerisini değerlendir.',
    responseModes: ['SPEAK', 'TEXT'], estimatedSeconds: 70,
    skillWeights: [{ skillId: 'verbal_expression', weight: .25 }, { skillId: 'self_regulation', weight: .25 }, { skillId: 'working_memory', weight: .20 }, { skillId: 'cognitive_flexibility', weight: .20 }, { skillId: 'attention', weight: .10 }],
    rubric: languageRubric,
  },
];
