import type { AssessmentTask } from './assessment-engine';

const mathRubric = [
  { id: 'accuracy', label: 'Doğruluk', max: 2 },
  { id: 'strategy', label: 'Strateji kalitesi', max: 3 },
  { id: 'explanation', label: 'Düşünceyi açıklama', max: 2 },
  { id: 'independence', label: 'Bağımsızlık', max: 2 },
  { id: 'transfer', label: 'Transfer', max: 3 },
];

export const mathTasks: AssessmentTask[] = [
  {
    id: 'MAT-01A', groupId: 'MAT-01', role: 'ACADEMIC_ANCHOR', title: 'Sayı Dedektifi',
    childInstruction: '47 sayısında kaç onluk ve kaç birlik var?',
    educatorInstruction: 'İlk cevaba müdahale etme. Çocuğun basamak değerini ezberle mi yoksa kavramsal olarak mı kullandığını gözle.',
    responseModes: ['TEXT', 'SPEAK'], estimatedSeconds: 45,
    skillWeights: [{ skillId: 'number_sense', weight: .45 }, { skillId: 'math_reasoning', weight: .30 }, { skillId: 'verbal_expression', weight: .15 }, { skillId: 'working_memory', weight: .10 }],
    rubric: mathRubric, next: { success: 'MAT-01B', support: 'MAT-01S' },
  },
  {
    id: 'MAT-01S', groupId: 'MAT-01', role: 'SUPPORT_PROBE', title: 'Onlukları Görelim',
    childInstruction: '4 tane onluk çubuğu ve 7 tane birlik küpün var. Bu hangi sayıyı gösterir?',
    educatorInstruction: 'Somut temsil ile sembolik basamak değeri arasındaki bağı kontrol et. Destek seviyesini kaydet.',
    responseModes: ['TEXT', 'SPEAK'], estimatedSeconds: 45,
    skillWeights: [{ skillId: 'number_sense', weight: .50 }, { skillId: 'visual_spatial', weight: .25 }, { skillId: 'math_reasoning', weight: .25 }],
    rubric: mathRubric, next: { success: 'MAT-01B' },
  },
  {
    id: 'MAT-01B', groupId: 'MAT-01', role: 'CZA_PROBE', title: 'Aynı Rakamlar, Farklı Değer',
    childInstruction: '47 ile 74 aynı rakamları kullanıyor. Peki neden aynı sayı değiller? Bana kendi sözlerinle anlat.',
    educatorInstruction: 'Basamak değeri, karşılaştırma, sözel gerekçe ve kavramsal açıklamayı birlikte değerlendir.',
    responseModes: ['SPEAK', 'TEXT'], estimatedSeconds: 75,
    skillWeights: [{ skillId: 'number_sense', weight: .30 }, { skillId: 'math_reasoning', weight: .30 }, { skillId: 'verbal_expression', weight: .20 }, { skillId: 'problem_solving', weight: .20 }],
    rubric: mathRubric, next: { transfer: 'MAT-01T' },
  },
  {
    id: 'MAT-01T', groupId: 'MAT-01', role: 'TRANSFER', title: 'Rakamları Değiştir, Değeri Koru',
    childInstruction: '52 sayısını iki farklı şekilde gösterebilir misin? İstersen sayı, çizim ya da gruplar kullan.',
    educatorInstruction: 'Farklı temsil üretimini, transferi ve esnekliği gözle.',
    responseModes: ['SPEAK', 'DRAW', 'TEXT'], estimatedSeconds: 80,
    skillWeights: [{ skillId: 'number_sense', weight: .30 }, { skillId: 'cognitive_flexibility', weight: .25 }, { skillId: 'visual_spatial', weight: .20 }, { skillId: 'problem_solving', weight: .25 }],
    rubric: mathRubric,
  },
  {
    id: 'MAT-02A', groupId: 'MAT-02', role: 'ACADEMIC_ANCHOR', title: 'Hızlı Toplama',
    childInstruction: '8 + 7 kaç eder?',
    educatorInstruction: 'İlk stratejiyi not et: doğrudan hatırlama, sayma, parmak, onluğa tamamlama veya başka yol.',
    responseModes: ['TEXT', 'SPEAK'], estimatedSeconds: 35,
    skillWeights: [{ skillId: 'math_reasoning', weight: .45 }, { skillId: 'processing_speed', weight: .20 }, { skillId: 'working_memory', weight: .20 }, { skillId: 'self_regulation', weight: .15 }],
    rubric: mathRubric, next: { success: 'MAT-02B', support: 'MAT-02S' },
  },
  {
    id: 'MAT-02S', groupId: 'MAT-02', role: 'SUPPORT_PROBE', title: 'Toplamı Görerek Bul',
    childInstruction: '8 nesneye 7 nesne daha ekleniyor. Toplamı bulmak için nasıl bir yol kullanırsın?',
    educatorInstruction: 'Somut toplama kavramı var mı, yoksa sembolik işlem mi zor geliyor ayır.',
    responseModes: ['SPEAK', 'DRAW'], estimatedSeconds: 60,
    skillWeights: [{ skillId: 'math_reasoning', weight: .40 }, { skillId: 'visual_spatial', weight: .25 }, { skillId: 'problem_solving', weight: .20 }, { skillId: 'verbal_expression', weight: .15 }],
    rubric: mathRubric, next: { success: 'MAT-02B' },
  },
  {
    id: 'MAT-02B', groupId: 'MAT-02', role: 'CZA_PROBE', title: '15’e Kaç Yoldan Ulaşırsın?',
    childInstruction: '15 sayısına ulaşmanın mümkün olduğunca farklı yollarını bul. Toplama, çıkarma, gruplama ya da başka bir yol kullanabilirsin.',
    educatorInstruction: 'Doğru sonuçtan çok strateji çeşitliliği, esneklik ve açıklama kalitesini değerlendir.',
    responseModes: ['SPEAK', 'DRAW', 'TEXT'], estimatedSeconds: 100,
    skillWeights: [{ skillId: 'math_reasoning', weight: .25 }, { skillId: 'cognitive_flexibility', weight: .30 }, { skillId: 'problem_solving', weight: .25 }, { skillId: 'verbal_expression', weight: .10 }, { skillId: 'working_memory', weight: .10 }],
    rubric: mathRubric, next: { transfer: 'MAT-02T' },
  },
  {
    id: 'MAT-02T', groupId: 'MAT-02', role: 'TRANSFER', title: 'Bir Üstünü Düşün',
    childInstruction: 'Az önce bulduğun yollardan hangisini 16 sayısına ulaşmak için kullanabilirsin? Neyi değiştirmen gerekir?',
    educatorInstruction: 'Önceki stratejiyi yeni sayıya taşıma ve uyarlama becerisini değerlendir.',
    responseModes: ['SPEAK', 'TEXT'], estimatedSeconds: 70,
    skillWeights: [{ skillId: 'problem_solving', weight: .30 }, { skillId: 'cognitive_flexibility', weight: .30 }, { skillId: 'math_reasoning', weight: .25 }, { skillId: 'verbal_expression', weight: .15 }],
    rubric: mathRubric,
  },
  {
    id: 'MAT-03A', groupId: 'MAT-03', role: 'ACADEMIC_ANCHOR', title: 'Çıkarma Kapısı',
    childInstruction: '14 - 6 kaç eder?',
    educatorInstruction: 'Eksiltme stratejisini izle. Yanlışsa doğrudan sonucu söyleme.',
    responseModes: ['TEXT', 'SPEAK'], estimatedSeconds: 35,
    skillWeights: [{ skillId: 'math_reasoning', weight: .50 }, { skillId: 'working_memory', weight: .20 }, { skillId: 'processing_speed', weight: .15 }, { skillId: 'self_regulation', weight: .15 }],
    rubric: mathRubric, next: { success: 'MAT-03B', support: 'MAT-03S' },
  },
  {
    id: 'MAT-03S', groupId: 'MAT-03', role: 'SUPPORT_PROBE', title: 'Eksiltmeyi Canlandır',
    childInstruction: '14 nesnen var. 6 tanesini ayırırsan kaç tane kalır? İstersen çizerek göster.',
    educatorInstruction: 'Eksiltme kavramı ile sembolik işlemi ayır. Somut modelde başarı varsa sembolik otomatiklik notu düş.',
    responseModes: ['DRAW', 'SPEAK', 'TEXT'], estimatedSeconds: 60,
    skillWeights: [{ skillId: 'math_reasoning', weight: .40 }, { skillId: 'visual_spatial', weight: .25 }, { skillId: 'number_sense', weight: .20 }, { skillId: 'problem_solving', weight: .15 }],
    rubric: mathRubric, next: { success: 'MAT-03B' },
  },
  {
    id: 'MAT-03B', groupId: 'MAT-03', role: 'CZA_PROBE', title: 'Geriye mi, Parçalayarak mı?',
    childInstruction: '14’ten 6 çıkarmayı başka bir yolla da yapabilir misin? Hangi yol sana daha kolay geldi?',
    educatorInstruction: 'Strateji çeşitliliği, metabiliş ve işlemsel esnekliği gözle.',
    responseModes: ['SPEAK', 'TEXT'], estimatedSeconds: 80,
    skillWeights: [{ skillId: 'math_reasoning', weight: .30 }, { skillId: 'cognitive_flexibility', weight: .25 }, { skillId: 'self_regulation', weight: .20 }, { skillId: 'verbal_expression', weight: .15 }, { skillId: 'problem_solving', weight: .10 }],
    rubric: mathRubric, next: { transfer: 'MAT-03T' },
  },
  {
    id: 'MAT-03T', groupId: 'MAT-03', role: 'TRANSFER', title: 'Yeni Sayıda Aynı Fikir',
    childInstruction: '15 - 7 için az önceki yollardan hangisini kullanırdın? Neden?',
    educatorInstruction: 'Strateji transferini ve gerekçeyi değerlendir.',
    responseModes: ['SPEAK', 'TEXT'], estimatedSeconds: 65,
    skillWeights: [{ skillId: 'problem_solving', weight: .30 }, { skillId: 'math_reasoning', weight: .30 }, { skillId: 'cognitive_flexibility', weight: .25 }, { skillId: 'verbal_expression', weight: .15 }],
    rubric: mathRubric,
  },
  {
    id: 'MAT-04A', groupId: 'MAT-04', role: 'ACADEMIC_ANCHOR', title: 'Hangisi Daha Büyük?',
    childInstruction: '36 mı daha büyük, 63 mü?',
    educatorInstruction: 'Sadece doğru seçimi değil, ilk gerekçeyi de kaydet.',
    responseModes: ['TEXT', 'SPEAK'], estimatedSeconds: 30,
    skillWeights: [{ skillId: 'number_sense', weight: .50 }, { skillId: 'math_reasoning', weight: .25 }, { skillId: 'processing_speed', weight: .15 }, { skillId: 'verbal_expression', weight: .10 }],
    rubric: mathRubric, next: { success: 'MAT-04B', support: 'MAT-04S' },
  },
  {
    id: 'MAT-04S', groupId: 'MAT-04', role: 'SUPPORT_PROBE', title: 'Onlukları Karşılaştır',
    childInstruction: '36 sayısında 3 onluk, 63 sayısında 6 onluk var. Hangisi daha büyük olmalı? Neden?',
    educatorInstruction: 'Karşılaştırma stratejisinde onluk değerini kullanıp kullanamadığını kontrol et.',
    responseModes: ['SPEAK', 'TEXT'], estimatedSeconds: 45,
    skillWeights: [{ skillId: 'number_sense', weight: .50 }, { skillId: 'math_reasoning', weight: .30 }, { skillId: 'verbal_expression', weight: .20 }],
    rubric: mathRubric, next: { success: 'MAT-04B' },
  },
  {
    id: 'MAT-04B', groupId: 'MAT-04', role: 'CZA_PROBE', title: 'Sayı Yazmadan Anlat',
    childInstruction: '36 ile 63’ün neden farklı olduğunu hiç sayı yazmadan anlatabilir misin?',
    educatorInstruction: 'Kavramsal açıklama, sözel temsil ve basamak değerini farklı biçimde ifade etme becerisini gözle.',
    responseModes: ['SPEAK', 'DRAW'], estimatedSeconds: 75,
    skillWeights: [{ skillId: 'number_sense', weight: .25 }, { skillId: 'verbal_expression', weight: .25 }, { skillId: 'cognitive_flexibility', weight: .25 }, { skillId: 'visual_spatial', weight: .15 }, { skillId: 'math_reasoning', weight: .10 }],
    rubric: mathRubric, next: { transfer: 'MAT-04T' },
  },
  {
    id: 'MAT-04T', groupId: 'MAT-04', role: 'TRANSFER', title: 'Benzer İkiliyi Sen Kur',
    childInstruction: 'Aynı rakamları kullanan ama değerleri farklı iki sayı sen oluşturabilir misin?',
    educatorInstruction: 'Kuralı genelleyip yeni örnek üretme becerisini değerlendir.',
    responseModes: ['SPEAK', 'TEXT'], estimatedSeconds: 60,
    skillWeights: [{ skillId: 'number_sense', weight: .25 }, { skillId: 'cognitive_flexibility', weight: .30 }, { skillId: 'problem_solving', weight: .20 }, { skillId: 'verbal_expression', weight: .15 }, { skillId: 'math_reasoning', weight: .10 }],
    rubric: mathRubric,
  },
  {
    id: 'MAT-05A', groupId: 'MAT-05', role: 'ACADEMIC_ANCHOR', title: 'Örüntüyü Tamamla',
    childInstruction: '2, 4, 6, 8, ... Sıradaki sayı ne olmalı?',
    educatorInstruction: 'Kuralı nasıl fark ettiğini sor ama ilk cevaptan sonra.',
    responseModes: ['TEXT', 'SPEAK'], estimatedSeconds: 30,
    skillWeights: [{ skillId: 'pattern_reasoning', weight: .50 }, { skillId: 'processing_speed', weight: .20 }, { skillId: 'working_memory', weight: .15 }, { skillId: 'attention', weight: .15 }],
    rubric: mathRubric, next: { success: 'MAT-05B', support: 'MAT-05S' },
  },
  {
    id: 'MAT-05S', groupId: 'MAT-05', role: 'SUPPORT_PROBE', title: 'Kuralı Gör',
    childInstruction: 'Her sayıdan sonra 2 artırıyoruz: 2, 4, 6, 8... Şimdi sıradaki sayıyı bul.',
    educatorInstruction: 'Açık kural verildiğinde uygulama var mı kontrol et; bu öğrenme tepkisi için önemli kanıttır.',
    responseModes: ['TEXT', 'SPEAK'], estimatedSeconds: 35,
    skillWeights: [{ skillId: 'pattern_reasoning', weight: .45 }, { skillId: 'working_memory', weight: .25 }, { skillId: 'attention', weight: .15 }, { skillId: 'self_regulation', weight: .15 }],
    rubric: mathRubric, next: { success: 'MAT-05B' },
  },
  {
    id: 'MAT-05B', groupId: 'MAT-05', role: 'CZA_PROBE', title: 'Kuralı Sen Kur',
    childInstruction: 'Şimdi bana kendi sayı örüntünü kur ve kuralını anlat.',
    educatorInstruction: 'Üretim, kural açıklama ve bilişsel esnekliği değerlendir.',
    responseModes: ['SPEAK', 'TEXT'], estimatedSeconds: 85,
    skillWeights: [{ skillId: 'pattern_reasoning', weight: .30 }, { skillId: 'cognitive_flexibility', weight: .30 }, { skillId: 'verbal_expression', weight: .20 }, { skillId: 'problem_solving', weight: .20 }],
    rubric: mathRubric, next: { transfer: 'MAT-05T' },
  },
  {
    id: 'MAT-05T', groupId: 'MAT-05', role: 'TRANSFER', title: 'Kural Değişti',
    childInstruction: '3, 5, 8, 10, 13... Sence burada neler oluyor? Devam ettirmek için bir kural bulabilir misin?',
    educatorInstruction: 'Tek bir beklenen cevap arama. Hipotez üretme, tutarlılık ve açıklamayı değerlendir.',
    responseModes: ['SPEAK', 'TEXT'], estimatedSeconds: 90,
    skillWeights: [{ skillId: 'pattern_reasoning', weight: .30 }, { skillId: 'cognitive_flexibility', weight: .30 }, { skillId: 'problem_solving', weight: .25 }, { skillId: 'verbal_expression', weight: .15 }],
    rubric: mathRubric,
  },
];

export function allAssessmentTasks(warmupTasks: AssessmentTask[]) {
  return [...warmupTasks, ...mathTasks];
}
