import type { AssessmentTask } from './assessment-engine';

const cognitiveRubric = [
  { id: 'accuracy', label: 'Doğruluk', max: 2 },
  { id: 'speed', label: 'Hız-doğruluk dengesi', max: 2 },
  { id: 'strategy', label: 'Strateji', max: 3 },
  { id: 'independence', label: 'Bağımsızlık', max: 2 },
  { id: 'transfer', label: 'Kural değişimi / transfer', max: 3 },
];

export const cognitiveTasks: AssessmentTask[] = [
  {
    id: 'COG-01A', groupId: 'COG-01', role: 'ACADEMIC_ANCHOR', title: 'Dikkat Avcısı',
    childInstruction: 'Sadece 3 sayılarını say: 3 8 3 5 3 2 8 3. Kaç tane 3 var?',
    educatorInstruction: 'Tarama biçimini, atlama/tekrar hatalarını ve aceleciliği gözle.',
    responseModes: ['TEXT', 'SPEAK'], estimatedSeconds: 35,
    skillWeights: [{ skillId: 'attention', weight: .45 }, { skillId: 'processing_speed', weight: .25 }, { skillId: 'working_memory', weight: .15 }, { skillId: 'self_regulation', weight: .15 }],
    rubric: cognitiveRubric, next: { success: 'COG-01B', support: 'COG-01S' },
  },
  {
    id: 'COG-01S', groupId: 'COG-01', role: 'SUPPORT_PROBE', title: 'Kısa Dikkat Taraması',
    childInstruction: 'Sadece 3 sayılarını say: 3 5 3 2 3. Kaç tane?',
    educatorInstruction: 'Uyaran sayısı azalınca doğruluk artıyor mu kaydet.',
    responseModes: ['TEXT', 'SPEAK'], estimatedSeconds: 25,
    skillWeights: [{ skillId: 'attention', weight: .55 }, { skillId: 'processing_speed', weight: .20 }, { skillId: 'self_regulation', weight: .15 }, { skillId: 'working_memory', weight: .10 }],
    rubric: cognitiveRubric, next: { success: 'COG-01B' },
  },
  {
    id: 'COG-01B', groupId: 'COG-01', role: 'CZA_PROBE', title: 'Hedef Değişti',
    childInstruction: 'Aynı dizide bu kez sadece 8 sayılarını bul. Eski hedef olan 3’leri görmezden gel.',
    educatorInstruction: 'Eski kurala takılma, seçici dikkat ve kural değişimindeki hata örüntüsünü gözle.',
    responseModes: ['TEXT', 'SPEAK'], estimatedSeconds: 35,
    skillWeights: [{ skillId: 'attention', weight: .35 }, { skillId: 'cognitive_flexibility', weight: .30 }, { skillId: 'self_regulation', weight: .20 }, { skillId: 'processing_speed', weight: .15 }],
    rubric: cognitiveRubric, next: { transfer: 'COG-01T' },
  },
  {
    id: 'COG-01T', groupId: 'COG-01', role: 'TRANSFER', title: 'Kuralı Sen Değiştir',
    childInstruction: 'Bu sayı dizisi için yeni bir dikkat kuralı sen oluştur ve bana neyi bulmam gerektiğini söyle.',
    educatorInstruction: 'Kural üretimi, esneklik ve yönerge açıklığını değerlendir.',
    responseModes: ['SPEAK', 'TEXT'], estimatedSeconds: 60,
    skillWeights: [{ skillId: 'cognitive_flexibility', weight: .35 }, { skillId: 'attention', weight: .20 }, { skillId: 'verbal_expression', weight: .20 }, { skillId: 'problem_solving', weight: .15 }, { skillId: 'self_regulation', weight: .10 }],
    rubric: cognitiveRubric,
  },
  {
    id: 'COG-02A', groupId: 'COG-02', role: 'ACADEMIC_ANCHOR', title: 'Kulak Hafızası',
    childInstruction: 'Eğitmenin söyleyeceği üç sayıyı aynı sırayla tekrar et.',
    educatorInstruction: 'Bir kez ve doğal hızda “4 - 1 - 7” söyle. Tekrar etme. Doğru sıra: 4-1-7.',
    responseModes: ['SPEAK', 'TEXT'], estimatedSeconds: 30,
    skillWeights: [{ skillId: 'working_memory', weight: .50 }, { skillId: 'attention', weight: .25 }, { skillId: 'verbal_expression', weight: .10 }, { skillId: 'self_regulation', weight: .15 }],
    rubric: cognitiveRubric, next: { success: 'COG-02B', support: 'COG-02S' },
  },
  {
    id: 'COG-02S', groupId: 'COG-02', role: 'SUPPORT_PROBE', title: 'İki Sayıyı Tut',
    childInstruction: 'Eğitmenin söyleyeceği iki sayıyı aynı sırayla tekrar et.',
    educatorInstruction: 'Bir kez “4 - 7” söyle. Yük azalınca performansı karşılaştır.',
    responseModes: ['SPEAK', 'TEXT'], estimatedSeconds: 25,
    skillWeights: [{ skillId: 'working_memory', weight: .60 }, { skillId: 'attention', weight: .25 }, { skillId: 'self_regulation', weight: .15 }],
    rubric: cognitiveRubric, next: { success: 'COG-02B' },
  },
  {
    id: 'COG-02B', groupId: 'COG-02', role: 'CZA_PROBE', title: 'Zihninde Ters Çevir',
    childInstruction: 'Şimdi eğitmenin söyleyeceği üç sayıyı ters sırayla söyle.',
    educatorInstruction: 'Bir kez “4 - 1 - 7” söyle. Beklenen ters sıra 7-1-4. Bilgiyi tutma ve zihinde dönüştürmeyi ayır.',
    responseModes: ['SPEAK', 'TEXT'], estimatedSeconds: 40,
    skillWeights: [{ skillId: 'working_memory', weight: .45 }, { skillId: 'problem_solving', weight: .20 }, { skillId: 'self_regulation', weight: .20 }, { skillId: 'attention', weight: .15 }],
    rubric: cognitiveRubric, next: { transfer: 'COG-02T' },
  },
  {
    id: 'COG-02T', groupId: 'COG-02', role: 'TRANSFER', title: 'Yeni Dizide Aynı Zihin Oyunu',
    childInstruction: 'Yeni üç sayıyı da ters sırayla söyle.',
    educatorInstruction: 'Bir kez “5 - 2 - 8” söyle. Beklenen 8-2-5. Öğrenilen işlemi yeni diziye transferi değerlendir.',
    responseModes: ['SPEAK', 'TEXT'], estimatedSeconds: 40,
    skillWeights: [{ skillId: 'working_memory', weight: .40 }, { skillId: 'problem_solving', weight: .20 }, { skillId: 'cognitive_flexibility', weight: .20 }, { skillId: 'attention', weight: .10 }, { skillId: 'self_regulation', weight: .10 }],
    rubric: cognitiveRubric,
  },
  {
    id: 'COG-03A', groupId: 'COG-03', role: 'ACADEMIC_ANCHOR', title: 'Sembol Kodu',
    childInstruction: 'Kural: ⭐ gördüğünde 1, 🔵 gördüğünde 2 söyle. Dizi: ⭐ 🔵 🔵 ⭐. Sonuç nedir?',
    educatorInstruction: 'Kuralı akılda tutma, doğru kodlama ve cevap hızını gözle.',
    responseModes: ['TEXT', 'SPEAK'], estimatedSeconds: 35,
    skillWeights: [{ skillId: 'working_memory', weight: .30 }, { skillId: 'attention', weight: .25 }, { skillId: 'processing_speed', weight: .25 }, { skillId: 'pattern_reasoning', weight: .20 }],
    rubric: cognitiveRubric, next: { success: 'COG-03B', support: 'COG-03S' },
  },
  {
    id: 'COG-03S', groupId: 'COG-03', role: 'SUPPORT_PROBE', title: 'Kısa Kod',
    childInstruction: 'Kural aynı: ⭐ = 1, 🔵 = 2. Dizi: ⭐ 🔵. Sonuç nedir?',
    educatorInstruction: 'Dizi kısalınca doğruluk artıyorsa yük etkisini not et.',
    responseModes: ['TEXT', 'SPEAK'], estimatedSeconds: 25,
    skillWeights: [{ skillId: 'working_memory', weight: .35 }, { skillId: 'attention', weight: .30 }, { skillId: 'processing_speed', weight: .20 }, { skillId: 'pattern_reasoning', weight: .15 }],
    rubric: cognitiveRubric, next: { success: 'COG-03B' },
  },
  {
    id: 'COG-03B', groupId: 'COG-03', role: 'CZA_PROBE', title: 'Kodu Tersine Çevir',
    childInstruction: 'Kural değişti: ⭐ artık 2, 🔵 artık 1. Aynı dizi ⭐ 🔵 🔵 ⭐ için sonuç nedir?',
    educatorInstruction: 'Eski kuralı baskılayıp yeni kurala geçişi, hata sonrası öz-düzeltmeyi ve hız-doğruluk dengesini gözle.',
    responseModes: ['TEXT', 'SPEAK'], estimatedSeconds: 45,
    skillWeights: [{ skillId: 'cognitive_flexibility', weight: .30 }, { skillId: 'self_regulation', weight: .25 }, { skillId: 'working_memory', weight: .20 }, { skillId: 'attention', weight: .15 }, { skillId: 'processing_speed', weight: .10 }],
    rubric: cognitiveRubric, next: { transfer: 'COG-03T' },
  },
  {
    id: 'COG-03T', groupId: 'COG-03', role: 'TRANSFER', title: 'Kendi Kodunu Tasarla',
    childInstruction: 'İki sembol seç, ikisine de farklı bir sayı ver ve bana kısa bir kod dizisi hazırla.',
    educatorInstruction: 'Kural üretme, tutarlılık, planlama ve sembolik düşünmeyi değerlendir.',
    responseModes: ['SPEAK', 'TEXT'], estimatedSeconds: 70,
    skillWeights: [{ skillId: 'cognitive_flexibility', weight: .30 }, { skillId: 'pattern_reasoning', weight: .25 }, { skillId: 'problem_solving', weight: .20 }, { skillId: 'self_regulation', weight: .15 }, { skillId: 'verbal_expression', weight: .10 }],
    rubric: cognitiveRubric,
  },
  {
    id: 'COG-04A', groupId: 'COG-04', role: 'ACADEMIC_ANCHOR', title: 'Şekil Sırası',
    childInstruction: 'Dizi: ● ▲ ● ▲ ● ... Sıradaki şekil ne olmalı?',
    educatorInstruction: 'Basit görsel örüntü kuralını ne hızda fark ettiğini gözle.',
    responseModes: ['TEXT', 'SPEAK'], estimatedSeconds: 25,
    skillWeights: [{ skillId: 'visual_spatial', weight: .35 }, { skillId: 'pattern_reasoning', weight: .35 }, { skillId: 'attention', weight: .15 }, { skillId: 'processing_speed', weight: .15 }],
    rubric: cognitiveRubric, next: { success: 'COG-04B', support: 'COG-04S' },
  },
  {
    id: 'COG-04S', groupId: 'COG-04', role: 'SUPPORT_PROBE', title: 'İkili Tekrarı Gör',
    childInstruction: '● ▲ / ● ▲ / ● ... Her iki şekilden sonra aynı sıra tekrar ediyor. Sıradaki hangisi?',
    educatorInstruction: 'Kural sözel ipucuyla belirginleşince performans değişimini kaydet.',
    responseModes: ['TEXT', 'SPEAK'], estimatedSeconds: 25,
    skillWeights: [{ skillId: 'visual_spatial', weight: .35 }, { skillId: 'pattern_reasoning', weight: .35 }, { skillId: 'attention', weight: .20 }, { skillId: 'verbal_expression', weight: .10 }],
    rubric: cognitiveRubric, next: { success: 'COG-04B' },
  },
  {
    id: 'COG-04B', groupId: 'COG-04', role: 'CZA_PROBE', title: 'Kuralı İki Katmanlı Yap',
    childInstruction: 'Şimdi bir örüntü düşün: şekil sırayla değişsin, ama her turda şekil sayısı da artsın. Nasıl bir örnek kurarsın?',
    educatorInstruction: 'İki kuralı aynı anda yönetme, görsel planlama ve özgün örüntü üretimini değerlendir.',
    responseModes: ['SPEAK', 'TEXT', 'DRAW'], estimatedSeconds: 90,
    skillWeights: [{ skillId: 'visual_spatial', weight: .25 }, { skillId: 'pattern_reasoning', weight: .25 }, { skillId: 'cognitive_flexibility', weight: .25 }, { skillId: 'problem_solving', weight: .15 }, { skillId: 'working_memory', weight: .10 }],
    rubric: cognitiveRubric, next: { transfer: 'COG-04T' },
  },
  {
    id: 'COG-04T', groupId: 'COG-04', role: 'TRANSFER', title: 'Başkasının Kuralını Çöz',
    childInstruction: 'Örüntü: ● ▲▲ ●●● ▲▲▲▲ ... Sence sırada ne gelmeli ve neden?',
    educatorInstruction: 'Şekil değişimi ile adet artışını birlikte çıkarıp çıkaramadığını gözle.',
    responseModes: ['SPEAK', 'TEXT'], estimatedSeconds: 60,
    skillWeights: [{ skillId: 'pattern_reasoning', weight: .30 }, { skillId: 'visual_spatial', weight: .25 }, { skillId: 'working_memory', weight: .15 }, { skillId: 'problem_solving', weight: .20 }, { skillId: 'verbal_expression', weight: .10 }],
    rubric: cognitiveRubric,
  },
  {
    id: 'COG-05A', groupId: 'COG-05', role: 'ACADEMIC_ANCHOR', title: 'Üç Adımlı Plan',
    childInstruction: 'Akşam ödevini bitirmen, çantanı hazırlaman ve uyuman gerekiyor. Bunları hangi sırayla yaparsın?',
    educatorInstruction: 'Tek doğru sıra arama. Planın tutarlılığını, başlama kararını ve gerekçeyi gözle.',
    responseModes: ['SPEAK', 'TEXT'], estimatedSeconds: 55,
    skillWeights: [{ skillId: 'self_regulation', weight: .35 }, { skillId: 'problem_solving', weight: .30 }, { skillId: 'verbal_expression', weight: .20 }, { skillId: 'working_memory', weight: .15 }],
    rubric: cognitiveRubric, next: { success: 'COG-05B' },
  },
  {
    id: 'COG-05B', groupId: 'COG-05', role: 'CZA_PROBE', title: 'Plan Bozulursa',
    childInstruction: 'Tam çantanı hazırlarken bir kitabının başka odada olduğunu fark ettin. Planını nasıl değiştirirsin?',
    educatorInstruction: 'Beklenmedik durumda plan güncelleme, esneklik ve önceliklendirmeyi değerlendir.',
    responseModes: ['SPEAK', 'TEXT'], estimatedSeconds: 70,
    skillWeights: [{ skillId: 'self_regulation', weight: .30 }, { skillId: 'problem_solving', weight: .30 }, { skillId: 'cognitive_flexibility', weight: .25 }, { skillId: 'verbal_expression', weight: .15 }],
    rubric: cognitiveRubric, next: { transfer: 'COG-05T' },
  },
  {
    id: 'COG-05T', groupId: 'COG-05', role: 'TRANSFER', title: 'Planı Sen Tasarla',
    childInstruction: 'Yarın sabah okula zamanında çıkmak için üç adımlı kendi planını oluştur. En önemli adımı da söyle.',
    educatorInstruction: 'Plan üretimi, öncelik, zaman farkındalığı ve gerekçelendirmeyi değerlendir.',
    responseModes: ['SPEAK', 'TEXT'], estimatedSeconds: 80,
    skillWeights: [{ skillId: 'self_regulation', weight: .35 }, { skillId: 'problem_solving', weight: .25 }, { skillId: 'verbal_expression', weight: .20 }, { skillId: 'cognitive_flexibility', weight: .10 }, { skillId: 'working_memory', weight: .10 }],
    rubric: cognitiveRubric,
  },
];
