import type { AssessmentTask } from './assessment-engine';

const rubric = [
  { id: 'accuracy', label: 'Doğruluk', max: 2 },
  { id: 'strategy', label: 'Strateji kalitesi', max: 3 },
  { id: 'explanation', label: 'Düşünceyi açıklama', max: 2 },
  { id: 'independence', label: 'Bağımsızlık', max: 2 },
  { id: 'transfer', label: 'Transfer', max: 3 },
];

export const extendedMathTasks: AssessmentTask[] = [
  {
    id: 'MAT-06A', groupId: 'MAT-06', role: 'ACADEMIC_ANCHOR', title: 'Kayıp Sayıyı Bul',
    childInstruction: '7 + ? = 12. Boşluğa hangi sayı gelmeli?',
    educatorInstruction: 'Eksik toplananı nasıl bulduğunu gözle: sayma, geri düşünme, ters işlem veya doğrudan hatırlama.',
    responseModes: ['TEXT', 'SPEAK'], estimatedSeconds: 40,
    skillWeights: [{ skillId: 'math_reasoning', weight: .40 }, { skillId: 'working_memory', weight: .20 }, { skillId: 'problem_solving', weight: .25 }, { skillId: 'processing_speed', weight: .15 }],
    rubric, next: { success: 'MAT-06B', support: 'MAT-06S' },
  },
  {
    id: 'MAT-06S', groupId: 'MAT-06', role: 'SUPPORT_PROBE', title: '12’ye Tamamla',
    childInstruction: '7 nesnen var. 12 olması için kaç nesne daha eklemelisin?',
    educatorInstruction: 'Eşitlik ve eksik parça kavramı somut modelde var mı kontrol et.',
    responseModes: ['TEXT', 'SPEAK', 'DRAW'], estimatedSeconds: 55,
    skillWeights: [{ skillId: 'math_reasoning', weight: .35 }, { skillId: 'number_sense', weight: .25 }, { skillId: 'visual_spatial', weight: .20 }, { skillId: 'problem_solving', weight: .20 }],
    rubric, next: { success: 'MAT-06B' },
  },
  {
    id: 'MAT-06B', groupId: 'MAT-06', role: 'CZA_PROBE', title: 'Eşitliği Sen Kur',
    childInstruction: 'İki tarafı da aynı değerde olan kendi sayı cümleni kurabilir misin? Sonra neden eşit olduğunu anlat.',
    educatorInstruction: 'Eşitlik işaretini “cevap gelir” sembolü değil ilişki olarak anlayıp anlamadığını değerlendir.',
    responseModes: ['TEXT', 'SPEAK'], estimatedSeconds: 80,
    skillWeights: [{ skillId: 'math_reasoning', weight: .30 }, { skillId: 'cognitive_flexibility', weight: .25 }, { skillId: 'verbal_expression', weight: .20 }, { skillId: 'problem_solving', weight: .25 }],
    rubric, next: { transfer: 'MAT-06T' },
  },
  {
    id: 'MAT-06T', groupId: 'MAT-06', role: 'TRANSFER', title: 'Dengeyi Koru',
    childInstruction: '8 + 4 = 6 + ? eşitliğini tamamla. Sonra iki tarafın neden eşit kaldığını anlat.',
    educatorInstruction: 'İlişkisel eşitlik ve transferi değerlendir.',
    responseModes: ['TEXT', 'SPEAK'], estimatedSeconds: 70,
    skillWeights: [{ skillId: 'math_reasoning', weight: .35 }, { skillId: 'working_memory', weight: .20 }, { skillId: 'problem_solving', weight: .25 }, { skillId: 'verbal_expression', weight: .20 }],
    rubric,
  },
  {
    id: 'MAT-07A', groupId: 'MAT-07', role: 'ACADEMIC_ANCHOR', title: 'Kısa Problem',
    childInstruction: 'Ece’nin 9 kalemi vardı. Arkadaşı 4 kalem daha verdi. Ece’nin şimdi kaç kalemi var?',
    educatorInstruction: 'İşlem seçimini, problem dilini anlama ve gereksiz ayrıntı olmadan modeli kurma biçimini gözle.',
    responseModes: ['TEXT', 'SPEAK'], estimatedSeconds: 55,
    skillWeights: [{ skillId: 'problem_solving', weight: .35 }, { skillId: 'comprehension', weight: .20 }, { skillId: 'math_reasoning', weight: .30 }, { skillId: 'working_memory', weight: .15 }],
    rubric, next: { success: 'MAT-07B', support: 'MAT-07S' },
  },
  {
    id: 'MAT-07S', groupId: 'MAT-07', role: 'SUPPORT_PROBE', title: 'Problemi Canlandır',
    childInstruction: 'Önce 9 kalemi düşün. Sonra 4 kalem daha geliyor. Sence kalemler artıyor mu azalıyor mu? Ne yapmalıyız?',
    educatorInstruction: 'Dil anlaması, işlem seçimi ve kavramsal model arasındaki sorunu ayır.',
    responseModes: ['SPEAK', 'DRAW'], estimatedSeconds: 60,
    skillWeights: [{ skillId: 'comprehension', weight: .25 }, { skillId: 'problem_solving', weight: .30 }, { skillId: 'math_reasoning', weight: .25 }, { skillId: 'visual_spatial', weight: .20 }],
    rubric, next: { success: 'MAT-07B' },
  },
  {
    id: 'MAT-07B', groupId: 'MAT-07', role: 'CZA_PROBE', title: 'Birden Fazla Çözüm Yolu',
    childInstruction: '13 cevabını bulmanın iki farklı yolunu gösterebilir misin? Sonra hangisini daha hızlı bulduğunu söyle.',
    educatorInstruction: 'Strateji üretimi, seçim gerekçesi ve metabilişi değerlendir.',
    responseModes: ['TEXT', 'SPEAK', 'DRAW'], estimatedSeconds: 90,
    skillWeights: [{ skillId: 'problem_solving', weight: .30 }, { skillId: 'cognitive_flexibility', weight: .25 }, { skillId: 'math_reasoning', weight: .25 }, { skillId: 'self_regulation', weight: .10 }, { skillId: 'verbal_expression', weight: .10 }],
    rubric, next: { transfer: 'MAT-07T' },
  },
  {
    id: 'MAT-07T', groupId: 'MAT-07', role: 'TRANSFER', title: 'Problemi Sen Değiştir',
    childInstruction: 'Bu problemi cevabı 14 olacak şekilde değiştirebilir misin? İstersen sayıları ya da hikâyeyi değiştir.',
    educatorInstruction: 'Problem yapısını anlama, tersine kurma ve yaratıcı transferi değerlendir.',
    responseModes: ['SPEAK', 'TEXT'], estimatedSeconds: 90,
    skillWeights: [{ skillId: 'problem_solving', weight: .30 }, { skillId: 'cognitive_flexibility', weight: .30 }, { skillId: 'math_reasoning', weight: .20 }, { skillId: 'verbal_expression', weight: .20 }],
    rubric,
  },
  {
    id: 'MAT-08A', groupId: 'MAT-08', role: 'ACADEMIC_ANCHOR', title: 'Şekli Tanı',
    childInstruction: 'Bir karenin kaç köşesi vardır?',
    educatorInstruction: 'Temel şekil bilgisini ve doğrudan hatırlamayı gözle.',
    responseModes: ['TEXT', 'SPEAK'], estimatedSeconds: 25,
    skillWeights: [{ skillId: 'visual_spatial', weight: .45 }, { skillId: 'processing_speed', weight: .20 }, { skillId: 'attention', weight: .20 }, { skillId: 'verbal_expression', weight: .15 }],
    rubric, next: { success: 'MAT-08B', support: 'MAT-08S' },
  },
  {
    id: 'MAT-08S', groupId: 'MAT-08', role: 'SUPPORT_PROBE', title: 'Köşeleri İzle',
    childInstruction: 'Bir kare çiz ve parmağınla köşelerini tek tek göster. Kaç tane buldun?',
    educatorInstruction: 'Bilgi eksikliği ile görsel tarama/şekil temsilini ayır.',
    responseModes: ['DRAW', 'SPEAK', 'TEXT'], estimatedSeconds: 45,
    skillWeights: [{ skillId: 'visual_spatial', weight: .50 }, { skillId: 'attention', weight: .25 }, { skillId: 'self_regulation', weight: .15 }, { skillId: 'verbal_expression', weight: .10 }],
    rubric, next: { success: 'MAT-08B' },
  },
  {
    id: 'MAT-08B', groupId: 'MAT-08', role: 'CZA_PROBE', title: 'Şekli Dönüştür',
    childInstruction: 'İki aynı kareyi yan yana birleştirirsen dışarıdan hangi şekle benzeyebilir? Çizerek ya da anlatarak göster.',
    educatorInstruction: 'Parça-bütün, zihinsel birleştirme, uzamsal temsil ve açıklamayı değerlendir.',
    responseModes: ['DRAW', 'SPEAK'], estimatedSeconds: 80,
    skillWeights: [{ skillId: 'visual_spatial', weight: .40 }, { skillId: 'problem_solving', weight: .20 }, { skillId: 'cognitive_flexibility', weight: .25 }, { skillId: 'verbal_expression', weight: .15 }],
    rubric, next: { transfer: 'MAT-08T' },
  },
  {
    id: 'MAT-08T', groupId: 'MAT-08', role: 'TRANSFER', title: 'Parçalardan Yeni Şekil',
    childInstruction: 'Üç kareyi kullanarak kaç farklı şekil oluşturabileceğini düşün. En az iki farklı düzen göster.',
    educatorInstruction: 'Uzamsal esneklik, sistematik arama ve özgün düzen üretimini değerlendir.',
    responseModes: ['DRAW', 'SPEAK'], estimatedSeconds: 100,
    skillWeights: [{ skillId: 'visual_spatial', weight: .35 }, { skillId: 'cognitive_flexibility', weight: .30 }, { skillId: 'problem_solving', weight: .25 }, { skillId: 'self_regulation', weight: .10 }],
    rubric,
  },
];
