import { createHash } from 'node:crypto';
import {
  BOOK_PREPARATION_MODULE_VERSION,
  BOOK_PREPARATION_SCHEMA_VERSION,
  deepFreezeBookValue,
  SYNTHETIC_BOOK_DRAFT,
  type BookBlockKind,
  type BookContentBlock,
  type BookDifficulty,
  type BookDraftInput,
  type BookTargetWpm,
  type ServerVerifiedBookContentSummary,
} from './book-preparation-core';

const DIFFICULTIES = new Set<BookDifficulty>([
  'foundation',
  'developing',
  'advanced',
]);
const BLOCK_KINDS = new Set<BookBlockKind>(['heading', 'paragraph']);
const BLOCK_ID_PATTERN = /^block-[a-z0-9](?:[a-z0-9-]{0,39})$/;
const HASH_PATTERN = /^[0-9a-f]{64}$/;
const UUID_PATTERN =
  /^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
const IDEMPOTENCY_KEY_PATTERN = UUID_PATTERN;
const HTML_TAG_PATTERN = /<\/?[a-z][^>]*>/iu;
const MAX_TOTAL_TEXT_BYTES = 20_000;

type PlainObject = Record<string, unknown>;

export class BookPreparationError extends Error {
  constructor(
    public readonly code: string,
    public readonly status = 400,
  ) {
    super(code);
    this.name = 'BookPreparationError';
  }
}

export type ServerOwnedBookDraftIdentity = Readonly<{
  draft_id: string;
  academy_id: string;
  educator_id: string;
}>;

export type AuthenticatedBookDraftOwner = Readonly<{
  academy_id: string;
  educator_id: string;
}>;

export type BookDraftStatus = 'draft' | 'review' | 'published';

export type BookDraftRevision = Readonly<
  ServerOwnedBookDraftIdentity & {
    version: number;
    revision_id: string;
    previous_revision_id: string | null;
    status: BookDraftStatus;
    etag: string;
    content_hash: string;
    created_at: string;
  }
>;

export type BookDraftAuditEvent = Readonly<
  ServerOwnedBookDraftIdentity & {
    audit_event_id: string;
    revision_id: string;
    action: 'created' | 'revised' | 'submitted' | 'returned' | 'published';
    created_at: string;
  }
>;

export type BookDraftWriteResult = Readonly<{
  revision: BookDraftRevision;
  audit_event: BookDraftAuditEvent;
  replayed: boolean;
}>;

export type CreateBookDraftCommand = Readonly<{
  owner: AuthenticatedBookDraftOwner;
  idempotency_key: string;
  untrusted_draft: unknown;
}>;

export type UpdateBookDraftCommand = Readonly<{
  identity: ServerOwnedBookDraftIdentity;
  expected_version: number;
  expected_etag: string;
  expected_status: BookDraftStatus;
  target_status: BookDraftStatus;
  untrusted_draft: unknown;
}>;

export type PreparedBookDraftCreate = Readonly<{
  owner: AuthenticatedBookDraftOwner;
  idempotency_key: string;
  audit_action: 'created';
  summary: ServerVerifiedBookContentSummary;
}>;

export type PreparedBookDraftUpdate = Readonly<{
  identity: ServerOwnedBookDraftIdentity;
  expected_version: number;
  expected_etag: string;
  expected_status: BookDraftStatus;
  target_status: BookDraftStatus;
  audit_action: BookDraftAuditEvent['action'];
  summary: ServerVerifiedBookContentSummary;
}>;

export class BookDraftOptimisticConflictError extends Error {
  readonly code = 'book_draft_version_conflict';
  readonly status = 409;

  constructor() {
    super('book_draft_version_conflict');
    this.name = 'BookDraftOptimisticConflictError';
  }
}

export class BookDraftIdempotencyConflictError extends Error {
  readonly code = 'book_draft_idempotency_conflict';
  readonly status = 409;

  constructor() {
    super('book_draft_idempotency_conflict');
    this.name = 'BookDraftIdempotencyConflictError';
  }
}

export class BookDraftStatusConflictError extends Error {
  readonly code = 'book_draft_status_conflict';
  readonly status = 409;

  constructor() {
    super('book_draft_status_conflict');
    this.name = 'BookDraftStatusConflictError';
  }
}

/**
 * Future persistence boundary; this preview module provides no DB adapter.
 *
 * Required adapter rules:
 * - `draft_id` is generated by the server. `academy_id` and `educator_id` are
 *   derived from the authenticated educator principal, never from request JSON.
 * - public commands accept only `untrusted_draft`; both create and update run
 *   normalizeBookDraft/hash calculation before the adapter sees the content.
 *   A client-cast ServerVerifiedBookContentSummary is never accepted directly.
 * - create starts at `version = 1`, status `draft`, and generates both the
 *   `draft_id`, `revision_id`, and ETag on the server inside one transaction.
 * - the database must enforce UNIQUE(academy_id, educator_id, idempotency_key)
 *   and UNIQUE(draft_id, version). A duplicate create with the same normalized
 *   content hash returns the original result with `replayed = true`; reuse with
 *   a different hash throws BookDraftIdempotencyConflictError (HTTP 409).
 * - update must atomically match `draft_id`, `academy_id`, `educator_id`,
 *   `expected_version`, `expected_etag`, and `expected_status`, then increment
 *   the version once. State changes must pass assertBookDraftStatusTransition.
 * - an update affecting zero rows must throw BookDraftOptimisticConflictError
 *   and map to HTTP 409; blind overwrite and last-write-wins are forbidden.
 * - every successful write appends a new immutable revision and audit event in
 *   the same transaction. Existing revision/audit rows may never be updated or
 *   deleted; publishing does not rewrite prior content.
 */
export abstract class BookDraftPersistenceContract {
  async createServerOwnedDraft(
    command: CreateBookDraftCommand,
  ): Promise<BookDraftWriteResult> {
    const prepared = deepFreezeBookValue({
      owner: validatedOwner(command.owner),
      idempotency_key: validatedIdempotencyKey(command.idempotency_key),
      audit_action: 'created' as const,
      summary: buildServerVerifiedContentSummary(command.untrusted_draft),
    });
    return this.createRevisionTransactionally(prepared);
  }

  async updateOwnedDraft(
    command: UpdateBookDraftCommand,
  ): Promise<BookDraftWriteResult> {
    const identity = validatedIdentity(command.identity);
    if (
      !Number.isSafeInteger(command.expected_version) ||
      command.expected_version < 1 ||
      !HASH_PATTERN.test(command.expected_etag)
    ) {
      fail('book_draft_revision_invalid');
    }
    assertBookDraftStatusTransition(
      command.expected_status,
      command.target_status,
    );
    const prepared = deepFreezeBookValue({
      identity,
      expected_version: command.expected_version,
      expected_etag: command.expected_etag,
      expected_status: command.expected_status,
      target_status: command.target_status,
      audit_action: bookDraftAuditAction(
        command.expected_status,
        command.target_status,
      ),
      summary: buildServerVerifiedContentSummary(command.untrusted_draft),
    });
    return this.updateRevisionTransactionally(prepared);
  }

  protected abstract createRevisionTransactionally(
    command: PreparedBookDraftCreate,
  ): Promise<BookDraftWriteResult>;

  protected abstract updateRevisionTransactionally(
    command: PreparedBookDraftUpdate,
  ): Promise<BookDraftWriteResult>;
}

function validatedOwner(owner: AuthenticatedBookDraftOwner) {
  if (
    !owner ||
    !UUID_PATTERN.test(owner.academy_id) ||
    !UUID_PATTERN.test(owner.educator_id)
  ) {
    fail('book_draft_owner_invalid');
  }
  return deepFreezeBookValue({
    academy_id: owner.academy_id.toLowerCase(),
    educator_id: owner.educator_id.toLowerCase(),
  });
}

function validatedIdentity(identity: ServerOwnedBookDraftIdentity) {
  if (!identity || !UUID_PATTERN.test(identity.draft_id)) {
    fail('book_draft_identity_invalid');
  }
  return deepFreezeBookValue({
    ...validatedOwner(identity),
    draft_id: identity.draft_id.toLowerCase(),
  });
}

function validatedIdempotencyKey(value: string) {
  if (typeof value !== 'string' || !IDEMPOTENCY_KEY_PATTERN.test(value)) {
    fail('book_draft_idempotency_key_invalid');
  }
  return value.toLowerCase();
}

export function assertBookDraftStatusTransition(
  current: BookDraftStatus,
  target: BookDraftStatus,
) {
  const allowed =
    (current === 'draft' && (target === 'draft' || target === 'review')) ||
    (current === 'review' && (target === 'draft' || target === 'published'));
  if (!allowed) throw new BookDraftStatusConflictError();
}

function bookDraftAuditAction(
  current: BookDraftStatus,
  target: BookDraftStatus,
): BookDraftAuditEvent['action'] {
  if (current === 'draft' && target === 'draft') return 'revised';
  if (current === 'draft' && target === 'review') return 'submitted';
  if (current === 'review' && target === 'draft') return 'returned';
  if (current === 'review' && target === 'published') return 'published';
  throw new BookDraftStatusConflictError();
}

export function buildBookDraftEtag(
  identity: ServerOwnedBookDraftIdentity,
  version: number,
  contentHash: string,
) {
  if (
    !UUID_PATTERN.test(identity.draft_id) ||
    !UUID_PATTERN.test(identity.academy_id) ||
    !UUID_PATTERN.test(identity.educator_id) ||
    !Number.isSafeInteger(version) ||
    version < 1 ||
    !HASH_PATTERN.test(contentHash)
  ) {
    fail('book_draft_revision_invalid');
  }
  return createHash('sha256')
    .update(
      [
        identity.draft_id.toLowerCase(),
        identity.academy_id.toLowerCase(),
        identity.educator_id.toLowerCase(),
        String(version),
        contentHash,
      ].join('\u0000'),
      'utf8',
    )
    .digest('hex');
}

function fail(code: string): never {
  throw new BookPreparationError(code);
}

function plainObject(value: unknown): value is PlainObject {
  if (!value || typeof value !== 'object' || Array.isArray(value)) return false;
  const prototype = Object.getPrototypeOf(value);
  return prototype === Object.prototype || prototype === null;
}

function exactFields(
  value: PlainObject,
  required: readonly string[],
  code: string,
) {
  const allowed = new Set(required);
  if (
    Object.keys(value).some((key) => !allowed.has(key)) ||
    required.some((key) => !Object.hasOwn(value, key))
  ) {
    fail(code);
  }
}

function hasUnsafeControlCharacter(value: string) {
  for (const character of value) {
    const codePoint = character.codePointAt(0) as number;
    if (
      codePoint <= 8 ||
      codePoint === 11 ||
      codePoint === 12 ||
      (codePoint >= 14 && codePoint <= 31) ||
      codePoint === 127 ||
      (codePoint >= 0x202a && codePoint <= 0x202e) ||
      (codePoint >= 0x2066 && codePoint <= 0x2069)
    ) {
      return true;
    }
  }
  return false;
}

function normalizedText(value: unknown, maximum: number, code: string) {
  if (typeof value !== 'string') fail(code);
  const normalized = value
    .normalize('NFC')
    .replace(/\r\n?/g, '\n')
    .replace(/[\t ]+/g, ' ')
    .trim();
  if (
    !normalized ||
    normalized.length > maximum ||
    hasUnsafeControlCharacter(normalized) ||
    HTML_TAG_PATTERN.test(normalized)
  ) {
    fail(code);
  }
  return normalized;
}

function boundedInteger(
  value: unknown,
  minimum: number,
  maximum: number,
  code: string,
) {
  if (
    !Number.isInteger(value) ||
    Number(value) < minimum ||
    Number(value) > maximum
  ) {
    fail(code);
  }
  return Number(value);
}

function normalizedWpm(value: unknown): BookTargetWpm {
  if (!plainObject(value)) fail('book_target_wpm_invalid');
  exactFields(
    value,
    ['minimum', 'preferred', 'maximum'],
    'book_target_wpm_invalid',
  );
  const targetWpm = {
    minimum: boundedInteger(value.minimum, 40, 600, 'book_target_wpm_invalid'),
    preferred: boundedInteger(
      value.preferred,
      40,
      700,
      'book_target_wpm_invalid',
    ),
    maximum: boundedInteger(value.maximum, 40, 800, 'book_target_wpm_invalid'),
  };
  if (
    targetWpm.minimum > targetWpm.preferred ||
    targetWpm.preferred > targetWpm.maximum
  ) {
    fail('book_target_wpm_order_invalid');
  }
  return targetWpm;
}

function normalizedBlocks(value: unknown): BookContentBlock[] {
  if (!Array.isArray(value) || value.length < 1 || value.length > 50) {
    fail('book_blocks_invalid');
  }
  const identifiers = new Set<string>();
  const blocks = value.map((candidate) => {
    if (!plainObject(candidate)) fail('book_block_invalid');
    exactFields(
      candidate,
      ['clientBlockId', 'kind', 'text'],
      'book_block_invalid',
    );
    const clientBlockId = normalizedText(
      candidate.clientBlockId,
      48,
      'book_block_id_invalid',
    );
    if (
      identifiers.has(clientBlockId) ||
      !BLOCK_ID_PATTERN.test(clientBlockId)
    ) {
      fail('book_block_id_invalid');
    }
    identifiers.add(clientBlockId);
    if (
      typeof candidate.kind !== 'string' ||
      !BLOCK_KINDS.has(candidate.kind as BookBlockKind)
    ) {
      fail('book_block_kind_invalid');
    }
    return {
      clientBlockId,
      kind: candidate.kind as BookBlockKind,
      text: normalizedText(candidate.text, 4_000, 'book_block_text_invalid'),
    };
  });
  const byteLength = Buffer.byteLength(
    blocks.map((block) => block.text).join('\n'),
    'utf8',
  );
  if (byteLength > MAX_TOTAL_TEXT_BYTES) fail('book_text_too_large');
  return blocks;
}

export function normalizeBookDraft(value: unknown): BookDraftInput {
  if (!plainObject(value)) fail('book_draft_invalid');
  exactFields(
    value,
    ['title', 'language', 'difficulty', 'targetWpm', 'blocks'],
    'book_draft_invalid',
  );
  if (value.language !== 'tr-TR') fail('book_language_invalid');
  if (
    typeof value.difficulty !== 'string' ||
    !DIFFICULTIES.has(value.difficulty as BookDifficulty)
  ) {
    fail('book_difficulty_invalid');
  }
  return deepFreezeBookValue({
    title: normalizedText(value.title, 120, 'book_title_invalid'),
    language: 'tr-TR',
    difficulty: value.difficulty as BookDifficulty,
    targetWpm: normalizedWpm(value.targetWpm),
    blocks: normalizedBlocks(value.blocks),
  });
}

function canonicalBookPayload(draft: BookDraftInput) {
  return JSON.stringify({
    schemaVersion: BOOK_PREPARATION_SCHEMA_VERSION,
    moduleVersion: BOOK_PREPARATION_MODULE_VERSION,
    title: draft.title,
    language: draft.language,
    difficulty: draft.difficulty,
    targetWpm: draft.targetWpm,
    blocks: draft.blocks,
  });
}

export function buildServerVerifiedContentSummary(
  value: unknown,
): ServerVerifiedBookContentSummary {
  const draft = normalizeBookDraft(value);
  const contentHash = createHash('sha256')
    .update(canonicalBookPayload(draft), 'utf8')
    .digest('hex');
  if (!HASH_PATTERN.test(contentHash)) fail('book_hash_invalid');
  const wordCount = draft.blocks.reduce(
    (total, block) => total + block.text.split(/\s+/u).filter(Boolean).length,
    0,
  );
  return deepFreezeBookValue({
    schemaVersion: BOOK_PREPARATION_SCHEMA_VERSION,
    moduleVersion: BOOK_PREPARATION_MODULE_VERSION,
    summaryType: 'server_verified_content_summary',
    serverValidated: true,
    persistenceEnabled: false,
    productionLedgerEligible: false,
    contentHash,
    wordCount,
    approximateReadingSeconds: Math.max(
      1,
      Math.ceil((wordCount * 60) / draft.targetWpm.preferred),
    ),
    draft,
  });
}

export const SYNTHETIC_BOOK_CONTENT_SUMMARY =
  buildServerVerifiedContentSummary(SYNTHETIC_BOOK_DRAFT);
