import { useMemo, useState } from 'react';
import { api } from '@appdeploy/client';
import EarlyDevelopmentCaregiverForm,{type CaregiverState} from './EarlyDevelopmentCaregiverForm';
import EarlyDevelopmentCaregiverV4 from './EarlyDevelopmentCaregiverV4';
import EarlyDevelopmentChildExercises from './EarlyDevelopmentChildExercises';
import EarlyDevelopmentChildExercisesV5 from './EarlyDevelopmentChildExercisesV5';
import EarlyDevelopmentChildCenterV6 from './EarlyDevelopmentChildCenterV6';
import EarlyDevelopmentChildCenterV7 from './EarlyDevelopmentChildCenterV7';

export type EarlyRating='independent'|'prompted'|'verbal_prompt'|'visual_prompt'|'modeled'|'physical_assist'|'not_observed'|'not_assessed';
export type EarlyResponse={itemId:string;rating:EarlyRating;note?:string;metrics?:Record<string,number>;recordedAt:string};
export type EarlyDevelopmentState={version:'E2-v1'|'E2-v2'|'E2-v3'|'E2-v4'|'E2-v5'|'E2-v6'|'E2-v7';responses:EarlyResponse[];startedAt:string;adaptiveProfile?:{languageLevel:'single_word'|'two_word'|'short_sentence';interests:Array<'animals'|'vehicles'|'kitchen'|'outdoor'>;attentionSpan:'short'|'medium'|'long';developmentalNote?:string;configuredAt:string;previousCategoryPerformance?:Record<string,number>};adaptiveSectionsCompleted?:string[];childCompletedAt?:string;caregiver?:CaregiverState;completedAt?:string};

type EarlyItem = {
  id: string;
  station: string;
  title: string;
  instruction: string;
  material: string;
  observe: string;
  minAgeMonths?: number;
  precursor?: boolean;
  v3Only?:boolean;
  metrics?:string[];
};

const legacyItemIds = new Set([
  'RL1','RL2','RL3','RL4','RL5','RL6','EL1','EL2','EL3','EL4','EL5','EL6','JA1','JA2','JA3','JA4','JA5',
  'IM1','IM2','IM3','PL1','PL2','PL3','CO1','CO2','CO3','ME1','ME2','AT1','AT2','VM1','VM2','GM1','GM2','AD1','AD2',
]);

const items: EarlyItem[] = [
  { id: 'RL1', station: '1 · Alıcı Dil', title: 'Tanıdık nesneyi bul', instruction: 'Önüne 3 tanıdık nesne koy. “Topu bana ver.” de.', material: 'Top + iki tanıdık nesne', observe: 'Sözcüğü anlayıp doğru nesneye yönelmesi; tekrar veya jest gerekip gerekmediği.' },
  { id: 'RL2', station: '1 · Alıcı Dil', title: 'Beden bölümünü göster', instruction: '“Burnunu göster.” Sonra farklı bir beden bölümü iste.', material: 'Ek materyal gerekmez', observe: 'Sözel yönergeyi görsel model olmadan anlaması.' },
  { id: 'RL3', station: '1 · Alıcı Dil', title: 'Eylemi anla', instruction: 'İki resim/oyuncak eylemi göster. “Uyuyanı göster.” de.', material: 'İki eylem resmi veya oyuncak sahnesi', observe: 'Nesne adından bağımsız olarak eylem sözcüğünü ayırt etmesi.' },
  { id: 'RL4', station: '1 · Alıcı Dil', title: 'Tek aşamalı nesneli yönerge', instruction: '“Bebeği yatağa koy.” gibi tek eylemli bir yönerge ver.', material: 'Bebek ve küçük yatak/kutu', observe: 'Sözel yönergeyi sürdürmesi ve eylemi tamamlaması.' },
  { id: 'RL5', station: '1 · Alıcı Dil', title: 'Yer kavramı', instruction: '“Arabayı kutunun içine koy.” de. Sonra “üstüne koy” ile yeni örnek dene.', material: 'Araba + kutu', observe: 'Yer bildiren sözcüğü nesne ve eylemle birleştirmesi.', precursor: true },
  { id: 'RL6', station: '1 · Alıcı Dil', title: 'İki bağlantılı adım', instruction: '“Topu al ve kutuya koy.” de; tek sefer söyle.', material: 'Top + kutu', observe: 'İki bağlantılı bilgiyi akılda tutup sırayla uygulaması.', minAgeMonths: 30 },

  { id: 'EL1', station: '2 · İfade Edici Dil', title: 'İstek başlatma', instruction: 'Sevdiği bir nesneyi görünür ama erişemeyeceği yere koy. Bir süre bekle.', material: 'Tercih edilen oyuncak/nesne', observe: 'Bakış, işaret, ses, sözcük veya sözcük birleşimiyle isteği kendiliğinden başlatması.' },
  { id: 'EL2', station: '2 · İfade Edici Dil', title: 'Tanıdık nesneyi adlandırma', instruction: 'Tanıdık 3 nesneyi sırayla göster ve “Bu ne?” diye sor.', material: 'Top, kaşık, araba gibi nesneler', observe: 'Kendiliğinden adlandırma; yaklaşık sesletim varsa anlaşılabilirliği ayrıca not et.' },
  { id: 'EL3', station: '2 · İfade Edici Dil', title: 'Eylemi adlandırma', instruction: 'Bir oyuncak bebeği uyut veya yedir. “Bebek ne yapıyor?” diye sor.', material: 'Bebek + kaşık/yatak', observe: 'Eylem sözcüğü kullanımı; yalnız nesne adıyla kalıp kalmadığı.' },
  { id: 'EL4', station: '2 · İfade Edici Dil', title: 'İki sözcüğü birleştirme fırsatı', instruction: '“Kırmızı araba”, “anne geldi” gibi iki bilgiyi gerektiren doğal bir oyun fırsatı oluştur.', material: 'İki özellik/eylem içeren oyuncak sahnesi', observe: 'İki sözcüğü kendiliğinden birleştirip birleştirmediği; model sonrası üretim.', minAgeMonths: 30 },
  { id: 'EL5', station: '2 · İfade Edici Dil', title: 'Basit soruya yanıt', instruction: 'Tanıdık bir sahnede “Nerede?” veya “Ne yapıyor?” sorusu sor.', material: 'Basit oyun sahnesi', observe: 'Soruyla ilişkili sözel/jest yanıt ve ek ipucu gereksinimi.' },
  { id: 'EL6', station: '2 · İfade Edici Dil', title: 'Bir şeyi paylaşarak anlatma', instruction: 'İlginç bir oyuncak/olay oluştur ve çocuğun bunu sana göstermesi veya hakkında bir şey söylemesi için bekle.', material: 'Basit ilgi çekici oyuncak', observe: 'Yalnız istemek için değil, paylaşmak/yorumlamak için iletişim kurması.' },

  { id: 'JA1', station: '3 · Ortak Dikkat ve Sosyal İletişim', title: 'İşaret edilen hedefi takip et', instruction: 'Yakındaki bir nesneyi yalnız işaret ederek “Bak!” de.', material: 'İlgi çekici nesne', observe: 'Parmağa değil hedefe yönelmesi; bakışını yetişkinle tekrar paylaşması.' },
  { id: 'JA2', station: '3 · Ortak Dikkat ve Sosyal İletişim', title: 'Gösterme ve paylaşma', instruction: 'Çocuğun ilgilendiği bir nesnede bekle. Sana göstermesi için doğrudan istemeden fırsat ver.', material: 'İlgi çekici oyuncak', observe: 'Nesneyi sana gösterme, getirme veya bakışla paylaşma davranışı.' },
  { id: 'JA3', station: '3 · Ortak Dikkat ve Sosyal İletişim', title: 'Bakış değişimi', instruction: 'Birlikte oynarken kısa süre dur ve nesne-yetişkin arasında bakış değişimini gözle.', material: 'Ortak oyun oyuncağı', observe: 'Nesne ile yetişkin arasında dikkati koordine etmesi.' },
  { id: 'JA4', station: '3 · Ortak Dikkat ve Sosyal İletişim', title: 'İletişimi kendisi başlatıyor mu?', instruction: 'İstediği bir nesneyi kapalı şeffaf kutuya koy. Bekle.', material: 'Şeffaf kutu + tercih edilen nesne', observe: 'Yardım istemek için bakış, işaret, ses veya sözcükle yetişkine yönelmesi.' },
  { id: 'JA5', station: '3 · Ortak Dikkat ve Sosyal İletişim', title: 'Kısa sıra alma oyunu', instruction: 'Topu sırayla birbirinize yuvarlayın; birkaç tur sürdür.', material: 'Top', observe: 'Sırasını bekleme, karşı tarafa yönelme ve ortak etkinliği sürdürme.' },

  { id: 'IM1', station: '4 · Taklit ve Oyun', title: 'Motor hareket taklidi', instruction: 'Alkışla, masaya vur veya ellerini başına koy. “Sen de yap.” de.', material: 'Ek materyal gerekmez', observe: 'Hareketi model sonrası kopyalama; gecikme veya ek fiziksel yardım gereksinimi.' },
  { id: 'IM2', station: '4 · Taklit ve Oyun', title: 'Nesneli taklit', instruction: 'Bebeğe kaşıkla yemek ver. Sonra kaşığı çocuğa uzat.', material: 'Bebek + kaşık', observe: 'Nesneyle yapılan eylemi taklit edip oyuna taşıması.' },
  { id: 'IM3', station: '4 · Taklit ve Oyun', title: 'Ses / sözcük taklidi', instruction: 'Oyuna uygun kısa bir ses veya kolay sözcük modeli ver; tekrar etmesi için bekle.', material: 'Oyuncak hayvan/araba kullanılabilir', observe: 'Sözel modeli taklit etme isteği ve üretimin anlaşılabilirliği.' },
  { id: 'PL1', station: '4 · Taklit ve Oyun', title: 'İşlevsel oyun', instruction: 'Araba, fincan, kaşık gibi tanıdık oyuncakları serbestçe sun.', material: '3 işlevsel oyuncak', observe: 'Nesneyi amacına uygun kullanma ve oyunu kendiliğinden başlatma.' },
  { id: 'PL2', station: '4 · Taklit ve Oyun', title: 'Mış gibi oyun', instruction: 'Bebek ve günlük yaşam oyuncaklarını ver; kısa süre yönlendirmeden bekle.', material: 'Bebek + fincan/kaşık/örtü', observe: 'Besleme, uyutma, içiyormuş gibi yapma gibi sembolik kullanım.' },
  { id: 'PL3', station: '4 · Taklit ve Oyun', title: 'İki eylemi oyun içinde bağla', instruction: 'Oyunda iki bağlantılı eylem için fırsat oluştur: bebeği besle sonra yatır gibi.', material: 'Bebek oyun seti', observe: 'İki oyun eylemini ardışık kurma; model sonrası yeni sırayı sürdürme.', minAgeMonths: 30, precursor: true },

  { id: 'CO1', station: '5 · Akademik Öncüller · Eşleme, Sınıflama ve Nicelik', title: 'Eşini bul', instruction: 'İki aynı, bir farklı nesne/şekil sun. Aynı olanları eşleştirmesini iste.', material: 'Basit eşleme kartları veya nesneler', observe: 'Görsel benzerliği fark edip eşleştirme stratejisi.', precursor: true },
  { id: 'MX1', station: '5 · Akademik Öncüller · Eşleme, Sınıflama ve Nicelik', title: 'Nesneyi resmine eşleştir', instruction: 'Gerçek bir kaşık veya topu, iki farklı resim arasındaki kendi resmiyle eşleştirmesini iste.', material: '1 gerçek nesne + 2 net fotoğraf/kart', observe: 'Gerçek nesne ile iki boyutlu temsil arasındaki ilişkiyi kurması.', precursor: true },
  { id: 'MX2', station: '5 · Akademik Öncüller · Eşleme, Sınıflama ve Nicelik', title: 'Aynı mı farklı mı?', instruction: 'İki aynı blok ve belirgin biçimde farklı bir üçüncü nesne koy. Aynı olan ikisini birlikte vermesini iste.', material: '2 aynı + 1 farklı nesne', observe: 'Benzerlik ve farklılık üzerinden görsel ayırt etme.', precursor: true },
  { id: 'MX3', station: '5 · Akademik Öncüller · Eşleme, Sınıflama ve Nicelik', title: 'Rengi eşleştir', instruction: 'Kırmızı, mavi ve sarı kartları koy. Aynı renkte kapağı doğru kartın üzerine bırakmasını iste.', material: '3 renk kartı + eş renkli kapaklar', observe: 'Rengi bir sınıflama/eşleme özelliği olarak kullanması.', precursor: true },
  { id: 'MX4', station: '5 · Akademik Öncüller · Eşleme, Sınıflama ve Nicelik', title: 'Şekli eşleştir', instruction: 'Daire ve kareyi göster. Aynı şekilli parçaları eşleştirmesini veya uygun boşluğa koymasını iste.', material: 'Daire/kare parçaları veya şekil kutusu', observe: 'Temel şekil benzerliğini fark etme ve görsel-konumsal eşleme.', precursor: true },
  { id: 'CO2', station: '5 · Akademik Öncüller · Eşleme, Sınıflama ve Nicelik', title: 'Basit gruplama', instruction: 'İki tür nesneyi karışık ver: hayvanlar ve araçlar gibi. Birlikte olanları ayırmasını iste.', material: '4–6 küçük nesne/kart', observe: 'Basit kategori kuralını fark etme; model gerektiğinde öğrenme tepkisi.', minAgeMonths: 30, precursor: true },
  { id: 'QT1', station: '5 · Akademik Öncüller · Eşleme, Sınıflama ve Nicelik', title: 'Bana bir tane ver', instruction: 'Önüne birkaç aynı nesne koy ve yalnız “Bana bir tane ver.” de.', material: '4–5 aynı blok/halka', observe: '“Bir” niceliğini sözel yönergeyle ilişkilendirip tek nesne seçmesi.', precursor: true },
  { id: 'QT2', station: '5 · Akademik Öncüller · Eşleme, Sınıflama ve Nicelik', title: 'Bir ve çok', instruction: 'Bir tabakta tek nesne, diğerinde birkaç nesne göster. “Bir tane olanı göster.” de; sonra “çok olanı” sor.', material: 'İki tabak + küçük nesneler', observe: 'Teklik ve çokluk arasındaki temel nicelik farkını ayırt etmesi.', precursor: true },
  { id: 'QT3', station: '5 · Akademik Öncüller · Eşleme, Sınıflama ve Nicelik', title: 'Her birine bir tane', instruction: 'Üç oyuncak bebeği sırala ve üç kaşık ver. “Her bebeğe bir kaşık ver.” de.', material: '3 bebek/figür + 3 küçük nesne', observe: 'Birebir dağıtım; her hedefe tek karşılık verme ve artan/eksik nesneyi fark etme.', minAgeMonths: 30, precursor: true },
  { id: 'CN1', station: '5 · Akademik Öncüller · Eşleme, Sınıflama ve Nicelik', title: 'Büyük ve küçük', instruction: 'Aynı türden belirgin büyük ve küçük iki nesne koy. Önce büyüğü, sonra küçüğü vermesini iste.', material: 'Aynı tür iki farklı boy nesne', observe: 'Boyut özelliğini kullanarak seçim yapma ve kavramı nesneye uygulama.', precursor: true },

  { id: 'CO3', station: '6 · Akademik Öncüller · Kavram, Örüntü ve Problem Çözme', title: 'Oyuncağa ulaşma yolu', instruction: 'Sevdiği oyuncağı hafif bir örtünün altına veya kolay açılan kutuya koy.', material: 'Oyuncak + örtü/kutu', observe: 'Amaç için araç/engel ilişkisini çözme, deneme ve vazgeçmeden sürdürme.', precursor: true },
  { id: 'SQ1', station: '6 · Akademik Öncüller · Kavram, Örüntü ve Problem Çözme', title: 'İki parçalı sırayı kopyala', instruction: 'Kırmızı bloğu, ardından sarı bloğu yan yana koy. Aynı iki parçalı sırayı yeni bloklarla tekrar etmesini iste.', material: '2 kırmızı + 2 sarı blok', observe: 'Kısa görsel sırayı tutup aynı düzeni yeniden kurması.', precursor: true },
  { id: 'PT1', station: '6 · Akademik Öncüller · Kavram, Örüntü ve Problem Çözme', title: 'Basit AB örüntüsünü sürdür', instruction: 'Kırmızı–mavi–kırmızı dizisini kur. Bir sonraki parçayı seçeneklerden koymasını iste.', material: 'İki renkten 5–6 blok', observe: 'Tekrarlayan iki öğeli düzeni fark edip sürdürmesi.', minAgeMonths: 30, precursor: true },
  { id: 'PT2', station: '6 · Akademik Öncüller · Kavram, Örüntü ve Problem Çözme', title: 'Önce–sonra sırasını kur', instruction: 'Tanıdık iki aşamalı bir rutinin iki resmini karışık ver: elleri yıka → havluyla kurula gibi. Sıraya koymasını iste.', material: 'İki aşamalı rutin kartı', observe: 'İki olay arasında doğal zaman sırası kurması.', minAgeMonths: 30, precursor: true },
  { id: 'PB1', station: '6 · Akademik Öncüller · Kavram, Örüntü ve Problem Çözme', title: 'Neden sonucu yeniden oluştur', instruction: 'Basınca hareket eden basit bir oyuncağı bir kez çalıştır. Sonra oyuncağı çocuğa ver ve sonucu kendisinin oluşturmasını bekle.', material: 'Basit neden-sonuç oyuncağı', observe: 'Eylem ile sonuç arasındaki ilişkiyi keşfetme ve tekrar kullanma.', precursor: true },
  { id: 'PB2', station: '6 · Akademik Öncüller · Kavram, Örüntü ve Problem Çözme', title: 'Aracı kullanarak ulaş', instruction: 'Oyuncağı doğrudan erişemeyeceği ama kısa bir bez/şerit çekilince yaklaşacak güvenli bir düzene koy.', material: 'Oyuncak + kısa bez/şerit', observe: 'Hedefe ulaşmak için aracı fark etme, deneme ve strateji değiştirme.', precursor: true },
  { id: 'PB3', station: '6 · Akademik Öncüller · Kavram, Örüntü ve Problem Çözme', title: 'Hangisi buraya sığar?', instruction: 'Biri belirgin büyük, biri küçük iki parçayı ve küçük bir kabı göster. Hangi parçanın kaba sığacağını denemesine izin ver.', material: 'İki boy parça + küçük kap', observe: 'Boyut–mekân ilişkisini problem çözmede kullanma; deneme sonrası düzeltme.', precursor: true },
  { id: 'TR1', station: '6 · Akademik Öncüller · Kavram, Örüntü ve Problem Çözme', title: 'Öğrendiğin kuralı yeni renge taşı', instruction: 'Önce kırmızı kapağı kırmızı karta eşlemeyi modelle. Sonra mavi kapak ve mavi kartı ver; yeni örneği kendisinin tamamlamasını bekle.', material: 'Kırmızı ve mavi kart/kapak çiftleri', observe: 'Modeldeki eşleme kuralını yeni materyale transfer etmesi.', minAgeMonths: 30, precursor: true },

  { id: 'ME1', station: '7 · Bellek ve Öğrenme', title: 'Saklanan yeri hatırla', instruction: 'Oyuncağı iki kaptan birine sakla. Kısa bir başka etkinlikten sonra bulmasını iste.', material: 'İki kap + küçük oyuncak', observe: 'Kısa gecikme sonrası konumu hatırlama; ipucu gereksinimi.' },
  { id: 'ME2', station: '7 · Bellek ve Öğrenme', title: 'Yeni yolu öğren', instruction: 'Yeni bir oyuncak kullanımını bir kez modelle. Kısa ara sonrası aynı eylemi tekrar denemesini iste.', material: 'Basit neden-sonuç oyuncağı', observe: 'Modelden öğrenme ve kısa süre sonra yeniden kullanma.', precursor: true },
  { id: 'AT1', station: '8 · Dikkat ve Öz Düzenleme', title: 'Ortak etkinliği sürdür', instruction: 'Çocuğun sevdiği kısa bir ortak oyunu 1–2 dakika doğal biçimde sürdür.', material: 'Tercih edilen oyun', observe: 'Etkinliğe geri dönme, yetişkinle ortak odağı koruma ve yönlendirme gereksinimi.' },
  { id: 'AT2', station: '8 · Dikkat ve Öz Düzenleme', title: 'Bir etkinlikten diğerine geç', instruction: 'Sevdiği oyundan farklı ama tanıdık ikinci etkinliğe geçiş yap.', material: 'İki tanıdık oyun', observe: 'Geçişte destek ihtiyacı; kısa uyarı/model sonrası toparlanma.' },
  { id: 'VM1', station: '9 · Görsel-Motor ve Hareket', title: 'Basit yerleştirme', instruction: '2–3 parçalı basit yerleştirme/puzzle sun.', material: 'Basit şekil kutusu veya puzzle', observe: 'Şekil-konum eşleme, parçayı çevirme ve ince motor kontrol.', precursor: true },
  { id: 'VM2', station: '9 · Görsel-Motor ve Hareket', title: 'Kule / yapı kurma', instruction: 'Birkaç blok ver ve küçük bir kule kurması için fırsat sun; gerekirse bir kez modelle.', material: 'Bloklar', observe: 'Görsel plan, el-göz koordinasyonu ve modelden yararlanma.' },
  { id: 'GM1', station: '9 · Görsel-Motor ve Hareket', title: 'Git–dur oyunu', instruction: 'Güvenli alanda kısa “git–dur” oyunu oyna.', material: 'Boş ve güvenli alan', observe: 'Kaba motor hareket sırasında sözel işarete yönelme ve durma.' },
  { id: 'GM2', station: '9 · Görsel-Motor ve Hareket', title: 'Topla karşılıklı oyun', instruction: 'Topu yuvarlama veya hafifçe tekmeleme fırsatı ver.', material: 'Yumuşak top', observe: 'Topa amaçlı yönelme, hareketi ayarlama ve karşılıklı oyuna katılma.' },
  { id: 'AD1', station: '10 · Günlük Yaşam', title: 'Kendi yapabildiği günlük iş', instruction: 'Bardak/kaşık kullanımı gibi günlük bir beceriyi doğal ortamda gözle veya bakım verenden somut örnek iste.', material: 'Günlük yaşam materyali', observe: 'Ne kadarını bağımsız yaptığı; hangi yardımın gerektiği.' },
  { id: 'AD2', station: '10 · Günlük Yaşam', title: 'Toparla ve rutini tamamla', instruction: 'Oyun sonunda “Oyuncakları kutuya koyalım.” diyerek basit toparlama rutini oluştur.', material: 'Oyuncaklar + kutu', observe: 'Günlük rutini anlama, katılma ve ipucuyla bağımsızlığın değişmesi.' },
  {id:'MOTJ',station:'11 · Kaba ve İnce Motor',title:'İki ayağıyla zıpla',instruction:'Güvenli zeminde iki ayağıyla yerden zıplaması için model ol.',material:'Boş güvenli alan',observe:'İki ayağın birlikte yerden ayrılması ve denge.',minAgeMonths:30,v3Only:true},{id:'MOTB',station:'11 · Kaba ve İnce Motor',title:'Kısa denge',instruction:'Çizgi üzerinde veya sabit duruşta kısa süre dengesini korumasını gözle.',material:'Zemine bant çizgi',observe:'Dengeyi kısa süre koruma.',v3Only:true},{id:'MOTT',station:'11 · Kaba ve İnce Motor',title:'Topu iki elle at',instruction:'Yumuşak topu iki elle ileri atmasını iste.',material:'Yumuşak top',observe:'Amaçlı iki el kullanımı ve kuvvet ayarı.',v3Only:true},{id:'MOTC',station:'11 · Kaba ve İnce Motor',title:'Büyük topu yakalamaya çalış',instruction:'Büyük yumuşak topu kısa mesafeden yavaşça gönder.',material:'Büyük yumuşak top',observe:'Topa hazırlanma ve yakalama girişimi.',minAgeMonths:30,v3Only:true},{id:'FIP',station:'11 · Kaba ve İnce Motor',title:'Kalem kavrama',instruction:'Kalın boya kalemi ver ve serbest karalama yapmasını iste.',material:'Kalın boya kalemi + kâğıt',observe:'Kalemi işlevsel biçimde kavrama.',v3Only:true},{id:'FIL',station:'11 · Kaba ve İnce Motor',title:'Dikey ve yatay çizgiyi taklit et',instruction:'Bir dikey ve bir yatay çizgi çiz; sırayla taklit etmesini iste.',material:'Kâğıt + kalem',observe:'Görsel-motor taklit ve çizgi yönü.',minAgeMonths:30,v3Only:true},{id:'FIB',station:'11 · Kaba ve İnce Motor',title:'Büyük parçayı ipe geçir',instruction:'Büyük delikli 2–3 parçayı kalın ipe geçirmesini iste.',material:'Büyük boncuk/parça + kalın ip',observe:'İki el koordinasyonu ve hedefleme.',minAgeMonths:30,v3Only:true},{id:'FIC',station:'11 · Kaba ve İnce Motor',title:'Kapak aç-kapa',instruction:'Kolay açılan kapaklı kabı açıp kapamasını iste.',material:'Güvenli kapaklı kap',observe:'İki el koordinasyonu ve planlama.',v3Only:true},{id:'FIT',station:'11 · Kaba ve İnce Motor',title:'Kule yap',instruction:'Bloklarla serbest veya kısa model sonrası kule yapmasını iste.',material:'6–8 blok',observe:'El-göz koordinasyonu ve yapı sürdürme.',v3Only:true},{id:'FIPG',station:'11 · Kaba ve İnce Motor',title:'Sayfa çevir',instruction:'Kalın sayfalı kitabı incelemesine izin ver.',material:'Kalın sayfalı kitap',observe:'Sayfaları amaçlı tek tek/az sayıda çevirme.',v3Only:true},
  {id:'LNAME',station:'12 · Dilin Alt Bileşenleri',title:'Adına yönelme',instruction:'Çocuk başka bir nesneyle meşgulken adını doğal sesle bir kez söyle.',material:'Doğal oyun',observe:'Adına yönelme ve bakış paylaşımı.',v3Only:true},{id:'LANIMAL',station:'12 · Dilin Alt Bileşenleri',title:'Hayvan sesi',instruction:'Tanıdık hayvan oyuncağını göster; sesini üretmesi/taklit etmesi için fırsat ver.',material:'Hayvan oyuncakları',observe:'Ses taklidi ve sembol-eşleme.',v3Only:true},{id:'LSONG',station:'12 · Dilin Alt Bileşenleri',title:'Şarkı / tekerlemeye eşlik',instruction:'Tanıdık kısa bir şarkıyı başlatıp bekle.',material:'Ek materyal gerekmez',observe:'Ritim, sözel tamamlama veya hareketle katılım.',v3Only:true},{id:'LBODY5',station:'12 · Dilin Alt Bileşenleri',title:'Beş vücut bölümünü göster',instruction:'Göz, burun, ağız, kulak, karın gibi beş bölümü sırayla sor.',material:'Ek materyal gerekmez',observe:'Sözcük-anlam eşlemesi ve yönerge takibi.',minAgeMonths:30,v3Only:true},{id:'LREFUSE',station:'12 · Dilin Alt Bileşenleri',title:'Reddetme iletişimi',instruction:'İstemediği doğal bir seçenek sun; uygun reddetme fırsatı oluştur.',material:'İki tanıdık seçenek',observe:'Hayır, istemiyorum, baş hareketi veya uygun jestle reddetme.',v3Only:true},{id:'LFAR',station:'12 · Dilin Alt Bileşenleri',title:'Uzak işareti takip et',instruction:'Biraz uzaktaki belirgin nesneyi işaret ederek “Bak” de.',material:'İlgi çekici uzak nesne',observe:'Parmağın ucundan hedefe yönelme.',v3Only:true},{id:'LEMOTION',station:'12 · Dilin Alt Bileşenleri',title:'Temel duyguyu ayırt et',instruction:'Belirgin mutlu ve üzgün iki yüz görselinden birini sor.',material:'İki temel duygu yüzü',observe:'Yüz ifadesi ile temel duygu arasında ilişki kurma.',minAgeMonths:30,v3Only:true},
  {id:'NP1',station:'13 · Doğal Oyun Gözlemi',title:'Yetişkine yönelme',instruction:'10 dakikalık doğal oyunda çocuğu yönlendirmeden yetişkine kendiliğinden yönelmesini izle.',material:'Sevdiği oyuncaklar',observe:'Yetişkini iletişim ortağı olarak kullanma.',v3Only:true},{id:'NP2',station:'13 · Doğal Oyun Gözlemi',title:'Ortak dikkat',instruction:'Doğal oyunda nesne-yetişkin arasında dikkat paylaşımını izle.',material:'Sevdiği oyuncaklar',observe:'Ortak dikkat girişimleri.',v3Only:true},{id:'NP3',station:'13 · Doğal Oyun Gözlemi',title:'İstek bildirme',instruction:'Doğal oyunda istediği nesne/yardım için iletişim başlatmasını izle.',material:'Sevdiği oyuncaklar',observe:'İstek bildirme biçimi ve bağımsızlığı.',v3Only:true},{id:'NP4',station:'13 · Doğal Oyun Gözlemi',title:'Taklit',instruction:'Doğal oyunda yetişkinin basit eylemini kendiliğinden veya kısa fırsatla taklit etmesini izle.',material:'Oyun materyali',observe:'Sosyal/motor taklit.',v3Only:true},{id:'NP5',station:'13 · Doğal Oyun Gözlemi',title:'Sıra alma',instruction:'Karşılıklı oyunu birkaç tur sürdür.',material:'Top veya ortak oyuncak',observe:'Sıra alma ve karşılıklı devam.',v3Only:true},{id:'NP6',station:'13 · Doğal Oyun Gözlemi',title:'Sembolik oyun',instruction:'Mış gibi oyunun kendiliğinden ortaya çıkıp çıkmadığını izle.',material:'Bebek/günlük yaşam oyuncakları',observe:'Sembolik oyun çeşitliliği.',v3Only:true},{id:'NP7',station:'13 · Doğal Oyun Gözlemi',title:'Problem çözme',instruction:'Küçük bir oyun engeli oluştur ve çözüm yolunu izle.',material:'Oyuncak + basit engel',observe:'Deneme, strateji ve yardım kullanımı.',v3Only:true},{id:'NP8',station:'13 · Doğal Oyun Gözlemi',title:'Etkinliği sürdürme',instruction:'Tercih ettiği oyunda odağı ne kadar sürdürebildiğini izle.',material:'Tercih edilen oyun',observe:'Sürdürülen dikkat ve yeniden yönelme.',v3Only:true},{id:'LSAMP',station:'13 · Doğal Oyun Gözlemi',title:'10 dakikalık dil örneklemi',instruction:'Doğal oyun boyunca kendiliğinden iletişim girişimlerini, istekleri, yorumları, soruya yanıtları, taklit/ekolaliyi ve anlaşılır sözcükleri say.',material:'Doğal oyun',observe:'İletişimin sıklığı ve işlev çeşitliliği.',v3Only:true,metrics:['Kendiliğinden girişim','İstek','Yorum','Soruya yanıt','Taklit / ekolali','Anlaşılır sözcük']}
];

const areas = ['Alıcı Dil', 'İfade Edici Dil', 'Konuşma ve Anlaşılırlık', 'Ortak Dikkat', 'Sosyal İletişim', 'Taklit', 'Oyun Gelişimi', 'Bilişsel Problem Çözme', 'Dikkat ve Öz Düzenleme', 'Bellek ve Öğrenme Tepkisi', 'Görsel Algı', 'İnce Motor', 'Kaba Motor', 'Uyumsal / Günlük Yaşam'];
const precursorAreas = ['Eşleme ve Görsel Ayırt Etme', 'Sınıflama ve Kavram Oluşturma', 'Nicelik ve Birebir İlişki', 'Boyut, Şekil ve Mekânsal Kavram', 'Örüntü, Sıra ve Parça-Bütün', 'Neden-Sonuç ve Problem Çözme', 'Modelden Öğrenme ve Transfer'];
const legacyRatingOptions:Array<{value:EarlyRating;label:string;detail:string}>=[{value:'independent',label:'Bağımsız gözlendi',detail:'Ek ipucu veya model gerekmedi.'},{value:'prompted',label:'Kısa ipucuyla',detail:'Sözel/jest/görsel ipucu sonrası ortaya çıktı.'},{value:'modeled',label:'Model sonrası',detail:'Yetişkin örnekledikten sonra yaptı.'},{value:'not_observed',label:'Henüz gözlenmedi',detail:'Uygun fırsat verildi ancak bu oturumda ortaya çıkmadı.'}];
const v3RatingOptions:Array<{value:EarlyRating;label:string;detail:string}>=[{value:'independent',label:'Bağımsız',detail:'Yardım olmadan yaptı.'},{value:'verbal_prompt',label:'Sözel ipucu',detail:'Kısa sözel hatırlatma sonrası yaptı.'},{value:'visual_prompt',label:'Jest / görsel ipucu',detail:'İşaret, jest veya görsel ipucu sonrası yaptı.'},{value:'modeled',label:'Model olma',detail:'Yetişkin örnekledikten sonra yaptı.'},{value:'physical_assist',label:'Fiziksel yardım',detail:'Kısmi/tam fiziksel yardım gerekti.'},{value:'not_observed',label:'Henüz gözlenmedi',detail:'Uygun fırsatta ortaya çıkmadı.'}];

export default function EarlyDevelopmentE2({ sessionId, studentLabel, ageMonths, assessmentPurpose, initialState, onCompleted }: { sessionId: string; studentLabel: string; ageMonths?: number; assessmentPurpose?: string; initialState?: EarlyDevelopmentState; onCompleted: (session: unknown) => void }) {
  const version = initialState?.version ?? 'E2-v2';
  const visibleItems = useMemo(() => {
    if(version==='E2-v1')return items.filter(item=>legacyItemIds.has(item.id));
    const age=ageMonths??24;
    return items.filter(item=>(version==='E2-v3'||!item.v3Only)&&(!item.minAgeMonths||age>=item.minAgeMonths));
  }, [ageMonths, version]);
  const [responses, setResponses] = useState<EarlyResponse[]>(initialState?.responses ?? []);
  const firstIncomplete = useMemo(() => {
    const done = new Set((initialState?.responses ?? []).map((response) => response.itemId));
    const found = visibleItems.findIndex((item) => !done.has(item.id));
    return found < 0 ? Math.max(0, visibleItems.length - 1) : found;
  }, [initialState, visibleItems]);
  const [index, setIndex] = useState(firstIncomplete);
  const[started,setStarted]=useState(version!=='E2-v3'&&(initialState?.responses.length??0)>0);
  const[mode,setMode]=useState<'overview'|'child'|'caregiver'>(['E2-v3','E2-v4','E2-v5','E2-v6','E2-v7'].includes(version)?'overview':'child');
  const [rating, setRating] = useState<EarlyRating | ''>('');
  const[note,setNote]=useState('');
  const[metrics,setMetrics]=useState<Record<string,number>>({});
  const[state,setState]=useState<EarlyDevelopmentState|undefined>(initialState);
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState('');
  const item = visibleItems[index];
  const requiredIds = useMemo(() => new Set(visibleItems.map((entry) => entry.id)), [visibleItems]);
  const completed = new Set(responses.filter((response) => requiredIds.has(response.itemId)).map((response) => response.itemId)).size;
  const pct = Math.round((completed / Math.max(1, visibleItems.length)) * 100);
  const stationRows = useMemo(() => {
    const map = new Map<string, number>();
    visibleItems.forEach((entry) => map.set(entry.station, (map.get(entry.station) ?? 0) + 1));
    return [...map.entries()];
  }, [visibleItems]);
  const precursorCount = visibleItems.filter((entry) => entry.precursor).length;
  const routeLabel=version==='E2-v1'?'E2-v1 · önceki 36 görevlik rota':(ageMonths??24)>=30?'30–35 ay · genişletilmiş rota':'24–29 ay · temel rota';
  const ratingOptions=version==='E2-v3'?v3RatingOptions:legacyRatingOptions;

  async function save(nextRating: EarlyRating) {
    if (busy) return;
    setBusy(true);
    setError('');
    try {
      const result=await api.post('/api/session/'+sessionId+'/early-development-response',{itemId:item.id,rating:nextRating,note:note.trim().slice(0,300),metrics});
      const session = result.data as { status?: string; earlyDevelopment?: EarlyDevelopmentState };
      const nextResponses=session.earlyDevelopment?.responses??responses;setResponses(nextResponses);setState(session.earlyDevelopment);setRating('');setNote('');setMetrics({});if(session.status==='completed'){onCompleted(session);return}if(session.earlyDevelopment?.childCompletedAt&&version==='E2-v3'){setMode('overview');return}setIndex(current=>Math.min(visibleItems.length-1,current+1));
    } catch {
      setError('Gözlem kaydedilemedi. Aynı adımı yeniden deneyin; önceki kayıtlar korunur.');
    } finally {
      setBusy(false);
    }
  }

  if(version==='E2-v7'&&mode==='child')return <EarlyDevelopmentChildCenterV7 sessionId={sessionId} ageMonths={ageMonths} initialState={state??initialState} onBack={()=>setMode('overview')} onUpdated={next=>{const s=next as {status?:string;earlyDevelopment?:EarlyDevelopmentState};setState(s.earlyDevelopment);setResponses(s.earlyDevelopment?.responses??responses);if(s.status==='completed')onCompleted(next)}}/>;
  if(version==='E2-v7'&&mode==='caregiver')return <EarlyDevelopmentCaregiverV4 sessionId={sessionId} studentLabel={studentLabel} initialState={state?.caregiver} onBack={()=>setMode('overview')} onUpdated={next=>{const s=next as {status?:string;earlyDevelopment?:EarlyDevelopmentState};setState(s.earlyDevelopment);if(s.status==='completed')onCompleted(next)}}/>;
  if(version==='E2-v7'&&mode==='overview')return <div className='early-shell'><main className='early-main'><section className='early-overview v7-overview'><div className='early-hero'><span>CZA · E2-v7 ADAPTİF BÜTÜNCÜL MERKEZ</span><h1>🌟 Merhaba {studentLabel}! Küçük Kaşif yolculuğun hazır.</h1><p>Yeni çocuk merkezi sabit bir soru listesi kullanmaz. Ay yaşı, dil düzeyi, ilgi, dikkat süresi ve toplanan performans kanıtına göre her bölümde uygun görev seçilir; doğal oyun ve veli beyanı ayrı kanıt kaynakları olarak korunur.</p><div className='early-meta'><b>{ageMonths??'—'} ay</b><b>130 dijital soru havuzu</b><b>8 değerlendirme bölümü</b><b>Adaptif zorluk</b></div></div><div className='early-dual-grid'><article><span>1</span><h2>🌈 Küçük Kaşif Oyun Dünyaları</h2><p>Görsel eşleme, kavram, ilişkilendirme, işitsel, hafıza, dikkat ve doğal oyun bölümleri çocuğa özel rota üretir. Cinsiyet zorluğu değiştirmez; 5 saniye yalnız ipucu sinyalidir.</p><strong>{state?.childCompletedAt?'Tamamlandı':responses.length+' kanıt kaydedildi'}</strong><button className='early-primary' type='button' onClick={()=>setMode('child')}>🚀 Oyun dünyalarını aç →</button></article><article><span>2</span><h2>CZA Veli Gelişim Görüşmesi</h2><p>Evde iletişim, sosyal oyun, düzenleme-duyusal ihtiyaç, günlük yaşam, güvenlik ve aile hedefleri ayrı veri kaynağı olarak kalır.</p><strong>{state?.caregiver?.completedAt?'Tamamlandı':(state?.caregiver?.responses.length||0)+' yanıt kaydedildi'}</strong><button className='early-primary' type='button' onClick={()=>setMode('caregiver')}>Veli görüşmesini aç →</button></article></div><div className='early-rule'><strong>Adaptif kanıt kuralı:</strong> 3 bağımsız seri zorluğu artırabilir; 2 zorlanma seri desteği artırır. Kategori yüzdesi yaş normu değil, yalnız oturum içi bağımsız performans oranıdır. Tavan görevleri nötrdür.</div></section></main></div>;
  if(version==='E2-v6'&&mode==='child')return <EarlyDevelopmentChildCenterV6 sessionId={sessionId} ageMonths={ageMonths} initialState={state??initialState} onBack={()=>setMode('overview')} onUpdated={next=>{const s=next as {status?:string;earlyDevelopment?:EarlyDevelopmentState};setState(s.earlyDevelopment);setResponses(s.earlyDevelopment?.responses??responses);if(s.status==='completed')onCompleted(next)}}/>;
  if(version==='E2-v6'&&mode==='caregiver')return <EarlyDevelopmentCaregiverV4 sessionId={sessionId} studentLabel={studentLabel} initialState={state?.caregiver} onBack={()=>setMode('overview')} onUpdated={next=>{const s=next as {status?:string;earlyDevelopment?:EarlyDevelopmentState};setState(s.earlyDevelopment);if(s.status==='completed')onCompleted(next)}}/>;
  if(version==='E2-v6'&&mode==='overview')return <div className='early-shell'><main className='early-main'><section className='early-overview'><div className='early-hero'><span>CZA · E2-v6 BÜTÜNCÜL DEĞERLENDİRME MERKEZİ</span><h1>{studentLabel} için 8 bölümlü, yaşa göre kademelenen değerlendirme</h1><p>Çocuk değerlendirmesi artık tek bir kısa görev dizisi değildir. Kavram-eşleme, alıcı dil, dikkat-görsel bellek, konuşma ve ilişkiler, işitsel ayırt etme, günlük yaşam ilişkileri, çalışma belleği ve yürütücü işlevler sekiz ayrı bölümde; ekran egzersizi ile gerçek oyun kanıtları birlikte toplanır.</p><div className='early-meta'><b>{ageMonths??'—'} ay</b><b>8 değerlendirme bölümü</b><b>Yaşa göre geniş görev bankası</b><b>Bölüm bölüm uygulanır</b></div></div><div className='early-dual-grid'><article><span>1</span><h2>Çocuk Bütüncül Değerlendirme Merkezi</h2><p>Her bölüm ayrı başlayıp ayrı gün sürdürülebilir. Bölüm içinde yeterli sayıda görsel, işitsel, bellek, dil ve gerçek oyun görevi bulunur; ileri keşif görevleri nötr tutulur.</p><strong>{state?.childCompletedAt?'Tamamlandı':responses.length+' görev kaydedildi'}</strong><button className='early-primary' type='button' onClick={()=>setMode('child')}>8 bölümlü çocuk merkezini aç →</button></article><article><span>2</span><h2>CZA Veli Gelişim Görüşmesi</h2><p>Evde iletişim, sosyal oyun, öğrenme biçimi, düzenleme-duyusal ihtiyaçlar, günlük yaşam, güvenlik ve aile hedefleri ayrı veri kaynağı olarak kalır.</p><strong>{state?.caregiver?.completedAt?'Tamamlandı':(state?.caregiver?.responses.length||0)+' yanıt kaydedildi'}</strong><button className='early-primary' type='button' onClick={()=>setMode('caregiver')}>Veli görüşmesini aç →</button></article></div><div className='early-rule'><strong>Bütüncül uygulama kuralı:</strong> Sekiz bölümün tek oturumda bitirilmesi beklenmez. Çocuğa puan, geri sayım veya doğru-yanlış mesajı gösterilmez. İlk seçim, tepki süresi, yardım düzeyi ve isteğe bağlı ilgi/kaçınma/zorlanma/yorgunluk kaydı ayrı kanıt olarak tutulur.</div></section></main></div>;
  if(version==='E2-v5'&&mode==='child')return <EarlyDevelopmentChildExercisesV5 sessionId={sessionId} ageMonths={ageMonths} initialState={state??initialState} onBack={()=>setMode('overview')} onUpdated={next=>{const s=next as {status?:string;earlyDevelopment?:EarlyDevelopmentState};setState(s.earlyDevelopment);setResponses(s.earlyDevelopment?.responses??responses);if(s.status==='completed')onCompleted(next)}}/>;
  if(version==='E2-v5'&&mode==='caregiver')return <EarlyDevelopmentCaregiverV4 sessionId={sessionId} studentLabel={studentLabel} initialState={state?.caregiver} onBack={()=>setMode('overview')} onUpdated={next=>{const s=next as {status?:string;earlyDevelopment?:EarlyDevelopmentState};setState(s.earlyDevelopment);if(s.status==='completed')onCompleted(next)}}/>;
  if(version==='E2-v5'&&mode==='overview')return <div className='early-shell'><main className='early-main'><section className='early-overview'><div className='early-hero'><span>CZA · E2-v5 PEDAGOJİK ERKEN GELİŞİM</span><h1>{studentLabel} için yaşa göre kademelenen, baskısız değerlendirme</h1><p>24–36 ay artık tek zorluk düzeyi değildir. Sistem 24–26, 27–29, 30–32 ve 33–35 aylık dört rotada basitten zora ilerler; önce puansız dokunma denemesi, sonra kısa ekran mini blokları, ardından gerçek oyun ve yüz yüze gözlem gelir.</p><div className='early-meta'><b>{ageMonths??'—'} ay</b><b>{(ageMonths??24)<27?'24–26 ay temel rota':(ageMonths??24)<30?'27–29 ay genişleyen rota':(ageMonths??24)<33?'30–32 ay iki aşamalı rota':'33–35 ay + nötr tavan'}</b><b>Mini blok + mola</b><b>Doğru/yanlış baskısı yok</b></div></div><div className='early-dual-grid'><article><span>1</span><h2>Çocuk Egzersizleri + Gerçek Oyun</h2><p>Bak-dokun, eşleştir-kavram, düşün-bul; uygun yaşta nötr tavan örnekleri. Ekran bittikten sonra ortak dikkat, dil, oyun, motor ve problem çözme gerçek materyalle gözlenir.</p><strong>{state?.childCompletedAt?'Tamamlandı':responses.length+' görev kaydedildi'}</strong><button className='early-primary' type='button' onClick={()=>setMode('child')}>Çocuk değerlendirmesini aç →</button></article><article><span>2</span><h2>CZA Veli Gelişim Görüşmesi</h2><p>Evde iletişim, sosyal oyun, öğrenme biçimi, düzenleme-duyusal ihtiyaçlar, günlük yaşam, güvenlik ve aile hedefleri ayrı veri kaynağı olarak kalır.</p><strong>{state?.caregiver?.completedAt?'Tamamlandı':(state?.caregiver?.responses.length||0)+' yanıt kaydedildi'}</strong><button className='early-primary' type='button' onClick={()=>setMode('caregiver')}>Veli görüşmesini aç →</button></article></div><div className='early-rule'><strong>Pedagojik kural:</strong> Çocuğa puan, geri sayım veya kırmızı/yeşil doğru-yanlış gösterilmez. İleri tavan görevinin ortaya çıkmaması olumsuz gelişim kanıtı değildir. Tek oturum zorunlu değildir; yorulursa kaldığı yerden başka zaman devam edilir.</div></section></main></div>;
  if(version==='E2-v4'&&mode==='child')return <EarlyDevelopmentChildExercises sessionId={sessionId} ageMonths={ageMonths} initialState={state??initialState} onBack={()=>setMode('overview')} onUpdated={next=>{const s=next as {status?:string;earlyDevelopment?:EarlyDevelopmentState};setState(s.earlyDevelopment);setResponses(s.earlyDevelopment?.responses??responses);if(s.status==='completed')onCompleted(next)}}/>;
  if(version==='E2-v4'&&mode==='caregiver')return <EarlyDevelopmentCaregiverV4 sessionId={sessionId} studentLabel={studentLabel} initialState={state?.caregiver} onBack={()=>setMode('overview')} onUpdated={next=>{const s=next as {status?:string;earlyDevelopment?:EarlyDevelopmentState};setState(s.earlyDevelopment);if(s.status==='completed')onCompleted(next)}}/>;
  if(version==='E2-v4'&&mode==='overview')return <div className='early-shell'><main className='early-main'><section className='early-overview'><div className='early-hero'><span>CZA · E2-v4 ETKİLEŞİMLİ ERKEN GELİŞİM</span><h1>{studentLabel} için iki kaynaklı, görev temelli değerlendirme</h1><p>Çocuğun bölümü artık yalnız sözel gözlem değildir. Kısa dokunmatik ekran egzersizleriyle görsel eşleme, nicelik, kavram, alıcı dil ve erken problem çözme doğrudan ölçülür; ortak dikkat, oyun, motor ve kendiliğinden iletişim ise kısa doğal oyun görevleriyle tamamlanır.</p><div className='early-meta'><b>{ageMonths??'—'} ay</b><b>{(ageMonths??24)>=30?'30 çocuk görevi':'23 çocuk görevi'}</b><b>{(ageMonths??24)>=30?'17 dokunmatik egzersiz':'12 dokunmatik egzersiz'}</b><b>37 özgün veli sorusu</b></div></div><div className='early-dual-grid'><article><span>1</span><h2>Çocuk Egzersizleri + Doğal Oyun</h2><p>Dokun–seç–eşleştir–bul görevleri; ardından ortak dikkat, taklit, oyun, motor, geçiş ve doğal iletişim gözlemleri.</p><strong>{state?.childCompletedAt?'Tamamlandı':responses.length+' görev kaydedildi'}</strong><button className='early-primary' type='button' onClick={()=>setMode('child')}>Çocuk değerlendirmesini aç →</button></article><article><span>2</span><h2>CZA Veli Gelişim Görüşmesi</h2><p>Evde iletişim, öğrenme biçimi, sosyal oyun, düzenleme-duyusal ihtiyaçlar, günlük yaşam, güvenlik ve aile hedefleri. Örnek PDF'nin soru listesi kullanılmaz.</p><strong>{state?.caregiver?.completedAt?'Tamamlandı':(state?.caregiver?.responses.length||0)+' yanıt kaydedildi'}</strong><button className='early-primary' type='button' onClick={()=>setMode('caregiver')}>Veli görüşmesini aç →</button></article></div><div className='early-rule'><strong>Kanıt kuralı:</strong> Ekran görevlerinde ilk dokunuş ve tepki süresi otomatik kaydolur. İlk seçim uygun değilse çocukta doğru/yanlış işareti gösterilmez; destek basamağıyla yeniden deneme yapılır. Veli beyanı ve çocuk performansı raporda ayrı tutulur.</div></section></main></div>;
  if(version==='E2-v3'&&mode==='caregiver')return <EarlyDevelopmentCaregiverForm sessionId={sessionId} studentLabel={studentLabel} initialState={state?.caregiver} onBack={()=>setMode('overview')} onUpdated={next=>{const s=next as {status?:string;earlyDevelopment?:EarlyDevelopmentState};setState(s.earlyDevelopment);if(s.status==='completed')onCompleted(next)}}/>;
  if(version==='E2-v3'&&mode==='overview')return <div className='early-shell'><main className='early-main'><section className='early-overview'><div className='early-hero'><span>CZA · E2 BÜTÜNCÜL ERKEN GELİŞİM</span><h1>{studentLabel} için iki kaynaklı değerlendirme</h1><p>Değerlendirme iki ayrı kanıt kaynağından oluşur. Çocuğun doğrudan performansı ile veli/bakımveren beyanı birbirine karıştırılmaz; raporda birlikte yorumlanır.</p><div className='early-meta'><b>{ageMonths??'—'} ay</b><b>Çocuk değerlendirmesi</b><b>Veli görüşmesi</b><b>Doğal oyun + öğrenmeye tepki</b></div></div><div className='early-dual-grid'><article><span>1</span><h2>Çocukla Doğrudan Değerlendirme</h2><p>Dil, ortak dikkat, sosyal iletişim, motor, oyun, bilişsel/akademik öncüller, doğal oyun ve ipucu düzeyi.</p><strong>{state?.childCompletedAt?'Tamamlandı':responses.length+' görev kaydedildi'}</strong><button className='early-primary' type='button' onClick={()=>{setStarted(true);setMode('child')}}>Çocuk değerlendirmesini aç →</button></article><article><span>2</span><h2>Veli / Bakımveren Görüşmesi</h2><p>Özgeçmiş, gelişimsel geçmiş, davranış-duyusal özellikler, günlük yaşam, aile öncelikleri ve kırmızı bayrak kontrolü.</p><strong>{state?.caregiver?.completedAt?'Tamamlandı':(state?.caregiver?.responses.length||0)+' yanıt kaydedildi'}</strong><button className='early-primary' type='button' onClick={()=>setMode('caregiver')}>Veli görüşmesini aç →</button></article></div><div className='early-caution'><strong>Tamamlanma kuralı</strong><p>Yeni E2-v3 profili iki bölüm de tamamlandığında kapanır. Tek oturum zorunlu değildir; kayıtlar korunur ve daha sonra devam edilebilir.</p></div></section></main></div>;
  if(!started)return <div className='early-shell'><main className='early-main'><section className='early-overview'><div className='early-hero'><span>CZA · E2 ERKEN GELİŞİM + AKADEMİK ÖNCÜLLER</span><h1>{studentLabel} için 24–36 ay bütüncül gelişim keşfi</h1><p>Bu uygulama gerçek oyun, günlük yaşam ve kısa yapılandırılmış görevleri birleştirir. Dil ve sosyal iletişimin yanında eşleme, sınıflama, nicelik, şekil, sıra, problem çözme ve modelden öğrenme gibi akademik öğrenmenin temel öncüllerini de izler.</p><div className='early-meta'><b>{ageMonths ?? '—'} ay</b><b>{visibleItems.length} kısa gözlem</b><b>{stationRows.length} istasyon</b><b>14 gelişim alanı</b><b>7 akademik öncül alan</b></div></div><div className='early-route-note'><strong>{routeLabel}</strong><p>{version === 'E2-v1' ? 'Bu mevcut oturum eski görev setiyle tamamlanır; yeni görevler geriye dönük zorunlu tutulmaz.' : (ageMonths ?? 24) >= 30 ? 'Temel görevların yanında 30–35 aya uygun daha karmaşık sınıflama, birebir dağıtım, örüntü, sıra ve transfer probları açılır.' : 'Temel eşleme, nicelik, kavram ve problem çözme görevleri kullanılır; 30–35 aya ayrılan ileri problar bu çocukta açılmaz.'}</p></div><div className='early-caution'><strong>Önemli sınır</strong><p>Bu araç standardize norm testi veya klinik tanı aracı değildir. “Kaç ay geride” sonucu üretmez; hangi becerinin bağımsız, destekli veya henüz gözlenmediğini eğitim planlaması için görünür kılar.</p></div><div><h2>Bugünkü {stationRows.length} istasyon</h2><div className='early-station-grid'>{stationRows.map(([title, count], index) => <div key={title}><b>{index + 1}</b><span><strong>{title.replace(/^\d+ · /, '')}</strong><small>{count} görev</small></span></div>)}</div></div>{version === 'E2-v2' && <div><h2>Akademik öğrenmenin 7 temel öncülü</h2><div className='early-area-grid precursor'>{precursorAreas.map((area, index) => <span key={area}><b>{index + 1}</b>{area}</span>)}</div><p className='early-subnote'>Bu bölüm “matematik başarısı” puanı üretmez. Sayı ve okul öğrenmesine temel oluşturan düşünme yapılarını oyun içinde örnekler.</p></div>}<div><h2>İzlenecek 14 erken gelişim alanı</h2><div className='early-area-grid'>{areas.map((area, index) => <span key={area}><b>{index + 1}</b>{area}</span>)}</div></div><div className='early-rule'><strong>Kayıt mantığı:</strong> Bağımsız → kısa ipucu → model sonrası → henüz gözlenmedi. Uygulanamayan görevde <b>“Soruyu geç · değerlendirilemedi”</b> kullanılır ve bu yanlış cevap sayılmaz.</div><button className='early-primary' type='button' onClick={() => setStarted(true)}>Uygulayıcı Modunu Başlat →</button></section></main></div>;

  return <div className='early-shell'><div className='early-progress-top'><div><strong>E2 · {item.station}</strong><span>{completed}/{visibleItems.length} kaydedildi · %{pct}</span></div><i><b style={{ width: pct + '%' }}/></i></div><main className='early-main'><section className='early-task-card'><div className='early-task-head'><div><span>GÖREV {index + 1} / {visibleItems.length}</span><h1>{item.title}</h1>{item.precursor && version === 'E2-v2' && <em className='early-task-badge'>Akademik öncül beceri</em>}</div><b>{ageMonths ?? '—'} ay</b></div><div className='early-instruction'><small>UYGULAYICI NE YAPACAK?</small><p>{item.instruction}</p></div><div className='early-two'><div><small>MATERYAL</small><strong>{item.material}</strong></div><div><small>NEYE BAKIYORUZ?</small><strong>{item.observe}</strong></div></div>{item.metrics&&version==='E2-v3'&&<div className='early-metrics'><h2>Dil örneklemi sayımları</h2>{item.metrics.map(k=><label key={k}><span>{k}</span><input type='number' min='0' value={metrics[k]??''} onChange={e=>setMetrics(m=>({...m,[k]:Math.max(0,Number(e.target.value)||0)}))}/></label>)}</div>}<div className='early-rating'><h2>Bu denemede beceri nasıl ortaya çıktı?</h2>{ratingOptions.map((option) => <button type='button' key={option.value} className={rating === option.value ? 'active' : ''} onClick={() => setRating(option.value)}><strong>{option.label}</strong><small>{option.detail}</small></button>)}</div><label className='early-note'><span>Kısa gözlem notu <small>(isteğe bağlı)</small></span><textarea value={note} onChange={(event) => setNote(event.target.value)} maxLength={300} placeholder='Örn. İlk denemede karıştırdı; tek modelden sonra yeni örnekte bağımsız yaptı.'/></label>{error && <div className='early-error'>{error}</div>}<div className='early-actions'><button type='button' className='early-skip' disabled={busy} onClick={() => void save('not_assessed')}>Soruyu geç · değerlendirilemedi</button><button type='button' className='early-primary' disabled={!rating || busy} onClick={() => rating && void save(rating)}>{busy ? 'Kaydediliyor…' : index === visibleItems.length - 1 ? 'Kaydet ve Değerlendirmeyi Bitir' : 'Kaydet ve Sonraki Göreve Geç →'}</button></div><footer>Değerlendirme amacı: {assessmentPurpose === 'LANGUAGE' ? 'Dil ve İletişim' : 'Genel Erken Gelişim'} · {precursorCount} görev akademik öncül kanıta katkı verir · Çocuğa doğru/yanlış geri bildirimi verilmez.</footer></section></main></div>;
}

