import { useMemo, useRef, useState } from 'react';
import { BrainCircuit, CheckCircle2, MessageCircle, PenLine, Quote, RotateCcw, Sparkles } from 'lucide-react';

type Domain='Gerekçelendirme'|'Örgütleme'|'Anlam'|'Üretim';
type Mode='choice'|'sequence'|'open';
type Choice={id:string;label:string};
type Item={id:string;domain:Domain;mode:Mode;title:string;prompt:string;scenario:string;choices?:Choice[];need?:number;correct?:string};
type Row={id:string;domain:Domain;answer:string;score:number|null;max:number;ms:number;changes:number;modality:'structured'|'written'|'spoken'|'skipped'};

const items:Item[]=[
{id:'G1',domain:'Gerekçelendirme',mode:'choice',title:'Nedenini güçlendir',prompt:'Deniz’in kararını en iyi açıklayan cümleyi seç.',scenario:'Deniz teneffüse çıkarken şemsiyesini aldı. Pencereden baktığında yağmur yağıyordu.',correct:'rain',choices:[{id:'rain',label:'Şemsiyesini aldı çünkü yağmurda ıslanmamak istedi.'},{id:'bag',label:'Şemsiyesini aldı çünkü çantası maviydi.'},{id:'break',label:'Şemsiyesini aldı çünkü teneffüs uzundu.'},{id:'book',label:'Şemsiyesini aldı çünkü dün kitap okudu.'}]},
{id:'O1',domain:'Örgütleme',mode:'sequence',title:'Olayı sıraya koy',prompt:'Açık ve mantıklı anlatmak için üç kartı sırala.',scenario:'Bir çocuk saksıdaki kuru toprağa su verdi. Bir süre sonra toprak nemlendi.',need:3,correct:'notice>water>result',choices:[{id:'result',label:'Toprağın nemlendiğini gördü.'},{id:'notice',label:'Toprağın kuru olduğunu fark etti.'},{id:'water',label:'Saksıya su verdi.'}]},
{id:'A1',domain:'Anlam',mode:'choice',title:'Kanıtı yakala',prompt:'Bu düşünceyi en iyi destekleyen bilgiyi seç.',scenario:'Düşünce: “Kütüphanede yüksek sesle konuşmak okumayı zorlaştırabilir.”',correct:'focus',choices:[{id:'focus',label:'Okuyan kişiler yüksek seste dikkatlerinin dağıldığını söylüyor.'},{id:'blue',label:'Kütüphanenin kapısı mavidir.'},{id:'shelf',label:'Kitaplar raflarda durur.'},{id:'clock',label:'Duvarda bir saat vardır.'}]},
{id:'R1',domain:'Örgütleme',mode:'choice',title:'Eksik bilgiyi bul',prompt:'Dinleyen kişinin cümleyi anlaması için en çok hangi bilgi eksik?',scenario:'Ece yalnızca şunu söyledi: “Onu oraya koyunca düştü.”',correct:'referent',choices:[{id:'referent',label:'Neyin, nereye konduğu'},{id:'weather',label:'Havanın nasıl olduğu'},{id:'color',label:'Ece’nin sevdiği renk'},{id:'day',label:'Haftanın hangi günü olduğu'}]},
{id:'G2',domain:'Gerekçelendirme',mode:'choice',title:'Sonucu kanıtla',prompt:'Mina’nın düşüncesini en güçlü destekleyen gözlemi seç.',scenario:'Mina bitkinin yapraklarının pencereye doğru eğildiğini gördü. Saksıyı çevirdi. İki gün sonra yapraklar yine pencereye dönmüştü. Mina “Bitki ışığın geldiği yöne yöneliyor.” dedi.',correct:'turn',choices:[{id:'turn',label:'Saksı çevrildikten sonra yaprakların yeniden pencereye yönelmesi'},{id:'pot',label:'Saksının yuvarlak olması'},{id:'green',label:'Yaprakların yeşil olması'},{id:'desk',label:'Saksının masada durması'}]},
{id:'G3',domain:'Gerekçelendirme',mode:'choice',title:'Fikrini savun',prompt:'Eren düşüncesini en açık ve kanıta dayalı nasıl savunur?',scenario:'Arda ve Eren bloklardan kule yapıyor. Arda daha çok blok eklemek istiyor. Eren kulenin sallandığını fark ediyor.',correct:'base',choices:[{id:'base',label:'Önce tabanı genişletelim; kule sallanıyor. Sağlamlaşınca daha çok blok ekleyebiliriz.'},{id:'mine',label:'Benim dediğim olsun.'},{id:'pretty',label:'Daha çok blok daha güzel görünür.'},{id:'none',label:'Bilmiyorum, rastgele yapalım.'}]},
{id:'O2',domain:'Örgütleme',mode:'sequence',title:'Nedeni sonuca bağla',prompt:'Üç cümleyi neden-sonuç ilişkisi kuracak şekilde sırala.',scenario:'Soru: “Çalışırken kapıyı neden kapattın?”',need:3,correct:'noise>effect>action',choices:[{id:'action',label:'Bu yüzden kapıyı kapattım.'},{id:'noise',label:'Koridordan çok ses geliyordu.'},{id:'effect',label:'Ses, çalışırken dikkatimi bölüyordu.'}]},
{id:'A2',domain:'Anlam',mode:'choice',title:'Özü yakala',prompt:'Metni en iyi özetleyen cümleyi seç.',scenario:'Bora sabah bisikletle okula gitmek istedi. Lastiğin havasının çok az olduğunu fark etti. Güvenli olmayacağını düşünüp o gün yürüdü. Akşam lastiği şişirdi.',correct:'safe',choices:[{id:'safe',label:'Bora güvenlik için planını değiştirdi ve bisikleti sonra hazırladı.'},{id:'walk',label:'Bora yürümeyi her zaman bisikletten daha çok sever.'},{id:'evening',label:'Bora yalnızca akşam dışarı çıkar.'},{id:'school',label:'Bora okula gitmedi.'}]},
{id:'A3',domain:'Anlam',mode:'choice',title:'Çelişkiyi bul',prompt:'Hangi cümle nottaki bilgiyle çelişiyor?',scenario:'Not: “Pazartesi fen kitabını getir. Deney salı günü yapılacak.”',correct:'wrongday',choices:[{id:'monday',label:'Fen kitabı pazartesi getirilecek.'},{id:'tuesday',label:'Deney salı günü yapılacak.'},{id:'wrongday',label:'Fen kitabı salı günü getirilecek.'},{id:'before',label:'Kitap deneyden önce sınıfta olacak.'}]},
{id:'G4',domain:'Gerekçelendirme',mode:'choice',title:'En güçlü gerekçe',prompt:'Bu öneriyi en güçlü hangi gerekçe destekler?',scenario:'Öneri: “Okul bahçesine bir gölgelik eklenmeli.” Öğle saatlerinde bahçedeki gölge alan çok küçük.',correct:'need',choices:[{id:'need',label:'Öğle arasında birçok öğrenci gölge arıyor ve mevcut alan herkese yetmiyor.'},{id:'blue',label:'Gölgelik mavi renkte yapılabilir.'},{id:'friend',label:'Bir arkadaşım gölgelikleri seviyor.'},{id:'large',label:'Bahçenin alanı büyüktür.'}]},
{id:'R2',domain:'Örgütleme',mode:'choice',title:'Mesajı netleştir',prompt:'Mesajı en açık hale getiren cümleyi seç.',scenario:'Öğretmen “Proje cuma günü teslim.” dedi. Öğrencinin ilk mesajı: “Onu sonra getiririm.”',correct:'clear',choices:[{id:'clear',label:'Projeyi cuma günü derse getireceğim.'},{id:'later',label:'Onu sonra getiririm.'},{id:'thing',label:'Şeyi o gün yaparım.'},{id:'maybe',label:'Belki bir ara getiririm.'}]},
{id:'U1',domain:'Üretim',mode:'open',title:'Açıkla',prompt:'Arkadaşına ne söyleyeceğini ve nedenini iki kısa cümleyle anlat.',scenario:'Sınıfta yere su dökülmüş. Bir arkadaşın koşarak kapıya gidiyor.'},
{id:'U2',domain:'Üretim',mode:'open',title:'Savun',prompt:'Birini seç ve kararını savun: bir neden ve o nedeni destekleyen bir örnek ya da bilgi ver.',scenario:'Teneffüste iki seçenek var: bahçede serbest oyun veya sınıfta sessiz masa oyunu. Hangisini seçerdin?'},
{id:'U3',domain:'Üretim',mode:'open',title:'Yeniden kur',prompt:'Belirsiz mesajı açık hale getir. Kim/ne, nereye ve sonra ne yapılacağı anlaşılır olsun.',scenario:'Belirsiz mesaj: “Onu oraya koy, sonra getir.”'}
];

function shuffled(a:Choice[]){const x=[...a];for(let i=x.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[x[i],x[j]]=[x[j],x[i]]}return x}
function icon(d:Domain){return d==='Gerekçelendirme'?<Quote/>:d==='Örgütleme'?<BrainCircuit/>:d==='Anlam'?<Sparkles/>:<PenLine/>}

export default function ExpressionLab({studentLabel,busy,onFinish,err,onActivity}:{studentLabel?:string;busy:boolean;onFinish:(value:string)=>void;err:string;onActivity:()=>void}){
const[idx,setIdx]=useState(0);const[selected,setSelected]=useState<string[]>([]);const[text,setText]=useState('');const[spoken,setSpoken]=useState(false);const[changes,setChanges]=useState(0);const[records,setRecords]=useState<Row[]>([]);const[breakMode,setBreakMode]=useState(false);const started=useRef(Date.now());const item=items[idx];const choices=useMemo(()=>shuffled(item.choices||[]),[item.id]);
const reset=()=>{setSelected([]);setText('');setSpoken(false);setChanges(0);started.current=Date.now()};
const choose=(id:string)=>{if(busy)return;onActivity();if(item.mode==='choice'){if(selected[0]&&selected[0]!==id)setChanges(v=>v+1);setSelected([id]);return}if(item.mode==='sequence'&&!selected.includes(id)&&selected.length<(item.need||1)){setSelected(v=>[...v,id]);setChanges(v=>v+1)}};
const answerValue=()=>item.mode==='open'?(spoken?'[SÖZLÜ ANLATIM]':text.trim().slice(0,120)):item.mode==='choice'?(selected[0]||''):selected.join('>');
const ready=item.mode==='open'?spoken||text.trim().length>=10:item.mode==='choice'?selected.length===1:selected.length===(item.need||1);
const score=():[number|null,number]=>{const ans=answerValue();if(item.mode==='open')return[null,0];if(item.mode==='choice')return[ans===item.correct?1:0,1];const exp=(item.correct||'').split('>'),got=ans.split('>');return[got.reduce((s,x,i)=>s+(x===exp[i]?1:0),0),exp.length]};
const encode=(rs:Row[])=>{const stat=(d:Domain)=>{const x=rs.filter(r=>r.domain===d&&r.max>0);return x.reduce((s,r)=>s+(r.score||0),0)+'/'+x.reduce((s,r)=>s+r.max,0)};const raw=rs.map(r=>r.id+'~'+encodeURIComponent(r.answer).slice(0,260)+'~'+(r.score==null?'R':r.score)+'~'+r.max+'~'+r.ms+'~'+r.changes+'~'+r.modality).join(',');return 'DX|n='+rs.length+'|reason='+stat('Gerekçelendirme')+'|organ='+stat('Örgütleme')+'|meaning='+stat('Anlam')+'|open='+rs.filter(r=>r.max===0&&r.answer!=='SKIP').length+'|spoken='+rs.filter(r=>r.modality==='spoken'&&r.answer!=='SKIP').length+'|r='+raw};
const next=(skip=false)=>{if((!ready&&!skip)||busy)return;const[s,m]=skip?[null,0]:score();const row:Row={id:item.id,domain:item.domain,answer:skip?'SKIP':answerValue(),score:s,max:m,ms:Math.max(0,Date.now()-started.current),changes,modality:skip?'skipped':item.mode==='open'?(spoken?'spoken':'written'):'structured'};const rs=[...records,row];if(idx===items.length-1){onFinish(encode(rs));return}setRecords(rs);if(idx===6){setBreakMode(true);return}setIdx(v=>v+1);reset()};
const resume=()=>{setBreakMode(false);setIdx(7);reset()};const undo=()=>{if(!selected.length||busy)return;onActivity();setSelected(v=>v.slice(0,-1));setChanges(v=>v+1)};
if(breakMode)return <div className='dx-shell'><header className='dx-top'><div><b>CZA</b><span>Çelik Zihin Akademisi</span></div><em>Anlat • Savun • Yeniden Kur</em></header><main className='dx-main'><section className='dx-break'><div><MessageCircle/></div><h1>İlk anlatım turu tamam.</h1><p>Şimdi bilgiyi özetleyecek, çelişkiyi yakalayacak ve kendi düşünceni üreterek daha açık anlatacaksın.</p><span>7 görev tamamlandı · 7 görev kaldı</span><button onClick={resume}>İkinci tura geç <b>→</b></button></section></main></div>;
return <div className='dx-shell'><header className='dx-top'><div><b>CZA</b><span>Çelik Zihin Akademisi</span></div><em>Anlat • Savun • Yeniden Kur</em></header><main className='dx-main'>{err&&<div className='dx-error'>{err}</div>}<section className='dx-card'><div className='dx-progress'><strong>{idx+1}<small>/14</small></strong><div><i style={{width:((idx+1)/14*100)+'%'}}/></div><span>{item.domain}</span></div><div className='dx-head'><div><span>CZA DİL ÜRETİM LABORATUVARI</span><h1>{item.title}</h1><p>{item.prompt}</p></div><div>{icon(item.domain)}</div></div><div className='dx-stage'><div className='dx-scenario'><MessageCircle/><div><strong>Durum</strong><p>{item.scenario}</p></div></div>{item.mode==='open'?<div className='dx-open'><div className='dx-mode'><button type='button' className={!spoken?'active':''} onClick={()=>{onActivity();setSpoken(false)}}><PenLine/> Yazacağım</button><button type='button' className={spoken?'active':''} onClick={()=>{onActivity();setSpoken(true);setText('')}}><MessageCircle/> Sözlü anlatacağım</button></div>{spoken?<div className='dx-spoken'><CheckCircle2/><strong>Sözlü anlatım seçildi.</strong><small>Yanındaki eğitmen cevabının içeriğini gözlem notuna kaydeder. Bu açık yanıt otomatik doğru/yanlış puanı almaz.</small></div>:<><textarea maxLength={120} value={text} onChange={e=>{onActivity();setText(e.target.value)}} placeholder='Kısa ama açık anlat…'/><small>{text.length}/120 · Yazım hızından çok düşüncenin açıklığı önemlidir.</small></>}</div>:<div className={'dx-options '+item.mode}>{choices.map(c=><button type='button' key={c.id} className={selected.includes(c.id)?'selected':''} aria-pressed={selected.includes(c.id)} onClick={()=>choose(c.id)}><span>{c.label}</span>{selected.includes(c.id)&&item.mode==='sequence'&&<b>{selected.indexOf(c.id)+1}</b>}</button>)}</div>}{item.mode==='sequence'&&<div className='dx-seq'><div><strong>{selected.length} / {item.need} adım</strong><small>Sıra önemlidir. Son seçimini geri alabilirsin.</small></div><button type='button' disabled={!selected.length||busy} onClick={undo}><RotateCcw/> Son seçimi geri al</button></div>}</div><div className='dx-bottom'><div><BrainCircuit/><span><strong>Doğru/yanlış geri bildirimi yok.</strong><small>Seçim değişiklikleri, sıra, süre ve açık yanıt biçimi ayrı kanıt olarak saklanır.</small></span></div><div style={{display:'flex',gap:9,flexWrap:'wrap',justifyContent:'flex-end'}}><button type='button' className='cza-btn cza-soft' disabled={busy} onClick={()=>next(true)}>Bu soruyu geç</button><button className='dx-next' disabled={!ready||busy} onClick={()=>next(false)}>{busy?'Kaydediliyor…':idx===13?'Anlatım Turunu Tamamla':'Sonraki Görev'} <span>→</span></button></div></div><footer className='dx-footer'><span>{studentLabel||'Öğrenci'} · 14 mikro-görev</span><span>gerekçe • örgütleme • anlam • üretim</span></footer></section></main></div>;
}

