import html2canvas from 'html2canvas';
import { jsPDF } from 'jspdf';
export type ParentPdfArea = {id:number;title:string;status:string;academic:string;family:string;daily:string;teacher?:string;teacherStructured:string[];holistic:string;nextStep:string;evidence:string};
export type ParentPdfRoute = {order:number;title:string;status:string;why:string;methods:string[];rationale:string;target:string;home:string};
export type ParentReportPdfData = {student:string;assessmentDate?:string|null;isFinal:boolean;coverage:string;coverageLabel:string;attemptCount:number;learningResponse:string;summary:string[];strengths:string[];developing:string[];priorities:string[];strategy:string[];teacherNotes:Array<{title:string;note:string}>;areas:ParentPdfArea[];routes:ParentPdfRoute[];disclaimer:string};
const paragraph=(root:HTMLElement,label:string,value:string)=>{if(!value)return;const p=document.createElement('p');p.style.cssText='margin:9px 0;line-height:1.5;overflow-wrap:anywhere';const b=document.createElement('strong');b.textContent=label+' ';p.append(b,document.createTextNode(value));root.append(p)};
const list=(root:HTMLElement,label:string,items:string[])=>{if(!items.length)return;const h=document.createElement('h2');h.textContent=label;root.append(h);for(const item of items){const p=document.createElement('p');p.textContent='• '+item;p.style.cssText='margin:6px 0;line-height:1.45;overflow-wrap:anywhere';root.append(p)}};
async function renderPage(pdf:jsPDF,build:(root:HTMLElement)=>void,index:number){const root=document.createElement('article');root.style.cssText='position:fixed;left:0;top:0;width:790px;box-sizing:border-box;padding:48px 56px;background:#fff;color:#173830;font:16px Arial,sans-serif;z-index:-1';const brand=document.createElement('div');brand.textContent='CZA • BAŞLANGIÇ DEĞERLENDİRMESİ';brand.style.cssText='font-size:14px;font-weight:700;color:#23695b;border-bottom:3px solid #23695b;padding-bottom:12px;margin-bottom:24px';root.append(brand);build(root);document.body.append(root);try{const canvas=await html2canvas(root,{backgroundColor:'#ffffff',scale:1.5,logging:false,width:790,height:Math.max(1120,root.scrollHeight)});const pageHeight=1120*canvas.width/790;let offset=0;while(offset<canvas.height){if(index||offset)pdf.addPage();const slice=document.createElement('canvas');slice.width=canvas.width;slice.height=Math.min(pageHeight,canvas.height-offset);slice.getContext('2d')!.drawImage(canvas,0,-offset);pdf.addImage(slice.toDataURL('image/png'),'PNG',0,0,210,slice.height/canvas.width*210);offset+=slice.height;}}finally{root.remove()}}
export async function downloadParentReportPdf(data:ParentReportPdfData){const pdf=new jsPDF({unit:'mm',format:'a4',compress:true});let index=0;await renderPage(pdf,r=>{const h=document.createElement('h1');h.textContent='Eğitmen değerlendirme raporu';r.append(h);paragraph(r,'Öğrenci:',data.student);paragraph(r,'Değerlendirme tarihi:',data.assessmentDate?new Date(data.assessmentDate).toLocaleDateString('tr-TR'):'Kayıtta bulunmuyor');paragraph(r,'Tamamlanma durumu:',data.isFinal?'Tamamlandı':'Devam ediyor');paragraph(r,'Kapsam:',data.coverage+' · '+data.coverageLabel);paragraph(r,'Kaydedilen görev:',String(data.attemptCount));paragraph(r,'Öğrenme yanıtı:',data.learningResponse);list(r,'Özet',data.summary);list(r,'Güçlü alanlar',data.strengths);list(r,'Gelişen alanlar',data.developing);list(r,'Öncelikler',data.priorities);paragraph(r,'Açıklama:',data.disclaimer)},index++);
for(const area of data.areas)await renderPage(pdf,r=>{const h=document.createElement('h1');h.textContent=`${area.id}. ${area.title}`;r.append(h);paragraph(r,'Durum:',area.status);paragraph(r,'Akademik gözlem:',area.academic);paragraph(r,'Aile için:',area.family);paragraph(r,'Günlük yaşam:',area.daily);paragraph(r,'Öğretmen:',area.teacher||'Kayıtta bulunmuyor');list(r,'Yapılandırılmış gözlem',area.teacherStructured);paragraph(r,'Bütüncül değerlendirme:',area.holistic);paragraph(r,'Sonraki adım:',area.nextStep);paragraph(r,'Kanıt:',area.evidence)},index++);
for(const route of data.routes)await renderPage(pdf,r=>{const h=document.createElement('h1');h.textContent=`Yol haritası ${route.order}: ${route.title}`;r.append(h);paragraph(r,'Durum:',route.status);paragraph(r,'Neden:',route.why);list(r,'Yöntemler',route.methods);paragraph(r,'Dayanak:',route.rationale);paragraph(r,'Hedef:',route.target);paragraph(r,'Evde:',route.home)},index++);
const safe=data.student.normalize('NFKD').replace(/[^a-zA-Z0-9-]+/g,'-').slice(0,40)||'ogrenci';pdf.save(`CZA-degerlendirme-${safe}.pdf`)}
