import { useRef, useState } from 'react';
import { KeyRound, Lightbulb, Route, Shapes, Shuffle, Sparkles, Umbrella } from 'lucide-react';

type Domain='Kural'|'Esneklik'|'Görsel-Uzamsal'|'Problem'|'Üretim';
type Mode='single'|'multi'|'build'|'text';
type TokenShape='circle'|'square'|'triangle'|'star'|'diamond';
type Tone='gold'|'blue'|'coral'|'violet'|'mint';
type Choice={id:string;label:string;shape?:TokenShape;tone?:Tone;cat?:string};
type Item={id:string;domain:Domain;mode:Mode;title:string;prompt:string;choices?:Choice[];need?:number};
type RecordRow={id:string;domain:Domain;answer:string;score:number;max:number;ms:number;changes:number};

const tokenChoices:Choice[]=[{id:'gold-star',label:'Altın yıldız',shape:'star',tone:'gold'},{id:'blue-circle',label:'Mavi daire',shape:'circle',tone:'blue'},{id:'coral-square',label:'Mercan kare',shape:'square',tone:'coral'},{id:'violet-triangle',label:'Mor üçgen',shape:'triangle',tone:'violet'}];
const items:Item[]=[
{id:'R1',domain:'Kural',mode:'single',title:'Gizli ritmi yakala',prompt:'Şekil ve rengi birlikte izle. Sıradaki kart hangisi?',choices:[{id:'blue-circle',label:'Mavi daire',shape:'circle',tone:'blue'},{id:'gold-circle',label:'Altın daire',shape:'circle',tone:'gold'},{id:'blue-star',label:'Mavi yıldız',shape:'star',tone:'blue'},{id:'gold-star',label:'Altın yıldız',shape:'star',tone:'gold'}]},
{id:'R2',domain:'Kural',mode:'single',title:'İki kural aynı anda',prompt:'Renk ve büyüklük döngüsünü birlikte düşün. Eksik kartı seç.',choices:[{id:'red-small',label:'Küçük mercan daire',shape:'circle',tone:'coral'},{id:'red-large',label:'Büyük mercan daire',shape:'circle',tone:'coral'},{id:'blue-small',label:'Küçük mavi kare',shape:'square',tone:'blue'},{id:'blue-large',label:'Büyük mavi kare',shape:'square',tone:'blue'}]},
{id:'S1',domain:'Görsel-Uzamsal',mode:'single',title:'Zihninde döndür',prompt:'Ok her adımda çeyrek tur dönüyor. Sıradaki yönü bul.',choices:[{id:'up',label:'↑'},{id:'right',label:'→'},{id:'down',label:'↓'},{id:'left',label:'←'}]},
{id:'S2',domain:'Görsel-Uzamsal',mode:'single',title:'Aynadaki parça',prompt:'Kesikli çizgi aynadır. Soldaki L parçasının sağ-sol yönü ters dönünce nasıl görünür?',choices:[{id:'A',label:'A'},{id:'B',label:'B'},{id:'C',label:'C'},{id:'D',label:'D'}]},
{id:'F1',domain:'Esneklik',mode:'multi',title:'Aynı hedefe iki yol',prompt:'Dört sayı seç. Seçtiğin sayılar iki farklı ikili halinde 10 yapabilsin.',need:4,choices:['1','2','3','7','8','9'].map(x=>({id:x,label:x}))},
{id:'F2',domain:'Esneklik',mode:'multi',title:'Aynı parçalar, iki farklı düzen',prompt:'Bu kartları iki farklı mantıklı kuralla gruplayabiliriz. İki kural seç.',need:2,choices:[{id:'renk',label:'Rengine göre'},{id:'sekil',label:'Şekline göre'},{id:'boyut',label:'Boyutuna göre'},{id:'yon',label:'Yönüne göre'}]},
{id:'P1',domain:'Görsel-Uzamsal',mode:'single',title:'Kısa ve güvenli rota',prompt:'S noktasından H noktasına git. Kırmızı engellere basma ve tam 5 hamlede hedefe ulaşan yolu seç.',choices:[{id:'A',label:'↓ ↓ → → →'},{id:'B',label:'→ → ↓ ↓ →'},{id:'C',label:'↓ → ↓ → →'},{id:'D',label:'↓ ↓ → ↑ →'}]},
{id:'S3',domain:'Görsel-Uzamsal',mode:'single',title:'Parçayı tamamla',prompt:'Her satırda ve sütunda aynı iki kart birer kez bulunuyor. Eksik kart hangisi?',choices:[{id:'gold-circle',label:'Altın daire',shape:'circle',tone:'gold'},{id:'blue-circle',label:'Mavi daire',shape:'circle',tone:'blue'},{id:'gold-square',label:'Altın kare',shape:'square',tone:'gold'},{id:'violet-triangle',label:'Mor üçgen',shape:'triangle',tone:'violet'}]},
{id:'P2',domain:'Problem',mode:'multi',title:'Koltuğun altındaki topu kurtar',prompt:'Top koltuğun altında yaklaşık 60 cm içeride. Elin yetişmiyor ve topu daha içeri itmeden kendine doğru getirmen gerekiyor. Yalnız iki araç seçebilirsin. Hangilerini birlikte kullanırsın?',need:2,choices:[{id:'cubuk',label:'Uzun çubuk · 70 cm'},{id:'bant',label:'Yapışkan bant'},{id:'cetvel',label:'Kısa cetvel · 20 cm'},{id:'tabak',label:'Kağıt tabak'},{id:'sunger',label:'Yumuşak sünger'}]},
{id:'F3',domain:'Esneklik',mode:'multi',title:'Bir nesne, birçok fikir',prompt:'Bir kağıt bardağı içmek dışında üç farklı işe dönüştür. Birbirinden gerçekten farklı üç fikir seç.',need:3,choices:[{id:'saksi',label:'Mini saksı',cat:'doga'},{id:'davul',label:'Ritim davulu',cat:'muzik'},{id:'kalemlik',label:'Kalemlik',cat:'duzen'},{id:'kukla',label:'Kukla gövdesi',cat:'oyun'},{id:'kule',label:'Kule parçası',cat:'yapi'},{id:'icmek',label:'Su içmek',cat:'normal'}]},
{id:'F4',domain:'Esneklik',mode:'build',title:'Kendi desenini kur',prompt:'İlk 3 kartla bir desen kur. Sonraki 3 kartta aynı üçlü deseni aynı sırayla bir kez daha tekrar et.',choices:tokenChoices.slice(0,3)},
{id:'P3',domain:'Problem',mode:'single',title:'Plan B zamanı',prompt:'Köprü kapalı ve kırmızı bölge tehlikeli. Hedefe ulaşmak için iki koşulu da bozmayan planı seç.',choices:[{id:'A',label:'Kapalı köprüye geri dön'},{id:'B',label:'Kırmızı tehlike alanından kestirme geç'},{id:'C',label:'Biraz uzun ama açık ve güvenli yan yolu kullan'},{id:'D',label:'Hedefin ters yönüne ilerle'}]},
{id:'R3',domain:'Kural',mode:'single',title:'Kural değişti!',prompt:'Yeni kural: renge değil şekle bak. Mavi üçgenle aynı şekli taşıyan kartı seç; renk farklı olabilir.',choices:[{id:'gold-triangle',label:'Altın üçgen',shape:'triangle',tone:'gold'},{id:'blue-circle',label:'Mavi daire',shape:'circle',tone:'blue'},{id:'violet-star',label:'Mor yıldız',shape:'star',tone:'violet'},{id:'coral-square',label:'Mercan kare',shape:'square',tone:'coral'}]},
{id:'R4',domain:'Kural',mode:'single',title:'Büyük transfer',prompt:'Şekil daire-kare diye sırayla değişiyor; renkler altın-mavi-mercan-mor diye dönüyor. Sıradaki kartı seç.',choices:[{id:'blue-square',label:'Mavi kare',shape:'square',tone:'blue'},{id:'gold-square',label:'Altın kare',shape:'square',tone:'gold'},{id:'blue-triangle',label:'Mavi üçgen',shape:'triangle',tone:'blue'},{id:'coral-circle',label:'Mercan daire',shape:'circle',tone:'coral'}]},
{id:'O1',domain:'Üretim',mode:'text',title:'İki uzak fikri buluştur',prompt:'Şemsiye ile anahtarı tek bir yeni icatta birleştir. Gerçek olmak zorunda değil; ne işe yaradığını bir cümleyle anlat.'},
{id:'O2',domain:'Üretim',mode:'text',title:'Kısıtlı icat görevi',prompt:'Kalemin sürekli masadan yuvarlanıp düşüyor. Yeni eşya almadan yalnızca bir kağıt ve bir lastik bant kullanarak kalemi masada tutacak bir çözüm tasarla.'}
];

function Token({shape='circle',tone='blue',large=false}:{shape?:TokenShape;tone?:Tone;large?:boolean}){return <span className={'pl-token '+shape+' '+tone+(large?' large':'')} aria-hidden='true'/>}
function MissionVisual({id,build}:{id:string;build:string[]}){
if(id==='R1')return <div className='pl-seq'><Token shape='star' tone='gold'/><Token shape='circle' tone='blue'/><Token shape='star' tone='gold'/><Token shape='circle' tone='blue'/><b>?</b></div>;
if(id==='R2')return <div className='pl-seq size-seq'><span><Token shape='circle' tone='coral'/><i>K</i></span><span><Token shape='circle' tone='coral' large/><i>B</i></span><span><Token shape='square' tone='blue'/><i>K</i></span><span><Token shape='square' tone='blue' large/><i>B</i></span><span><Token shape='circle' tone='coral'/><i>K</i></span><b>?</b></div>;
if(id==='S1')return <div className='pl-arrows'><span>↑</span><span>→</span><span>↓</span><b>?</b></div>;
if(id==='S2')return <div className='pl-mirror'><div className='pl-lshape'/><span className='pl-mirror-line'/><b>?</b></div>;
if(id==='F1')return <div className='pl-goal'><span>10</span><i>iki farklı yol</i></div>;
if(id==='F2')return <div className='pl-token-cloud'><Token shape='circle' tone='gold'/><Token shape='square' tone='gold'/><Token shape='circle' tone='blue'/><Token shape='square' tone='blue'/><Token shape='circle' tone='violet'/><Token shape='square' tone='violet'/></div>;
if(id==='P1')return <div className='pl-route-grid'><i className='start'>S</i><i/><i className='block'/><i/><i/><i className='block'/><i/><i/><i/><i/><i/><i className='goal'>H</i></div>;
if(id==='S3')return <div className='pl-matrix'><Token shape='circle' tone='gold'/><Token shape='square' tone='blue'/><Token shape='square' tone='blue'/><b>?</b></div>;
if(id==='P2')return <div className='pl-tool-scene'><svg viewBox='0 0 620 220' role='img' aria-label='Top koltuğun altında yaklaşık 60 santimetre içeride' style={{width:'100%',maxWidth:620,height:'190px'}}><rect x='120' y='42' width='400' height='78' rx='28' fill='#55b9c8'/><rect x='104' y='98' width='432' height='42' rx='18' fill='#277f9b'/><rect x='140' y='136' width='30' height='48' rx='8' fill='#173d59'/><rect x='470' y='136' width='30' height='48' rx='8' fill='#173d59'/><circle cx='438' cy='171' r='20' fill='#f4c542' stroke='#b88311' strokeWidth='4'/><line x1='178' y1='198' x2='438' y2='198' stroke='#ef8c72' strokeWidth='4' strokeDasharray='10 8'/><path d='M178 190 L178 206 M438 190 L438 206' stroke='#ef8c72' strokeWidth='4'/><text x='308' y='190' textAnchor='middle' fontSize='18' fontWeight='900' fill='#8b4d3e'>60 cm</text><text x='92' y='176' textAnchor='middle' fontSize='14' fontWeight='900' fill='#6d7f8c'>EL YETİŞMİYOR</text></svg></div>;
if(id==='F3')return <div className='pl-paper-cup'><span/><i>KAĞIT BARDAK</i><strong>İçmek dışında neye dönüşebilir?</strong></div>;if(id==='O2')return <div className='pl-design-problem'><span className='pencil'/><span className='paper'/><span className='band'/><strong>Kalemi masada tut</strong></div>;
if(id==='F4')return <div className='pl-build-preview'>{Array.from({length:6},(_,i)=>{const c=tokenChoices.find(x=>x.id===build[i]);return c?<Token key={i} shape={c.shape} tone={c.tone}/>:<b key={i}>{i+1}</b>})}</div>;
if(id==='P3')return <div className='pl-planb'><Route/><span>×</span><Shuffle/><strong>PLAN B</strong></div>;
if(id==='R3')return <div className='pl-switch-rule'><div><small>ESKİ: RENK</small><Token shape='circle' tone='gold'/><span>→</span><Token shape='square' tone='gold'/></div><b>↻ KURAL DEĞİŞTİ</b><div><small>YENİ: ŞEKİL</small><Token shape='triangle' tone='blue'/><span>→</span><strong>?</strong></div></div>;
if(id==='O1')return <div className='pl-idea-pair'><Umbrella/><Sparkles/><KeyRound/></div>;
return <div className='pl-seq transfer'><Token shape='circle' tone='gold'/><Token shape='square' tone='blue'/><Token shape='circle' tone='coral'/><Token shape='square' tone='violet'/><Token shape='circle' tone='gold'/><b>?</b></div>;
}

function scoreItem(item:Item,answer:string[]):[number,number]{
const a=answer;
if(item.id==='R1')return[a[0]==='gold-star'?1:0,1];
if(item.id==='R2')return[a[0]==='red-large'?1:0,1];
if(item.id==='S1')return[a[0]==='left'?1:0,1];
if(item.id==='S2')return[a[0]==='B'?1:0,1];
if(item.id==='F1'){const nums=a.map(Number);let pairs=0;for(let i=0;i<nums.length;i++)for(let j=i+1;j<nums.length;j++)if(nums[i]+nums[j]===10)pairs++;return[Math.min(2,pairs),2]}
if(item.id==='F2')return[a.filter(x=>x==='renk'||x==='sekil').length,2];
if(item.id==='P1')return[a[0]==='A'?1:0,1];
if(item.id==='S3')return[a[0]==='gold-circle'?1:0,1];
if(item.id==='P2'){const s=new Set(a);return[s.has('cubuk')&&s.has('bant')?2:s.has('cubuk')||s.has('bant')?1:0,2]}
if(item.id==='F3'){const cats=new Set(a.map(id=>item.choices?.find(c=>c.id===id)?.cat).filter(x=>x&&x!=='normal'));return[Math.min(3,cats.size),3]}
if(item.id==='F4'){if(a.length!==6)return[0,2];const same=a.slice(0,3).every((x,i)=>x===a[i+3]);if(!same)return[0,2];return[new Set(a.slice(0,3)).size>=2?2:1,2]}
if(item.id==='P3')return[a[0]==='C'?1:0,1];
if(item.id==='R3')return[a[0]==='gold-triangle'?1:0,1];
if(item.id==='R4')return[a[0]==='blue-square'?1:0,1];
return[0,0];
}

export default function PotentialLab({studentLabel,busy,onFinish,err,onActivity}:{studentLabel?:string;busy:boolean;onFinish:(value:string)=>void;err:string;onActivity:()=>void}){
const[idx,setIdx]=useState(0);const[selected,setSelected]=useState<string[]>([]);const[text,setText]=useState('');const[changes,setChanges]=useState(0);const[records,setRecords]=useState<RecordRow[]>([]);const[breakMode,setBreakMode]=useState(false);const started=useRef(Date.now());const item=items[idx];
const choose=(id:string)=>{if(busy)return;onActivity();if(item.mode==='single'){if(selected[0]&&selected[0]!==id)setChanges(v=>v+1);setSelected([id]);return}if(item.mode==='multi'){const exists=selected.includes(id);const next=exists?selected.filter(x=>x!==id):selected.length<(item.need||1)?[...selected,id]:selected;if(next.join(',')!==selected.join(','))setChanges(v=>v+1);setSelected(next);return}if(item.mode==='build'&&selected.length<6){setSelected(v=>[...v,id]);setChanges(v=>v+1)}};
const ready=item.mode==='text'?text.trim().length>=4:item.mode==='build'?selected.length===6:item.mode==='multi'?selected.length===(item.need||1):selected.length===1;
const encode=(rs:RecordRow[])=>{const stat=(d:Domain)=>{const x=rs.filter(r=>r.domain===d);return[x.reduce((s,r)=>s+r.score,0),x.reduce((s,r)=>s+r.max,0)]};const rule=stat('Kural'),flex=stat('Esneklik'),spatial=stat('Görsel-Uzamsal'),plan=stat('Problem');const raw=rs.map(r=>r.id+'.'+encodeURIComponent(r.answer.slice(0,80))+'.'+r.score+'-'+r.max+'.'+r.ms+'.'+r.changes).join(',');return 'PL|n='+rs.length+'|rule='+rule[0]+'/'+rule[1]+'|flex='+flex[0]+'/'+flex[1]+'|spatial='+spatial[0]+'/'+spatial[1]+'|plan='+plan[0]+'/'+plan[1]+'|open='+rs.filter(r=>r.domain==='Üretim').length+'|r='+raw};
const next=(skip=false)=>{if((!ready&&!skip)||busy)return;const ans=skip?'SKIP':item.mode==='text'?text.trim().replace(/[|\n\r]+/g,' ').slice(0,90):selected.join('+');const[score,max]=skip?[0,0]:scoreItem(item,selected);const row:RecordRow={id:item.id,domain:item.domain,answer:ans,score,max,ms:Math.max(0,Date.now()-started.current),changes};const rs=[...records,row];if(idx===items.length-1){onFinish(encode(rs));return}setRecords(rs);if(idx===7){setBreakMode(true);return}setIdx(i=>i+1);setSelected([]);setText('');setChanges(0);started.current=Date.now()};
const resume=()=>{setBreakMode(false);setIdx(8);setSelected([]);setText('');setChanges(0);started.current=Date.now()};
if(breakMode)return <div className='pl-shell'><header className='pl-top'><div><b>CZA</b><span>Çelik Zihin Akademisi</span></div><em>Zihin Sıçraması</em></header><main className='pl-main'><section className='pl-break'><div className='pl-break-orb'><Lightbulb/></div><h1>Zihnin yön değiştirdi.</h1><p>İlk bölüm tamam. Şimdi tek doğru yolu aramak yerine farklı yollar üretme zamanı.</p><div><span>8 görev tamamlandı</span><span>8 yeni keşif kaldı</span></div><button onClick={resume}>Hazırım, ikinci bölüme geç <b>→</b></button></section></main></div>;
return <div className='pl-shell'><header className='pl-top'><div><b>CZA</b><span>Çelik Zihin Akademisi</span></div><em>Zihin Sıçraması · Potansiyel Laboratuvarı</em></header><main className='pl-main'>{err&&<div className='pl-error'>{err}</div>}<section className='pl-card'><div className='pl-progress'><strong>{idx+1}<small>/16</small></strong><div><i style={{width:((idx+1)/16*100)+'%'}}/></div><span>{item.domain}</span></div><div className='pl-head'><div><span className='pl-kicker'>CZA ZİHİN SIÇRAMASI</span><h1>{item.title}</h1><p>{item.prompt}</p></div><div className='pl-head-icon'>{item.domain==='Kural'?<Shuffle/>:item.domain==='Görsel-Uzamsal'?<Shapes/>:item.domain==='Problem'?<Route/>:item.domain==='Üretim'?<Lightbulb/>:<Sparkles/>}</div></div><div className='pl-stage'><MissionVisual id={item.id} build={selected}/>{item.mode==='text'?<div className='pl-text-wrap'><textarea maxLength={90} value={text} onChange={e=>{onActivity();setText(e.target.value)}} placeholder='Kısa fikrini buraya yaz…' aria-label='Yaratıcı fikir'/><span>{text.length}/90</span></div>:<div className={'pl-options '+item.mode}>{item.choices?.map(c=><button type='button' key={c.id} className={selected.includes(c.id)?'selected':''} onClick={()=>choose(c.id)} aria-pressed={selected.includes(c.id)}>{item.id==='S2'?<><span className={'pl-mirror-choice '+(c.id==='A'?'lb':c.id==='B'?'rb':c.id==='C'?'lt':'rt')}/><small>{c.id}</small></>:c.shape?<><Token shape={c.shape} tone={c.tone}/><small>{c.label}</small></>:<span>{c.label}</span>}{selected.includes(c.id)&&<b>✓</b>}</button>)}</div>}{item.mode==='build'&&<button className='pl-undo' disabled={!selected.length} onClick={()=>{setSelected(v=>v.slice(0,-1));setChanges(v=>v+1)}}>Son kartı geri al</button>}</div><div className='pl-bottom'><div className='pl-note'><Sparkles/><div><strong>{item.domain==='Üretim'?'Burada tek doğru cevap yok.':'Doğru/yanlış işareti göstermiyoruz.'}</strong><small>{item.domain==='Üretim'?'Fikrinin farklılığı eğitmen gözlemiyle birlikte yorumlanır.':'Hızdan çok kullandığın yol, değişikliklerin ve çözüm biçimin önemlidir.'}</small></div></div><div style={{display:'flex',gap:9,flexWrap:'wrap',justifyContent:'flex-end'}}><button type='button' className='cza-btn cza-soft' disabled={busy} onClick={()=>next(true)}>Bu soruyu geç</button><button className='pl-next' disabled={!ready||busy} onClick={()=>next(false)}>{busy?'Kaydediliyor…':idx===15?'Laboratuvarı Tamamla':'Sonraki Keşif'} <span>→</span></button></div></div><footer className='pl-footer'><span>{studentLabel||'Öğrenci'} · 16 farklı düşünme görevi</span><span>kural • esneklik • mekânsal düşünme • problem çözme • özgün üretim</span></footer></section></main></div>;
}

