import { useMemo, useRef, useState } from 'react';
import { BookOpenCheck, BrainCircuit, CheckCircle2, Gauge, Play, ShieldCheck } from 'lucide-react';

type Choice={id:string;label:string};
type Item={id:string;title:string;text:string;question:string;correct:string;choices:Choice[]};
type Row={id:string;answer:string;correct:boolean;words:number;readMs:number;questionMs:number;changes:number};

const items:Item[]=[
{id:'R1',title:'Sakin başla',text:'Küçük kuş pencerenin önündeki dala kondu.',question:'Kuş nereye kondu?',correct:'branch',choices:[{id:'roof',label:'Çatıya'},{id:'branch',label:'Dala'},{id:'table',label:'Masaya'},{id:'inside',label:'Pencerenin içine'}]},
{id:'R2',title:'Noktada dur',text:'Yağmur başladı. Çocuk kapüşonunu taktı ve yürümeye devam etti.',question:'Çocuk kapüşonunu neden taktı?',correct:'rain',choices:[{id:'sun',label:'Güneş çıktığı için'},{id:'rain',label:'Yağmur başladığı için'},{id:'bag',label:'Çantası ağır olduğu için'},{id:'game',label:'Oyun başladığı için'}]},
{id:'R3',title:'Soru ve ünlemi hisset',text:'Kutunun içinde ne var? Kapağı açınca üç renkli kalem gördüm!',question:'Kutudan ne çıktı?',correct:'pencils',choices:[{id:'books',label:'Üç kitap'},{id:'pencils',label:'Üç renkli kalem'},{id:'balls',label:'İki top'},{id:'keys',label:'Bir anahtar'}]},
{id:'R4',title:'Cümleleri bağla',text:'Mete sabah pencereden dışarı baktı. Bahçedeki yapraklar ıslaktı, bu yüzden şemsiyesini yanına aldı.',question:'Şemsiye neden yanına alındı?',correct:'wet',choices:[{id:'wet',label:'Yağmur ihtimalini düşündüğü için'},{id:'toy',label:'Oyun oynamak için'},{id:'shade',label:'Odayı karartmak için'},{id:'gift',label:'Birine vermek için'}]},
{id:'R5',title:'Nedeni takip et',text:'Okul bahçesindeki küçük fide eğilmişti. Çocuklar toprağın çok kuru olduğunu fark etti, su getirdi ve fideyi dikkatlice suladı. Bir süre sonra yapraklar dikleşti.',question:'Çocuklar fideyi neden suladı?',correct:'dry',choices:[{id:'dry',label:'Toprak çok kuru olduğu için'},{id:'wind',label:'Rüzgâr estiği için'},{id:'bell',label:'Zil çaldığı için'},{id:'paint',label:'Saksıyı boyamak için'}]},
{id:'R6',title:'Konuşmayı doğal oku',text:'“Sence oyun şimdi başlar mı?” diye sordu. “Önce herkes hazır olsun, sonra başlayalım!” yanıtı geldi.',question:'Oyundan önce ne olması isteniyor?',correct:'ready',choices:[{id:'ready',label:'Herkesin hazır olması'},{id:'leave',label:'Herkesin sınıftan çıkması'},{id:'sleep',label:'Biraz dinlenilmesi'},{id:'quiet',label:'Hiç konuşulmaması'}]},
{id:'R7',title:'İpucundan çıkar',text:'Sabah gökyüzü açıktı. Öğleden sonra koyu bulutlar hızla çoğaldı, rüzgâr güçlendi. Sınıftaki açık pencereler kapatıldı ve dışarıdaki kâğıtlar içeri alındı.',question:'Pencereler neden kapatılmış olabilir?',correct:'storm',choices:[{id:'storm',label:'Yağmur ve güçlü rüzgâr yaklaşabileceği için'},{id:'cold',label:'Sınıfta ders bittiği için'},{id:'paint',label:'Pencereler boyanacağı için'},{id:'dark',label:'Işık fazla geldiği için'}]},
{id:'R8',title:'Yeni metne transfer',text:'Sınıf kitaplığındaki bazı kitaplar sürekli yanlış rafa dönüyordu. Öğrenciler raflara renkli konu etiketleri hazırladı ve kitapları bu etiketlere göre yerleştirdi. Bir hafta sonra aranan kitaplar daha hızlı bulundu ve raflar daha düzenli kaldı.',question:'Metnin ana fikrine en uygun cümle hangisi?',correct:'system',choices:[{id:'system',label:'Basit bir düzenleme sistemi aramayı kolaylaştırabilir.'},{id:'color',label:'Her kitabın kapağı aynı renkte olmalıdır.'},{id:'week',label:'Kitaplar yalnız bir hafta kullanılmalıdır.'},{id:'few',label:'Kitaplıkta az kitap bulunmalıdır.'}]}
];

function shuffled(a:Choice[]){const x=[...a];for(let i=x.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[x[i],x[j]]=[x[j],x[i]]}return x}
function wordCount(text:string){return text.trim().split(/\s+/).length}

export default function ReadingFluencyLab({studentLabel,busy,onFinish,err,onActivity}:{studentLabel?:string;busy:boolean;onFinish:(value:string)=>void;err:string;onActivity:()=>void}){
const[idx,setIdx]=useState(0);const[phase,setPhase]=useState<'ready'|'reading'|'question'>('ready');const[selected,setSelected]=useState('');const[changes,setChanges]=useState(0);const[readMs,setReadMs]=useState(0);const[records,setRecords]=useState<Row[]>([]);const[breakMode,setBreakMode]=useState(false);const readStarted=useRef(0);const questionStarted=useRef(0);const item=items[idx];const choices=useMemo(()=>shuffled(item.choices),[item.id]);
const reset=()=>{setPhase('ready');setSelected('');setChanges(0);setReadMs(0);readStarted.current=0;questionStarted.current=0};
const startRead=()=>{if(busy)return;onActivity();setSelected('');setPhase('reading');readStarted.current=Date.now()};
const finishRead=()=>{if(busy||phase!=='reading')return;onActivity();setReadMs(Math.max(1,Date.now()-readStarted.current));setPhase('question');questionStarted.current=Date.now()};
const choose=(id:string)=>{if(busy||phase!=='question')return;onActivity();if(selected&&selected!==id)setChanges(v=>v+1);setSelected(id)};
const encode=(rs:Row[])=>{const answered=rs.filter(r=>r.answer!=='SKIP'),comp=answered.filter(r=>r.correct).length,words=rs.reduce((s,r)=>s+r.words,0),ms=rs.reduce((s,r)=>s+r.readMs,0);return 'RF|n='+rs.length+'|comp='+comp+'/'+answered.length+'|read='+rs.filter(r=>r.readMs>0).length+'|words='+words+'|ms='+ms+'|r='+rs.map(r=>r.id+'~'+r.answer+'~'+(r.correct?1:0)+'~'+r.words+'~'+r.readMs+'~'+r.questionMs+'~'+r.changes).join(',')};
const next=(skip=false)=>{if((((!selected||phase!=='question')&&!skip))||busy)return;const row:Row={id:item.id,answer:skip?'SKIP':selected,correct:!skip&&selected===item.correct,words:wordCount(item.text),readMs:skip&&phase==='ready'?0:readMs,questionMs:Math.max(0,Date.now()-questionStarted.current),changes};const rs=[...records,row];if(idx===items.length-1){onFinish(encode(rs));return}setRecords(rs);if(idx===3){setBreakMode(true);return}setIdx(v=>v+1);reset()};
const resume=()=>{setBreakMode(false);setIdx(4);reset()};
if(breakMode)return <div className='rf-shell'><header className='rf-top'><div><b>CZA</b><span>Çelik Zihin Akademisi</span></div><em>Sesli Okuma & Akıcılık Laboratuvarı</em></header><main className='rf-main'><section className='rf-break'><div><BookOpenCheck/></div><h1>İlk okuma turu tamam.</h1><p>Şimdi biraz daha uzun metinlerde anlamı koruyarak doğal ve akıcı okumaya devam edeceksin.</p><span>4 görev tamamlandı · 4 görev kaldı</span><button type='button' onClick={resume}>İkinci tura geç <b>→</b></button></section></main></div>;
return <div className='rf-shell'><header className='rf-top'><div><b>CZA</b><span>Çelik Zihin Akademisi</span></div><em>Sesli Okuma & Akıcılık Laboratuvarı</em></header><main className='rf-main'>{err&&<div className='rf-error'>{err}</div>}<section className='rf-card'><div className='rf-progress'><strong>{idx+1}<small>/8</small></strong><div><i style={{width:((idx+1)/8*100)+'%'}}/></div><span>{idx<4?'AKICI OKUMA':'ANLAM + TRANSFER'}</span></div><div className='rf-head'><div><span>CZA SESLİ OKUMA LABORATUVARI</span><h1>{item.title}</h1><p>{phase==='question'?'Metin artık kapalı. Okuduğundan yola çıkarak cevap ver.':'Metni sesli, doğal ve anlamını düşünerek oku. Bu bir hız yarışı değil.'}</p></div><div>{phase==='question'?<BrainCircuit/>:<BookOpenCheck/>}</div></div><div className='rf-stage'>{phase==='ready'?<div className='rf-ready'><div><Play/></div><strong>Hazır olduğunda başlat.</strong><small>Metin açılınca sesli oku. Bitirdiğinde “Okumayı bitirdim” düğmesine dokun.</small><button type='button' onClick={startRead}><Play/> Okumaya başla</button></div>:phase==='reading'?<div className='rf-reading'><div className='rf-live'><span/><strong>SESLİ OKUMA</strong><small>doğal ritimde</small></div><p>{item.text}</p><button type='button' onClick={finishRead}><CheckCircle2/> Okumayı bitirdim</button></div>:<div className='rf-question'><div className='rf-lock'><ShieldCheck/><span><strong>Metin kapandı.</strong><small>Cevabı tekrar metne bakmadan ver.</small></span></div><h2>{item.question}</h2><div className='rf-options'>{choices.map(c=><button type='button' key={c.id} className={selected===c.id?'selected':''} aria-pressed={selected===c.id} onClick={()=>choose(c.id)}><span>{c.label}</span>{selected===c.id&&<b>✓</b>}</button>)}</div></div>}</div><div className='rf-bottom'><div><Gauge/><span><strong>Okuma süresi otomatik kaydediliyor.</strong><small>Doğruluk, atlama, tekrar, duraklama ve öz-düzeltme eğitmen gözlemiyle birlikte yorumlanır; yalnız hızdan puan üretilmez.</small></span></div><div style={{display:'flex',gap:9,flexWrap:'wrap',justifyContent:'flex-end'}}><button type='button' className='cza-btn cza-soft' disabled={busy} onClick={()=>next(true)}>Bu soruyu geç</button><button className='rf-next' disabled={phase!=='question'||!selected||busy} onClick={()=>next(false)}>{busy?'Kaydediliyor…':idx===7?'Okuma Turunu Tamamla':'Sonraki Görev'} <span>→</span></button></div></div><footer className='rf-footer'><span>{studentLabel||'Öğrenci'} · 8 sesli okuma görevi</span><span>doğruluk • akıcılık • anlam • öz-düzeltme</span></footer></section></main></div>;
}

