import { useEffect, useMemo, useRef, useState } from 'react';
import { BrainCircuit, Gauge, ShieldCheck, Sparkles, TimerReset } from 'lucide-react';

type Section='Temel Eşleme'|'Tempo'|'Kural Değişimi'|'Tepki Kontrolü';
type Shape='circle'|'square'|'triangle'|'diamond'|'star'|'arrow';
type Tone='teal'|'gold'|'blue'|'violet'|'coral';
type Mark='none'|'dot'|'bar';
type GlyphDef={shape:Shape;tone:Tone;mark?:Mark;rot?:number;frame?:'red'|'teal'};
type Choice={id:string;glyph?:GlyphDef;label?:string;wait?:boolean};
type Item={id:string;section:Section;title:string;prompt:string;target:GlyphDef;correct:string;choices:Choice[];limit?:number};
type Row={id:string;section:Section;answer:string;score:number;max:number;ms:number;changes:number;timeout:number};

const items:Item[]=[
{id:'B1',section:'Temel Eşleme',title:'Aynısını yakala',prompt:'Hedef kartla her özelliği aynı olan kartı seç.',target:{shape:'diamond',tone:'teal',mark:'dot'},correct:'a',choices:[{id:'a',glyph:{shape:'diamond',tone:'teal',mark:'dot'}},{id:'b',glyph:{shape:'diamond',tone:'blue',mark:'dot'}},{id:'c',glyph:{shape:'diamond',tone:'teal',mark:'bar'}},{id:'d',glyph:{shape:'square',tone:'teal',mark:'dot'}}]},
{id:'B2',section:'Temel Eşleme',title:'Yönü koru',prompt:'Hedef okun baktığı yönü aynen koruyan kartı seç.',target:{shape:'arrow',tone:'blue',rot:90},correct:'b',choices:[{id:'a',glyph:{shape:'arrow',tone:'blue',rot:0}},{id:'b',glyph:{shape:'arrow',tone:'blue',rot:90}},{id:'c',glyph:{shape:'arrow',tone:'blue',rot:180}},{id:'d',glyph:{shape:'arrow',tone:'blue',rot:270}}]},
{id:'B3',section:'Temel Eşleme',title:'İki özelliği birlikte tut',prompt:'Renk, şekil ve iç işaret birlikte aynı olsun.',target:{shape:'triangle',tone:'gold',mark:'bar'},correct:'c',choices:[{id:'a',glyph:{shape:'triangle',tone:'gold',mark:'dot'}},{id:'b',glyph:{shape:'triangle',tone:'violet',mark:'bar'}},{id:'c',glyph:{shape:'triangle',tone:'gold',mark:'bar'}},{id:'d',glyph:{shape:'diamond',tone:'gold',mark:'bar'}}]},
{id:'T1',section:'Tempo',title:'Tempo başladı',prompt:'Aynı kartı bul. Hız için doğruluktan vazgeçme.',target:{shape:'square',tone:'violet',mark:'dot'},correct:'f',limit:8,choices:[{id:'a',glyph:{shape:'square',tone:'blue',mark:'dot'}},{id:'b',glyph:{shape:'circle',tone:'violet',mark:'dot'}},{id:'c',glyph:{shape:'square',tone:'violet',mark:'bar'}},{id:'d',glyph:{shape:'diamond',tone:'violet',mark:'dot'}},{id:'e',glyph:{shape:'square',tone:'coral',mark:'dot'}},{id:'f',glyph:{shape:'square',tone:'violet',mark:'dot'}},{id:'g',glyph:{shape:'triangle',tone:'violet',mark:'dot'}},{id:'h',glyph:{shape:'square',tone:'gold',mark:'none'}}]},
{id:'T2',section:'Tempo',title:'Hedef avı',prompt:'Aynı renk + aynı şekil + aynı işareti birlikte ara.',target:{shape:'circle',tone:'blue',mark:'bar'},correct:'d',limit:8,choices:[{id:'a',glyph:{shape:'circle',tone:'blue',mark:'dot'}},{id:'b',glyph:{shape:'circle',tone:'teal',mark:'bar'}},{id:'c',glyph:{shape:'square',tone:'blue',mark:'bar'}},{id:'d',glyph:{shape:'circle',tone:'blue',mark:'bar'}},{id:'e',glyph:{shape:'diamond',tone:'blue',mark:'bar'}},{id:'f',glyph:{shape:'circle',tone:'gold',mark:'bar'}},{id:'g',glyph:{shape:'triangle',tone:'blue',mark:'bar'}},{id:'h',glyph:{shape:'circle',tone:'violet',mark:'none'}}]},
{id:'T3',section:'Tempo',title:'Kalabalıkta eşini bul',prompt:'Ayrıntıya bak; yalnız tam eşleşen karta dokun.',target:{shape:'diamond',tone:'coral',mark:'none'},correct:'h',limit:8,choices:[{id:'a',glyph:{shape:'diamond',tone:'coral',mark:'dot'}},{id:'b',glyph:{shape:'square',tone:'coral',mark:'none'}},{id:'c',glyph:{shape:'diamond',tone:'gold',mark:'none'}},{id:'d',glyph:{shape:'circle',tone:'coral',mark:'none'}},{id:'e',glyph:{shape:'diamond',tone:'violet',mark:'none'}},{id:'f',glyph:{shape:'triangle',tone:'coral',mark:'none'}},{id:'g',glyph:{shape:'diamond',tone:'coral',mark:'bar'}},{id:'h',glyph:{shape:'diamond',tone:'coral',mark:'none'}}]},
{id:'T4',section:'Tempo',title:'Kuralı uygula',prompt:'Hedefle AYNI şekil, ama FARKLI renk olan kartı seç.',target:{shape:'star',tone:'gold',mark:'none'},correct:'b',limit:9,choices:[{id:'a',glyph:{shape:'star',tone:'gold'}},{id:'b',glyph:{shape:'star',tone:'blue'}},{id:'c',glyph:{shape:'circle',tone:'blue'}},{id:'d',glyph:{shape:'square',tone:'coral'}}]},
{id:'S1',section:'Kural Değişimi',title:'Şekle bak',prompt:'Kural: Rengi unut. Yalnız hedefle AYNI ŞEKİL olan kartı seç.',target:{shape:'star',tone:'gold'},correct:'c',limit:10,choices:[{id:'a',glyph:{shape:'circle',tone:'gold'}},{id:'b',glyph:{shape:'triangle',tone:'coral'}},{id:'c',glyph:{shape:'star',tone:'violet'}},{id:'d',glyph:{shape:'square',tone:'blue'}}]},
{id:'S2',section:'Kural Değişimi',title:'Kural değişti',prompt:'Şimdi şekli unut. Yalnız hedefle AYNI RENK olan kartı seç.',target:{shape:'star',tone:'gold'},correct:'a',limit:10,choices:[{id:'a',glyph:{shape:'circle',tone:'gold'}},{id:'b',glyph:{shape:'star',tone:'blue'}},{id:'c',glyph:{shape:'circle',tone:'violet'}},{id:'d',glyph:{shape:'star',tone:'coral'}}]},
{id:'I1',section:'Tepki Kontrolü',title:'Dur sinyalini uygula',prompt:'Kural: KIRMIZI çerçeve = BEKLE. Turkuaz çerçeve = içteki şeklin eşini seç. Bu kart için doğru hareketi seç.',target:{shape:'triangle',tone:'blue',frame:'red'},correct:'wait',limit:10,choices:[{id:'wait',wait:true,label:'BEKLE'},{id:'a',glyph:{shape:'triangle',tone:'blue'}},{id:'b',glyph:{shape:'triangle',tone:'gold'}},{id:'c',glyph:{shape:'circle',tone:'blue'}}]}
];

function shuffle(a:Choice[]){const x=[...a];for(let i=x.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[x[i],x[j]]=[x[j],x[i]]}return x}
function Glyph({v}:{v:GlyphDef}){const pts=v.shape==='triangle'?'50,13 88,82 12,82':v.shape==='diamond'?'50,8 91,50 50,92 9,50':v.shape==='star'?'50,7 61,36 92,36 67,55 77,86 50,68 23,86 33,55 8,36 39,36':'';return <span className={'hb-glyph '+v.tone+(v.frame?' frame-'+v.frame:'')}><svg viewBox='0 0 100 100' style={{transform:v.shape==='arrow'?'rotate('+(v.rot||0)+'deg)':undefined}} aria-hidden='true'>{v.shape==='circle'?<circle cx='50' cy='50' r='34'/>:v.shape==='square'?<rect x='18' y='18' width='64' height='64' rx='9'/>:v.shape==='arrow'?<path d='M45 13h10v48l17-17 8 8-30 30-30-30 8-8 17 17z'/>:<polygon points={pts}/>} {v.mark==='dot'&&<circle className='hb-mark' cx='50' cy='50' r='8'/>}{v.mark==='bar'&&<rect className='hb-mark' x='37' y='46' width='26' height='8' rx='4'/>}</svg></span>}
function sectionIcon(s:Section){return s==='Temel Eşleme'?<BrainCircuit/>:s==='Tempo'?<Gauge/>:s==='Kural Değişimi'?<TimerReset/>:<ShieldCheck/>}

export default function SpeedBalanceLab({studentLabel,busy,onFinish,err,onActivity}:{studentLabel?:string;busy:boolean;onFinish:(value:string)=>void;err:string;onActivity:()=>void}){
const[idx,setIdx]=useState(0);const[selected,setSelected]=useState('');const[changes,setChanges]=useState(0);const[decisionMs,setDecisionMs]=useState(0);const[records,setRecords]=useState<Row[]>([]);const[breakMode,setBreakMode]=useState(false);const[timeLeft,setTimeLeft]=useState(0);const[expired,setExpired]=useState(false);const[locked,setLocked]=useState(false);const started=useRef(Date.now());const selectedRef=useRef('');const item=items[idx];const choices=useMemo(()=>shuffle(item.choices),[item.id]);
useEffect(()=>{started.current=Date.now();selectedRef.current='';setSelected('');setChanges(0);setDecisionMs(0);setExpired(false);setLocked(false);setTimeLeft(item.limit||0);if(!item.limit)return;const timer=window.setInterval(()=>setTimeLeft(t=>{if(t<=1){window.clearInterval(timer);setLocked(true);if(!selectedRef.current)setExpired(true);return 0}return t-1}),1000);return()=>window.clearInterval(timer)},[item.id]);
const choose=(id:string)=>{if(busy||locked||expired)return;onActivity();if(selectedRef.current&&selectedRef.current!==id)setChanges(v=>v+1);selectedRef.current=id;setSelected(id);setDecisionMs(Math.max(1,Date.now()-started.current))};
const ready=Boolean(selected)||expired;
const encode=(rs:Row[])=>{const stat=(s:Section)=>{const x=rs.filter(r=>r.section===s);return x.reduce((n,r)=>n+r.score,0)+'/'+x.reduce((n,r)=>n+r.max,0)};const timed=rs.filter(r=>r.max>0&&r.section!=='Temel Eşleme'&&!r.timeout&&r.ms>0).map(r=>r.ms).sort((a,b)=>a-b);const med=timed.length?timed[Math.floor(timed.length/2)]:0;return 'HB|n='+rs.length+'|base='+stat('Temel Eşleme')+'|tempo='+stat('Tempo')+'|switch='+stat('Kural Değişimi')+'|inhibit='+stat('Tepki Kontrolü')+'|timeouts='+rs.reduce((n,r)=>n+r.timeout,0)+'|med='+med+'|r='+rs.map(r=>r.id+'~'+r.answer+'~'+r.score+'~'+r.ms+'~'+r.changes+'~'+r.timeout).join(',')};
const next=(skip=false)=>{if((!ready&&!skip)||busy)return;const ans=skip?'SKIP':selected||'TIME';const row:Row={id:item.id,section:item.section,answer:ans,score:skip?0:ans===item.correct?1:0,max:skip?0:1,ms:skip?Math.max(0,decisionMs):selected?decisionMs:(item.limit||0)*1000,changes,timeout:skip?0:expired?1:0};const rs=[...records,row];if(idx===items.length-1){onFinish(encode(rs));return}setRecords(rs);if(idx===4){setBreakMode(true);return}setIdx(v=>v+1)};
const resume=()=>{setBreakMode(false);setIdx(5)};
if(breakMode)return <div className='hb-shell'><header className='hb-top'><div><b>CZA</b><span>Çelik Zihin Akademisi</span></div><em>Hız Dengesi & Tepki Kontrolü</em></header><main className='hb-main'><section className='hb-break'><div><Sparkles/></div><h1>İlk tempo turu tamam.</h1><p>Şimdi kural değişirken doğru kararı koruma ve gerektiğinde kendini durdurma bölümüne geçiyorsun.</p><span>5 görev tamamlandı · 5 görev kaldı</span><button type='button' onClick={resume}>İkinci tura geç <b>→</b></button></section></main></div>;
return <div className='hb-shell'><header className='hb-top'><div><b>CZA</b><span>Çelik Zihin Akademisi</span></div><em>Hız Dengesi & Tepki Kontrolü</em></header><main className='hb-main'>{err&&<div className='hb-error'>{err}</div>}<section className='hb-card'><div className='hb-progress'><strong>{idx+1}<small>/10</small></strong><div><i style={{width:((idx+1)/10*100)+'%'}}/></div><span>{item.section}</span></div><div className='hb-head'><div><span>CZA HIZ–DOĞRULUK LABORATUVARI</span><h1>{item.title}</h1><p>{item.prompt}</p></div><div>{sectionIcon(item.section)}</div></div><div className='hb-stage'><div className='hb-target'><small>HEDEF / SİNYAL</small><Glyph v={item.target}/>{item.limit&&<div className={'hb-timer '+(timeLeft<=3?'urgent':'')}><b>{timeLeft}</b><span>saniye</span></div>}</div>{expired?<div className='hb-expired'><TimerReset/><strong>Süre tamamlandı.</strong><small>Bu da değerlendirme kanıtıdır; doğru cevap gösterilmez.</small></div>:<div className={'hb-options '+(choices.length>4?'dense':'')}>{choices.map(c=><button type='button' key={c.id} disabled={locked&&!selected} className={selected===c.id?'selected':''} onClick={()=>choose(c.id)}>{c.wait?<><ShieldCheck/><strong>{c.label}</strong></>:c.glyph?<Glyph v={c.glyph}/>:<strong>{c.label}</strong>}{selected===c.id&&<b className='hb-check'>✓</b>}</button>)}</div>}{item.limit&&<div className='hb-energy'><i style={{width:(item.limit?timeLeft/item.limit*100:0)+'%'}}/><span>{selected?'Kararın kaydedilmeye hazır.':timeLeft===0?'Tempo bitti.':'Doğru karar + sakin tempo'}</span></div>}</div><div className='hb-bottom'><div><ShieldCheck/><span><strong>Ham süre puan değildir.</strong><small>Sistem doğruluk, tempo altında doğruluğu koruma, kural değişimi, zaman aşımı ve fikir değiştirmeyi birlikte saklar. Cihazlar arası milisaniye farkı tek başına beceri etiketi üretmez.</small></span></div><div style={{display:'flex',gap:9,flexWrap:'wrap',justifyContent:'flex-end'}}><button type='button' className='cza-btn cza-soft' disabled={busy} onClick={()=>next(true)}>Bu soruyu geç</button><button className='hb-next' disabled={!ready||busy} onClick={()=>next(false)}>{busy?'Kaydediliyor…':idx===9?'Tempo Turunu Tamamla':'Sonraki Görev'} <span>→</span></button></div></div><footer className='hb-footer'><span>{studentLabel||'Öğrenci'} · 10 mikro-görev</span><span>tempo • doğruluk • kural değişimi • tepki kontrolü</span></footer></section></main></div>;
}

